import * as XLSX from 'xlsx';
import { isSubtotalRow } from './data-utils';

export interface ColumnDefinition {
  name: string;
  type: string;
  isAutoGenerated?: boolean;
  isRequired?: boolean;
  isUnique?: boolean;    // 추가: 중복 체크 기준 컬럼 여부
  options?: string[]; // 선택 목록 옵션
}

export interface TableData {
  name: string;
  columns: ColumnDefinition[];
  rows: any[];
}

export interface SheetResult {
  sheetName: string;
  tables: TableData[];
}

export interface SelectedField {
  id: string;   // Original Excel column name or '__data_id__'
  name: string; // User defined display name
  isRequired?: boolean;
  type?: string; 
}

export interface TableConfig {
  sheetName: string;      // Original Excel sheet name
  tableName: string;      // Custom table name defined by user
  headerRowIndex: number;
  selectedFields: SelectedField[];
}

/**
 * Parses an Excel workbook and returns data for all sheets and tables.
 */
export function parseExcelWorkbook(buffer: Buffer, configs?: TableConfig[]): SheetResult[] {
  const workbook = XLSX.read(buffer, { type: 'buffer' });
  return workbook.SheetNames.map((name) => {
    const sheet = workbook.Sheets[name];
    const config = configs?.find(c => c.sheetName === name);
    const tables = parseSheet(sheet, config?.tableName || name, config);
    return { sheetName: name, tables };
  });
}

/**
 * Parses a single sheet into one or more tables by finding rows with high column density.
 */
function parseSheet(sheet: XLSX.WorkSheet, sheetName: string, config?: TableConfig): TableData[] {
  const rawRows: any[][] = XLSX.utils.sheet_to_json(sheet, { header: 1 });
  if (rawRows.length === 0) return [];

  let headerRowIndex = config?.headerRowIndex ?? -1;

  if (headerRowIndex === -1) {
    let maxCols = 0;
    for (let i = 0; i < Math.min(rawRows.length, 25); i++) {
        // 집계 행은 헤더로 간주하지 않음
        if (isSubtotalRow(rawRows[i])) continue;
        
        const nonReserved = rawRows[i].filter(cell => cell !== undefined && cell !== null && cell !== '').length;
        if (nonReserved > maxCols) {
            maxCols = nonReserved;
            headerRowIndex = i;
        }
    }
  }

  if (headerRowIndex === -1) return [];

  const originalHeader = rawRows[headerRowIndex].map(h => h?.toString().trim() || '');
  const dataRows = rawRows.slice(headerRowIndex + 1);

  const tables: TableData[] = [];
  const rows: any[] = [];

  // Use config's selectedFields for column definition and sequence
  const columnConfigs: SelectedField[] = config?.selectedFields || originalHeader
    .filter(h => !!h)
    .map(h => ({ id: h, name: h, isRequired: true }));

  let rowCounter = 0;
  dataRows.forEach((row) => {
    const isRowEmpty = row.every(cell => cell === undefined || cell === null || cell === '');
    const isSubtotal = isSubtotalRow(row);

    if (!isRowEmpty && !isSubtotal) {
      rowCounter++;
      const rowObj: any = {};
      let hasData = false;
      
      columnConfigs.forEach((colConfig) => {
        if (colConfig.id === '__data_id__') {
          // Generate virtual Data ID with DID-XXXXXX format
          rowObj[colConfig.name] = `DID-${rowCounter.toString().padStart(6, '0')}`;
          hasData = true;
        } else {
          const colIndex = originalHeader.indexOf(colConfig.id);
          if (colIndex !== -1) {
             const val = row[colIndex];
             rowObj[colConfig.name] = val;
             if (val !== undefined && val !== null && val !== '') hasData = true;
          }
        }
      });
      if (hasData) rows.push(rowObj);
    }
  });

  const columns: ColumnDefinition[] = columnConfigs.map(colConfig => {
      const firstVal = rows[0] ? rows[0][colConfig.name] : null;
      return {
        name: colConfig.name,
        type: typeof firstVal === 'number' ? 'number' : 'string',
        isAutoGenerated: colConfig.id === '__data_id__',
        isRequired: colConfig.isRequired ?? true
      };
  });

  tables.push({
    name: sheetName,
    columns,
    rows,
  });

  return tables;
}
