/**
 * 슬랙 실시간 알림 유틸리티
 */

const SYSTEM_SLACK_WEBHOOK_URL = process.env.SLACK_WEBHOOK_URL;

/**
 * 슬랙으로 메시지를 전송합니다.
 * @param payload 슬랙 API 페이로드 (text 또는 blocks)
 * @param customWebhookUrl 보고서별로 설정된 개별 웹후크 URL (선택 사항)
 */
async function sendSlackMessage(payload: any, customWebhookUrl?: string | null) {
    // 1순위: 보고서별 개별 설정된 웹후크 URL
    // 2순위: 시스템 글로벌 공통 웹후크 URL
    const targetUrl = customWebhookUrl || SYSTEM_SLACK_WEBHOOK_URL;

    if (!targetUrl) {
        console.warn('사용 가능한 슬랙 웹후크 URL이 없어 알림을 건너뜁니다.');
        return;
    }

    try {
        console.log(`슬랙 알림 전송 시도중 (${customWebhookUrl ? '전용 채널' : '공통 채널'})...`, payload.text);
        const response = await fetch(targetUrl, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(payload),
        });

        if (!response.ok) {
            const errorText = await response.text();
            console.error('슬랙 메시지 전송 실패:', errorText);
        } else {
            console.log('슬랙 알림 전송 성공!');
        }
    } catch (err) {
        console.error('슬랙 알림 오류:', err);
    }
}

/**
 * 신규 데이터 단건 등록 알림
 */
export async function notifyNewDataRow(
    reportName: string, 
    userName: string, 
    rowData: any, 
    columns: any[],
    customWebhookUrl?: string | null
) {
    // 첫 번째 컬럼 정보 추출 (보안상 의미 있는 식별자로 활용)
    const firstCol = columns.find(c => !c.isAutoGenerated) || columns[0];
    const firstVal = firstCol ? rowData[firstCol.name] : 'N/A';
    
    // 데이터ID 추출 (있을 경우)
    const dataId = rowData['데이터ID'] || 'N/A';

    const blocks = [
        {
            type: 'header',
            text: {
                type: 'plain_text',
                text: '📢 신규 데이터 등록 알림',
                emoji: true
            }
        },
        {
            type: 'section',
            fields: [
                {
                    type: 'mrkdwn',
                    text: `*보고서:* ${reportName}`
                },
                {
                    type: 'mrkdwn',
                    text: `*등록자:* ${userName}`
                }
            ]
        },
        {
            type: 'section',
            text: {
                type: 'mrkdwn',
                text: `*주요 내용:* [${firstCol?.name || '항목'}] ${firstVal}\n*데이터 ID:* ${dataId}`
            }
        },
        {
            type: 'context',
            elements: [
                {
                    type: 'mrkdwn',
                    text: `🕒 등록 시간: ${new Date().toLocaleString('ko-KR')}`
                }
            ]
        }
    ];

    await sendSlackMessage({
        text: `[${reportName}] 신규 데이터 등록: ${firstVal}`,
        blocks
    }, customWebhookUrl);
}

/**
 * 엑셀 일괄 업로드 완료 알림
 */
export async function notifyBulkUpload(
    reportName: string, 
    userName: string, 
    count: number, 
    representativeRow?: any, 
    columns?: any[],
    customWebhookUrl?: string | null
) {
    const blocks: any[] = [
        {
            type: 'header',
            text: {
                type: 'plain_text',
                text: '📊 엑셀 일괄 업로드 완료',
                emoji: true
            }
        },
        {
            type: 'section',
            fields: [
                {
                    type: 'mrkdwn',
                    text: `*보고서:* ${reportName}`
                },
                {
                    type: 'mrkdwn',
                    text: `*등록자:* ${userName}`
                }
            ]
        },
        {
            type: 'section',
            text: {
                type: 'mrkdwn',
                text: `*업로드 건수:* 총 \`${count}\`건이 성공적으로 등록되었습니다.`
            }
        }
    ];

    // 첫 번째 행의 샘플 정보 추가 (있을 경우)
    if (representativeRow && columns) {
        const firstCol = columns.find(c => !c.isAutoGenerated) || columns[0];
        const firstVal = firstCol ? representativeRow[firstCol.name] : 'N/A';
        
        blocks.push({
            type: 'section',
            text: {
                type: 'mrkdwn',
                text: `*대표 데이터 샘플:* [${firstCol?.name || '항목'}] ${firstVal}`
            }
        });
    }

    blocks.push({
        type: 'context',
        elements: [
            {
                type: 'mrkdwn',
                text: `🕒 완료 시간: ${new Date().toLocaleString('ko-KR')}`
            }
        ]
    });

    await sendSlackMessage({
        text: `[${reportName}] 엑셀 일괄 업로드 완료 (${count}건)`,
        blocks
    }, customWebhookUrl);
}
