import { GoogleGenerativeAI } from "@google/generative-ai";
import { queryTable } from "@/egdesk-helpers";

const apiKey = process.env.GOOGLE_GENERATIVE_AI_API_KEY || "";
const genAI = new GoogleGenerativeAI(apiKey);
const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash" }, { apiVersion: 'v1beta' });

export interface WorkspaceAiResult {
    reportId: string | null;
    reportName: string | null;
    extractedData: Record<string, any> | null;
    confidence: number;
    message: string;
}

/**
 * 워크스페이스에서 입력된 데이터(텍스트/이미지)를 분석하여 
 * 적절한 보고서를 찾고 데이터를 추출합니다.
 */
export async function processWorkspaceInput(
    text: string, 
    imageBase64?: string, 
    mimeType?: string
): Promise<WorkspaceAiResult> {
    if (!apiKey) throw new Error("AI API 키가 설정되지 않았습니다.");

    // 1. 모든 가용 보고서 스키마 조회
    const reports = await queryTable('report', { filters: { isDeleted: '0' } });
    if (!reports || reports.length === 0) {
        return { 
            reportId: null, 
            reportName: null, 
            extractedData: null, 
            confidence: 0, 
            message: "현재 등록된 보고서가 없습니다." 
        };
    }

    // 2. 보고서 식별 (Classification)
    const reportList = reports.map((r: any) => ({
        id: r.id,
        name: r.name,
        description: r.description || "",
        columns: JSON.parse(r.columns).map((c: any) => c.name)
    }));

    const classificationPrompt = `
        당신은 기업 사내 데이터 관리 도우미입니다. 사용자의 입력(텍스트 또는 이미지)을 분석하여 다음 보고서 목록 중 가장 적합한 보고서를 하나 골라주세요.
        
        보고서 목록:
        ${JSON.stringify(reportList, null, 2)}
        
        입력 유형: ${imageBase64 ? "이미지(사진) + 텍스트" : "텍스트 전용"}
        사용자 추가 메시지: "${text || "없음"}"
        
        응답 규칙:
        1. 사진이 영수증이라면 '영수증', '카드', '지출' 등의 키워드가 포함된 보고서를 우선순위로 검토하세요.
        2. 가장 관련성이 높은 보고서의 ID를 반환하세요.
        3. 확신도가 낮거나(0.7 미만) 매칭되는 보고서가 전혀 없을 경우 reportId를 null로 반환하세요.
        4. 반드시 아래 JSON 형식으로만 응답하세요:
        { "reportId": "선택된 ID 또는 null", "confidence": 0.0~1.0, "reason": "선택 이유" }
    `;

    let classification: { reportId: string | null, confidence: number };
    try {
        const contents: any[] = [classificationPrompt];
        if (imageBase64 && mimeType) {
            contents.push({ inlineData: { data: imageBase64, mimeType } });
        }
        const result = await model.generateContent(contents);
        const responseText = result.response.text();
        const jsonMatch = responseText.match(/\{[\s\S]*\}/);
        classification = jsonMatch ? JSON.parse(jsonMatch[0]) : { reportId: null, confidence: 0 };
    } catch (e) {
        console.error("Classification failure:", e);
        classification = { reportId: null, confidence: 0 };
    }

    if (!classification.reportId || classification.confidence < 0.7) {
        return {
            reportId: null,
            reportName: null,
            extractedData: null,
            confidence: classification.confidence,
            message: "매칭되는 보고서를 찾을 수 없습니다. 현재 '신용카드영수증' 테이블이 활성화되어 있는지 확인해 주세요."
        };
    }

    const selectedReport = reports.find((r: any) => String(r.id) === String(classification.reportId));
    if (!selectedReport) {
        return { reportId: null, reportName: null, extractedData: null, confidence: 0, message: "보고서 매칭 오류가 발생했습니다." };
    }
    const columns = JSON.parse(selectedReport.columns);

    // 3. 데이터 추출 (Extraction) - 시맨틱 매핑 강화
    const extractionPrompt = `
        사용자의 입력(이미지 및 텍스트)을 분석하여 보고서 '${selectedReport.name}'의 컬럼 정의에 맞는 데이터를 추출하세요.
        
        컬럼 정의 (시맨틱 매핑 필요):
        ${columns.map((c: any) => `- ${c.name} (타입: ${c.type}${c.options ? `, 옵션: ${c.options.join(',')}` : ''}${c.isAutoGenerated ? ', 자동생성컬럼' : ''})`).join('\n')}
        
        중요 지침:
        1. 시맨틱 매핑: 이미지 속의 필드명이 컬럼명과 정확히 일치하지 않더라도 의미상 동일하면 매핑하세요. 
           (예: 영수증의 '일시' -> '승인일시', '금액' -> '사용금액', '상호' -> '가맹점명')
        2. 타입 변환:
           - 날짜: '2024년 04월 06일' 등은 반드시 'YYYY-MM-DD' 또는 'YYYY-MM-DD HH:mm:ss' 형식으로 변환하세요.
           - 숫자: '15,000원' 등은 통화 기호와 콤마를 제거하고 순수 숫자만 추출하세요.
        3. 필드가 자동생성컬럼(isAutoGenerated: true)인 경우 null을 반환하세요.
        4. 찾을 수 없는 필드는 null로 표시하세요.
        5. 결과는 반드시 JSON 객체 하나만 반환하세요. 설명이나 서술은 생략하세요.
    `;

    let extractedData: any = null;
    try {
        const contents: any[] = [extractionPrompt];
        if (imageBase64 && mimeType) {
            contents.push({ inlineData: { data: imageBase64, mimeType } });
        }
        
        const result = await model.generateContent(contents);
        const responseText = result.response.text();
        const jsonMatch = responseText.match(/\{[\s\S]*\}/);
        extractedData = jsonMatch ? JSON.parse(jsonMatch[0]) : null;
    } catch (e) {
        console.error("Extraction failure:", e);
    }

    return {
        reportId: selectedReport.id,
        reportName: selectedReport.name,
        extractedData,
        confidence: classification.confidence,
        message: extractedData ? `[${selectedReport.name}]에 데이터를 기록했습니다.` : "데이터 추출에 실패했습니다."
    };
}
