'use server';

import { revalidatePath } from 'next/cache';
import { redirect } from 'next/navigation';
import { cookies } from 'next/headers';
import { 
    queryTable, 
    insertRows, 
    updateRows, 
    deleteRows, 
    aggregateTable,
    createTable,
    listTables
} from '@/egdesk-helpers';
import { EGDESK_CONFIG } from '@/egdesk.config';
import { parseExcelWorkbook } from '@/lib/excel-parser';
import { analyzeExcelImage, extractDataFromImage, recommendSchemaFromSample } from '@/lib/ai-vision';
import crypto from 'crypto';
import fs from 'fs/promises';
import path from 'path';
import { notifyNewDataRow, notifyBulkUpload } from '@/lib/notifications';
import { getVisualizationRecommendation } from '@/lib/dashboard-ai';
import { runAITool } from '@/lib/ai-tools';

// Password Security Utilities
const SALT_SIZE = 16;
const KEY_LEN = 64;

function hashPassword(password: string): string {
    const salt = crypto.randomBytes(SALT_SIZE).toString('hex');
    const derivedKey = crypto.scryptSync(password, salt, KEY_LEN);
    return `${salt}:${derivedKey.toString('hex')}`;
}

function verifyPassword(password: string, storedHash: string): boolean {
    if (!storedHash) return false;
    const parts = storedHash.split(':');
    if (parts.length !== 2) return false;
    const [salt, hash] = parts;
    const derivedKey = crypto.scryptSync(password, salt, KEY_LEN);
    return derivedKey.toString('hex') === hash;
}

/**
 * 보고서에 대한 사용자의 접근 권한을 확인합니다.
 * ADMIN, EDITOR는 모든 권한을 가지며, VIEWER는 명시적으로 권한이 부여되었거나 소유자인 경우에만 허용합니다.
 */
async function checkReportAuthorization(reportId: string, userId: string, role: string) {
    if (role === 'ADMIN' || role === 'EDITOR') return true;
    
    const reports = await queryTable('report', { filters: { id: reportId } });
    const report = reports[0];
    
    if (!report) return false;
    if (report.ownerId === userId) return true;
    
    // report_access 테이블 확인
    const accessList = await queryTable('report_access', { 
        filters: { reportId, userId } 
    });
    
    return accessList.length > 0;
}

export async function uploadFileAction(formData: FormData) {
    const file = formData.get('file') as File;
    if (!file) throw new Error('파일이 없습니다.');

    const bytes = await file.arrayBuffer();
    const buffer = Buffer.from(bytes);

    const uploadDir = path.join(process.cwd(), 'public', 'uploads');
    try {
        await fs.access(uploadDir);
    } catch {
        await fs.mkdir(uploadDir, { recursive: true });
    }

    const uniqueName = `${Date.now()}-${file.name.replace(/\s+/g, '_')}`;
    const filePath = path.join(uploadDir, uniqueName);
    await fs.writeFile(filePath, buffer);

    return { url: `/uploads/${uniqueName}`, name: file.name };
}

export async function getSchemaRecommendationAction(reportId: string) {
    const reports = await queryTable('report', { filters: { id: reportId } });
    const report = reports[0];
    if (!report) throw new Error('보고서를 찾을 수 없습니다.');

    const currentColumns = JSON.parse(report.columns);
    const sampleRows = await queryTable('report_row', { 
        filters: { reportId },
        limit: 20
    });

    const rowsData = sampleRows.map((r: any) => JSON.parse(r.data));
    const recommendation = await recommendSchemaFromSample(currentColumns, rowsData);
    
    return recommendation.columns;
}

/**
 * 데이터 행의 중복 여부를 판단하기 위한 해시값을 생성합니다.
 * @param rowData 객체 형태의 행 데이터
 * @param columns 컬럼 정의 배열
 */
export async function generateContentHash(rowData: any, columns: any[]) {
    // 자동 생성 필드(데이터 ID 등)는 중복 체크에서 제외
    // 사용자가 'isUnique'로 설정한 필드가 있다면 해당 필드들만 조합, 없으면 모든 일반 필드 조합
    const uniqueCols = columns.filter(c => c.isUnique);
    const targetCols = uniqueCols.length > 0 ? uniqueCols : columns.filter(c => !c.isAutoGenerated);
    
    const sortedKeys = targetCols.map(c => c.name).sort();
    const hashSource = sortedKeys.map(key => `${key}:${rowData[key] ?? ''}`).join('|');
    
    return crypto.createHash('sha256').update(hashSource).digest('hex');
}

export async function uploadExcelAction(formData: FormData, userId: string) {
  const user = await getSessionAction();
  if (!user) throw new Error('인증이 필요합니다.');

  const file = formData.get('file') as File;
  const configsJson = formData.get('configsJson') as string;
  if (!file) throw new Error('파일이 없습니다.');

  const buffer = Buffer.from(await file.arrayBuffer());
  const configs = configsJson ? JSON.parse(configsJson) : [];
  
  // Use the advanced parser with user-defined configs (header row index, selected fields)
  const sheetResults = parseExcelWorkbook(buffer, configs);

  // Store each sheet/table as a separate report
  for (const sheet of sheetResults) {
    for (const table of sheet.tables) {
      if (table.columns.length === 0) continue; // Skip if no columns selected

      const reportId = crypto.randomUUID();
      await insertRows('report', [{
        id: reportId,
        name: table.name,
        sheetName: sheet.sheetName,
        columns: JSON.stringify(table.columns),
        ownerId: userId,
        createdAt: new Date().toISOString()
      }]);

      if (table.rows.length > 0) {
        await insertRows('report_row', table.rows.map(row => ({
          id: crypto.randomUUID(),
          reportId: reportId,
          data: JSON.stringify(row),
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString()
        })));

        // 슬랙 알림 발송 - 신규 보고서 생성 및 초기 데이터 알림
        notifyBulkUpload(table.name, user.fullName || user.username, table.rows.length, table.rows[0], table.columns, null).catch(console.error);
      }
    }
  }

  revalidatePath('/');
}

export async function addRowAction(reportId: string, rowData: any) {
  // 4. 세션 사용자 확인 및 권한 체크
  const user = await getSessionAction();
  if (!user) throw new Error('인증이 필요합니다.');
  
  const isAuthorized = await checkReportAuthorization(reportId, user.id, user.role);
  if (!isAuthorized) throw new Error('해당 보고서에 대한 접근 권한이 없습니다.');

  const reports = await queryTable('report', { filters: { id: reportId } });
  const report = reports[0];
  if (!report) throw new Error('보고서를 찾을 수 없습니다.');

  const columns = JSON.parse(report.columns);
  
  // 1. 중복 체크
  const hash = await generateContentHash(rowData, columns);
  const existingRows = await queryTable('report_row', {
      filters: { reportId, contentHash: hash, isDeleted: '0' }
  });
  
  if (existingRows.length > 0) {
      throw new Error('이미 동일한 내용의 데이터가 존재합니다. (중복 방지)');
  }

  // 2. DID-일련번호 자동 키 생성
  const rowCountResult = await aggregateTable('report_row', 'id', 'COUNT', { filters: { reportId } });
  const rowCount = Number(rowCountResult) || 0;
  const nextSerial = (rowCount + 1).toString().padStart(6, '0');
  
  const finalData = { ...rowData };
  columns.forEach((col: any) => {
    if (col.isAutoGenerated) {
        finalData[col.name] = `DID-${nextSerial}`;
    }
  });

  // 3. Server-side Validation
  for (const col of columns) {
    if (col.isAutoGenerated) continue;
    const val = finalData[col.name];

    if (col.isRequired && (val === undefined || val === null || val === '')) {
        throw new Error(`'${col.name}' 필드는 필수입니다.`);
    }

    if ((col.type === 'number' || col.type === 'currency') && val !== '' && val !== null && val !== undefined) {
        const sVal = String(val);
        const cleanVal = sVal.replace(/[^0-9.-]/g, '').trim();
        if (isNaN(Number(cleanVal))) {
            throw new Error('필드 ' + col.name + '에는 숫자만 입력 가능합니다.');
        }
        finalData[col.name] = Number(cleanVal);
    }
  }

  const creatorId = user.id;

  // 5. 저장
  await insertRows('report_row', [{
    id: crypto.randomUUID(),
    reportId,
    data: JSON.stringify(finalData),
    contentHash: hash,
    creatorId: creatorId,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    isDeleted: 0
  }]);
    
  // 슬랙 알림 발송 - 비동기로 처리하여 사용자 응답 속도에 영향을 주지 않음
  notifyNewDataRow(report.name, user.fullName || user.username, finalData, columns, report.slackWebhookUrl).catch(console.error);

  revalidatePath(`/report/${reportId}`);
  return { success: true };
}

/**
 * 특정 행의 상세 감사 정보(생성/수정/이력)를 조회합니다.
 */
export async function getRowHistoryAction(rowId: string) {
    const rows = await queryTable('report_row', { filters: { id: rowId } });
    const row = rows[0];

    if (!row) throw new Error('데이터를 찾을 수 없습니다.');

    // 작성자 조회
    const creators = row.creatorId 
        ? await queryTable('user', { filters: { id: row.creatorId } })
        : [];
    const updaters = row.updaterId 
        ? await queryTable('user', { filters: { id: row.updaterId } })
        : [];
    
    // 히스토리 조회
    const histories = await queryTable('report_row_history', { 
        filters: { rowId },
        orderBy: 'changedAt',
        orderDirection: 'DESC'
    });

    // 히스토리 작성자 정보를 위해 모든 history에 대해 사용자 정보 추가 조회
    const historyWithUsers = await Promise.all(
        histories.map(async (h: any) => {
            const users = await queryTable('user', { filters: { id: h.changedById } });
            return { ...h, changedBy: users[0] || null };
        })
    );

    return {
        id: row.id,
        createdAt: row.createdAt,
        updatedAt: row.updatedAt,
        creator: creators[0] || null,
        updater: updaters[0] || null,
        histories: historyWithUsers
    };
}

export async function deleteReportAction(reportId: string) {
    await updateRows('report', { 
        isDeleted: 1,
        deletedAt: new Date().toISOString()
    }, { filters: { id: reportId } });
    revalidatePath('/');
    revalidatePath('/archive');
}

export async function restoreReportAction(reportId: string) {
    await updateRows('report', { 
        isDeleted: 0,
        deletedAt: null
    }, { filters: { id: reportId } });
    revalidatePath('/');
    revalidatePath('/archive');
}

export async function permanentDeleteReportAction(reportId: string) {
    // 1. 데이터(행) 먼저 삭제
    await deleteRows('report_row', { filters: { reportId } });
    // 2. 보고서 본체 삭제
    await deleteRows('report', { filters: { id: reportId } });
    
    revalidatePath('/');
    revalidatePath('/archive');
}

export async function deleteRowsAction(reportId: string, rowIds: string[]) {
    const user = await getSessionAction();
    if (!user) throw new Error('인증이 필요합니다.');
    const updaterId = user.id;

    const isAuthorized = await checkReportAuthorization(reportId, user.id, user.role);
    if (!isAuthorized) throw new Error('해당 보고서에 대한 접근 권한이 없습니다.');

    // 1. 대상 행 로드
    const rows = await Promise.all(
        rowIds.map(async (id) => {
            const results = await queryTable('report_row', { filters: { id } });
            return results[0];
        })
    );
    const validRows = rows.filter(r => r);

    // 일반 사용자(VIEWER) 권한 일 때 타인의 데이터 삭제 시도 차단
    if (user.role === 'VIEWER') {
        const hasUnauthorized = validRows.some(r => r.creatorId !== user.id);
        if (hasUnauthorized) {
            throw new Error('본인이 작성하지 않은 데이터는 삭제할 수 없습니다.');
        }
    }

    // 2. 논리적 삭제 및 이력 생성
    for (const row of validRows) {
        await updateRows('report_row', {
            isDeleted: 1,
            deletedAt: new Date().toISOString(),
            updaterId: updaterId
        }, { filters: { id: row.id } });

        await insertRows('report_row_history', [{
            id: crypto.randomUUID(),
            rowId: row.id,
            oldData: row.data,
            newData: JSON.stringify({ ...JSON.parse(row.data), _deleted: true }),
            changeType: 'DELETE',
            changedById: updaterId || 'system',
            changedAt: new Date().toISOString()
        }]);
    }

    revalidatePath(`/report/${reportId}`);
    revalidatePath('/archive');
}

export async function bulkUpdateRowsAction(
    reportId: string, 
    rowIds: string[], 
    fieldName: string, 
    actionType: 'OVERWRITE' | 'FIND_REPLACE', 
    params: { value?: any; find?: string; replace?: string }
) {
    const user = await getSessionAction();
    if (!user) throw new Error('인증이 필요합니다.');
    
    const isAuthorized = await checkReportAuthorization(reportId, user.id, user.role);
    if (!isAuthorized) throw new Error('해당 보고서에 대한 접근 권한이 없습니다.');

    const reports = await queryTable('report', { filters: { id: reportId } });
    const report = reports[0];
    if (!report) throw new Error('보고서를 찾을 수 없습니다.');

    const columns = JSON.parse(report.columns);
    const colDef = columns.find((c: any) => c.name === fieldName);
    if (!colDef) throw new Error('컬럼 정의를 찾을 수 없습니다.');

    // 1. 대상 행 로드
    const rows = await Promise.all(
        rowIds.map(async (id) => {
            const results = await queryTable('report_row', { filters: { id, reportId } });
            return results[0];
        })
    );
    const validRows = rows.filter(r => r);

    if (validRows.length === 0) throw new Error('수정할 데이터가 없습니다.');

    const updaterId = user.id;

    // 일반 사용자(VIEWER) 권한 일 때 타인의 데이터 수정 시도 차단
    if (user.role === 'VIEWER') {
        const hasUnauthorized = validRows.some(r => r.creatorId !== user.id);
        if (hasUnauthorized) {
            throw new Error('본인이 작성하지 않은 데이터는 일괄 수정할 수 없습니다.');
        }
    }

    // 2. 일괄 업데이트 처리
    for (const row of validRows) {
        const oldData = row.data;
        const rowData = JSON.parse(row.data);
        let newValue = params.value;

        if (actionType === 'FIND_REPLACE') {
            const currentVal = String(rowData[fieldName] || '');
            newValue = currentVal.replace(new RegExp(params.find || '', 'g'), params.replace || '');
            
            // 타입 복원 (숫자/통화인 경우)
            if (colDef.type === 'number' || colDef.type === 'currency') {
                const cleanVal = newValue.replace(/[^0-9.-]/g, '').trim();
                newValue = isNaN(Number(cleanVal)) ? newValue : Number(cleanVal);
            }
        }

        // 유효성 검사 (Overwrite인 경우에도 적용)
        if (colDef.type === 'number' || colDef.type === 'currency') {
            const sVal = String(newValue);
            const cleanVal = sVal.replace(/[^0-9.-]/g, '').trim();
            if (isNaN(Number(cleanVal))) {
                throw new Error(`${fieldName} 필드에는 숫자만 입력 가능합니다.`);
            }
            newValue = Number(cleanVal);
        }

        rowData[fieldName] = newValue;

        // 중복 체크용 해시 재생성
        const newHash = await generateContentHash(rowData, columns);
        
        // 3. 개별 업데이트 및 이력 생성
        await updateRows('report_row', {
            data: JSON.stringify(rowData),
            contentHash: newHash,
            updaterId: updaterId,
            updatedAt: new Date().toISOString()
        }, { filters: { id: row.id } });

        await insertRows('report_row_history', [{
            id: crypto.randomUUID(),
            rowId: row.id,
            oldData: oldData,
            newData: JSON.stringify(rowData),
            changeType: 'UPDATE',
            changedById: updaterId || 'system',
            changedAt: new Date().toISOString()
        }]);
    }

    revalidatePath(`/report/${reportId}`);
    return { success: true, count: validRows.length };
}


export async function updateSingleRowAction(
    reportId: string, 
    rowId: string, 
    newData: any
) {
    const user = await getSessionAction();
    if (!user) throw new Error('인증이 필요합니다.');
    
    const isAuthorized = await checkReportAuthorization(reportId, user.id, user.role);
    if (!isAuthorized) throw new Error('해당 보고서에 대한 접근 권한이 없습니다.');

    const reports = await queryTable('report', { filters: { id: reportId } });
    const report = reports[0];
    if (!report) throw new Error('보고서를 찾을 수 없습니다.');

    const columns = JSON.parse(report.columns);
    
    // 1. 중복 체크용 해시 생성
    const hash = await generateContentHash(newData, columns);
    const existingRows = await queryTable('report_row', {
        filters: { 
            reportId, 
            contentHash: hash
        }
    });
    
    const existing = existingRows.find((r: any) => r.id !== rowId);
    
    if (existing) {
        throw new Error('이미 동일한 내용의 데이터가 존재합니다. (중복 방지)');
    }

    // 2. 유효성 검사
    const finalData = { ...newData };
    for (const col of columns) {
        if (col.isAutoGenerated) continue;
        const val = finalData[col.name];

        if (col.isRequired && (val === undefined || val === null || val === '')) {
            throw new Error(`'${col.name}' 필드는 필수입니다.`);
        }

        if ((col.type === 'number' || col.type === 'currency') && val !== '' && val !== null && val !== undefined) {
            const sVal = String(val);
            const cleanVal = sVal.replace(/[^0-9.-]/g, '').trim();
            if (isNaN(Number(cleanVal))) {
                throw new Error(`${col.name} 필드에는 숫자만 입력 가능합니다.`);
            }
            finalData[col.name] = Number(cleanVal);
        }
    }

    // 3. 업데이트 및 이력 생성
    const updaterId = user.id;
    const oldRows = await queryTable('report_row', { filters: { id: rowId } });
    const oldRow = oldRows[0];
    
    if (!oldRow) throw new Error('기존 데이터를 찾을 수 없습니다.');

    // 일반 사용자(VIEWER) 권한 일 때 타인의 데이터 수정 시도 차단
    if (user.role === 'VIEWER' && oldRow.creatorId !== user.id) {
        throw new Error('본인이 작성하지 않은 데이터는 수정할 수 없습니다.');
    }

    await updateRows('report_row', {
        data: JSON.stringify(finalData),
        contentHash: hash,
        updaterId: updaterId,
        updatedAt: new Date().toISOString()
    }, { filters: { id: rowId } });

    await insertRows('report_row_history', [{
        id: crypto.randomUUID(),
        rowId: rowId,
        oldData: oldRow.data,
        newData: JSON.stringify(finalData),
        changeType: 'UPDATE',
        changedById: updaterId || 'system',
        changedAt: new Date().toISOString()
    }]);

    revalidatePath(`/report/${reportId}`);
    return { success: true };
}

export async function renameReportAction(reportId: string, newName: string) {
    await updateRows('report', { name: newName }, { filters: { id: reportId } });
    revalidatePath(`/report/${reportId}`);
    revalidatePath('/');
}

export async function updateReportWebhookAction(reportId: string, webhookUrl: string | null) {
    const user = await getSessionAction();
    if (!user) throw new Error('인증이 필요합니다.');

    const isAuthorized = await checkReportAuthorization(reportId, user.id, user.role);
    if (!isAuthorized) throw new Error('해당 보고서에 대한 접근 권한이 없습니다.');

    await updateRows('report', { slackWebhookUrl: webhookUrl }, { filters: { id: reportId } });
    
    revalidatePath(`/report/${reportId}`);
    return { success: true };
}

export async function updateReportSchemaAction(reportId: string, columns: any[]) {
    await updateRows('report', { columns: JSON.stringify(columns) }, { filters: { id: reportId } });
    revalidatePath(`/report/${reportId}`);
}

export async function analyzeExcelScreenshotAction(formData: FormData) {
  const image = formData.get('image') as File;
  if (!image) throw new Error('이미지 파일이 없습니다.');

  const arrayBuffer = await image.arrayBuffer();
  const buffer = Buffer.from(arrayBuffer);
  const base64 = buffer.toString('base64');
  const mimeType = image.type;

  return await analyzeExcelImage(base64, mimeType);
}

export async function addRowsAction(reportId: string, rows: any[]) {
    const user = await getSessionAction();
    if (!user) throw new Error('인증이 필요합니다.');

    const isAuthorized = await checkReportAuthorization(reportId, user.id, user.role);
    if (!isAuthorized) throw new Error('해당 보고서에 대한 접근 권한이 없습니다.');

    const creatorId = user.id;

    const reports = await queryTable('report', { filters: { id: reportId } });
    const report = reports[0];
    if (!report) throw new Error('보고서를 찾을 수 없습니다.');
  
    const columns = JSON.parse(report.columns);
    const rowCountResult = await aggregateTable('report_row', 'id', 'COUNT', { filters: { reportId } });
    const initialRowCount = Number(rowCountResult) || 0;
    let skippedCount = 0;
    
    // 1. 기존 데이터의 해시값 로드 (중복 체크용) - 삭제되지 않은 행만 대상
    const existingRows = await queryTable('report_row', {
        filters: { reportId, isDeleted: '0' }
    });
    const existingHashes = new Set(existingRows.map((r: any) => r.contentHash).filter((h: any) => h));

    // 2. 각 행당 유효성 검사 및 정제
    const cleanedRowsToInsert = [];
    
    for (const rowData of rows) {
        const finalData: any = {};
        
        // 매핑
        columns.forEach((col: any) => {
            if (!col.isAutoGenerated) {
                finalData[col.name] = rowData[col.name];
            }
        });

        // 중복 체크용 해시 생성
        const hash = await generateContentHash(finalData, columns);
        
        if (existingHashes.has(hash)) {
            skippedCount++;
            continue; 
        }

        // 유효성 검사 및 정제
        for (const col of columns) {
            if (col.isAutoGenerated) continue;
            const val = finalData[col.name];

            if (col.isRequired && (val === undefined || val === null || val === '')) {
                if (val !== 0) throw new Error('필드 ' + col.name + '에 값이 누락되었습니다.');
            }

            if ((col.type === 'number' || col.type === 'currency') && val !== '' && val !== null && val !== undefined) {
                const sVal = String(val);
                const cleanVal = sVal.replace(/[^0-9.-]/g, '').trim();
                const numericVal = Number(cleanVal);
                if (!isNaN(numericVal)) {
                    finalData[col.name] = numericVal;
                }
            }
        }

        // 인서트 데이터 구성
        const nextSerial = (initialRowCount + cleanedRowsToInsert.length + 1).toString().padStart(6, '0');
        const rowWithMetadata: any = { ...finalData };
        
        columns.forEach((col: any) => {
            if (col.isAutoGenerated) {
                rowWithMetadata[col.name] = 'DID-' + nextSerial;
            }
        });

        cleanedRowsToInsert.push({
            id: crypto.randomUUID(),
            data: JSON.stringify(rowWithMetadata),
            contentHash: hash,
            reportId: reportId,
            creatorId: creatorId,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
            isDeleted: 0
        });
        
        existingHashes.add(hash);
    }
  
    if (cleanedRowsToInsert.length > 0) {
        await insertRows('report_row', cleanedRowsToInsert);
    }
  
    if (cleanedRowsToInsert.length > 0) {
        // 슬랙 알림 발송 - 첫 번째 행을 대표 데이터로 사용
        const firstRowData = JSON.parse(cleanedRowsToInsert[0].data);
        notifyBulkUpload(report.name, user.fullName || user.username, cleanedRowsToInsert.length, firstRowData, columns, report.slackWebhookUrl).catch(console.error);
    }

    revalidatePath('/report/' + reportId);
    return { 
        success: true, 
        addedCount: cleanedRowsToInsert.length, 
        skippedCount 
    };
}

export async function createManualReportAction(name: string, sheetName: string, columns: any[]) {
    // 1. 유저 확인
    const users = await queryTable('user', { filters: { username: 'admin_user' } });
    let user = users[0];
    if (!user) {
        const newUserId = crypto.randomUUID();
        await insertRows('user', [{
            id: newUserId,
            username: 'admin_user',
            role: 'ADMIN',
            isActive: 1
        }]);
        user = { id: newUserId };
    }

    // 2. 컬럼 준비 (Data ID 가 없으면 첫 번째로 자동 추가)
    const hasAutoId = columns.some(c => c.isAutoGenerated);
    let finalColumns = [...columns];
    if (!hasAutoId) {
        finalColumns = [
            { id: 'did', name: '데이터 ID', type: 'string', isRequired: true, isAutoGenerated: true },
            ...columns
        ];
    }

    // 3. 보고서 생성
    const reportId = crypto.randomUUID();
    await insertRows('report', [{
        id: reportId,
        name,
        sheetName,
        columns: JSON.stringify(finalColumns),
        ownerId: user.id,
        createdAt: new Date().toISOString()
    }]);

    revalidatePath('/');
    redirect(`/report/${reportId}?action=new`);
}

export async function analyzeImageAndExtractDataAction(formData: FormData, columnsJson: string) {
    try {
        const image = formData.get('image') as File;
        if (!image) throw new Error('이미지 파일이 없습니다.');
        
        console.log(`Analyzing image: ${image.name}, size: ${Math.round(image.size / 1024)} KB, type: ${image.type}`);

        const columns = JSON.parse(columnsJson);
        const arrayBuffer = await image.arrayBuffer();
        const buffer = Buffer.from(arrayBuffer);
        const base64 = buffer.toString('base64');
        const mimeType = image.type;

        const extractedData = await extractDataFromImage(base64, mimeType, columns);
        return { success: true, data: extractedData };
    } catch (error: any) {
        console.error("AI Analysis Action Error:", error);
        // 에러 메시지를 가공하여 사용자에게 친숙하게 전달
        let errorMessage = error.message || '이미지를 분석하는 중 오류가 발생했습니다.';
        if (errorMessage.includes('413')) {
            errorMessage = '이미지 용량이 너무 큽니다. 더 작은 이미지를 사용해 주세요.';
        }
        return { success: false, error: errorMessage };
    }
}


export async function loginAction(username: string, password?: string) {
    const trimmedUsername = username.trim();

    // Check if admin_user exists, create if not
    const admins = await queryTable('user', { filters: { username: 'admin_user' } });
    const existingAdmin = admins[0];
    
    if (!existingAdmin) {
        await insertRows('user', [{ 
            id: crypto.randomUUID(),
            username: 'admin_user', 
            role: 'ADMIN', 
            fullName: '초기 관리자', 
            isActive: 1,
            password: hashPassword('admin123!') // 기본 비밀번호 설정
        }]);
    } else if (!existingAdmin.isActive && trimmedUsername === 'admin_user') {
        // Emergency reactivate admin_user if it's the target login and is deactivated
        await updateRows('user', { isActive: 1 }, { filters: { username: 'admin_user' } });
    }

    const users = await queryTable('user', { filters: { username: trimmedUsername } });
    const user = users[0];
    
    if (!user || user.isActive === 0) {
        throw new Error('존재하지 않거나 비활성화된 계정입니다.');
    }

    // 비밀번호 검증 (이미 설정된 비밀번호가 있는 경우)
    if (user.password && password) {
        const isValid = verifyPassword(password, user.password);
        if (!isValid) {
            throw new Error('비밀번호가 일치하지 않습니다.');
        }
    } else if (user.password && !password) {
        throw new Error('비밀번호를 입력해 주세요.');
    }

    const cookieStore = await cookies();
    cookieStore.set('session_user_id', user.id, {
        httpOnly: true,
        secure: process.env.NODE_ENV === 'production',
        sameSite: 'lax',
        maxAge: 60 * 60 * 24 * 7, // 1 week
        path: '/'
    });

    return { success: true, user };
}

export async function logoutAction() {
    const cookieStore = await cookies();
    cookieStore.delete('session_user_id');
    redirect('/login');
}

export async function getVisualizationRecommendationAction(tableIds: string[], messages: any[]) {
    const user = await getSessionAction();
    if (!user) throw new Error('인증이 필요합니다.');
    
    return await getVisualizationRecommendation(tableIds, messages);
}

export async function getSessionAction() {
    const cookieStore = await cookies();
    const userId = cookieStore.get('session_user_id')?.value;
    
    if (!userId) return null;

    const users = await queryTable('user', { filters: { id: userId } });
    const user = users[0];

    if (!user || user.isActive === 0) {
        return null;
    }

    return user;
}


export async function getUsersAction() {
    const session = await getSessionAction();
    if (!session || (session.role !== 'ADMIN' && session.role !== 'EDITOR')) {
        throw new Error('접근 권한이 없습니다.');
    }

    const users = await queryTable('user', { 
        orderBy: 'username',
        orderDirection: 'ASC'
    });

    return users.map((user: any) => ({
        ...user,
        hasPassword: !!user.password,
        password: undefined
    }));
}

export async function updateUserAction(userId: string, data: any) {
    const session = await getSessionAction();
    if (!session || (session.role !== 'ADMIN' && session.role !== 'EDITOR')) {
        throw new Error('접근 권한이 없습니다.');
    }

    // admin_user 본인의 역할이나 활성화 상태 변경은 제한 (안전장치)
    const targetUsers = await queryTable('user', { filters: { id: userId } });
    const targetUser = targetUsers[0];
    if (targetUser?.username === 'admin_user') {
        if (data.role !== 'ADMIN' || data.isActive === false) {
            throw new Error('기본 관리자 계정의 권한이나 활성 상태는 변경할 수 없습니다.');
        }
    }

    const { username, role, fullName, employeeId, isActive, password } = data;
    const finalEmployeeId = employeeId?.trim() || null;

    // 아이디 중복 체크 (수정 시 본인 제외)
    if (username) {
        const trimmedUsername = username.trim();
        const existingUsers = await queryTable('user', { filters: { username: trimmedUsername } });
        if (existingUsers.length > 0 && existingUsers[0].id !== userId) {
            throw new Error('이미 사용 중인 아이디입니다.');
        }
    }

    // 사번 중복 체크 (수정 시 본인 제외)
    if (finalEmployeeId) {
        const existingEmps = await queryTable('user', { filters: { employeeId: finalEmployeeId } });
        if (existingEmps.length > 0 && existingEmps[0].id !== userId) {
            throw new Error('이미 다른 사용자가 사용 중인 사번입니다.');
        }
    }
    
    await updateRows('user', { 
        username: username?.trim(), 
        role, 
        fullName: fullName?.trim(), 
        employeeId: finalEmployeeId, 
        isActive: isActive === undefined ? 1 : (isActive ? 1 : 0),
        ...(password ? { password: hashPassword(password) } : {})
    }, { filters: { id: userId } });

    revalidatePath('/users');
    revalidatePath('/');
    return { success: true };
}

export async function createUserAction(data: any) {
    const session = await getSessionAction();
    if (!session || (session.role !== 'ADMIN' && session.role !== 'EDITOR')) {
        throw new Error('접근 권한이 없습니다.');
    }

    const { username, role, fullName, employeeId, password } = data;
    const trimmedUsername = username.trim();
    const finalEmployeeId = employeeId?.trim() || null;
    
    // 아이디 중복 체크
    const existingUsers = await queryTable('user', { filters: { username: trimmedUsername } });
    if (existingUsers.length > 0) throw new Error('이미 존재하는 아이디입니다.');

    // 사번 중복 체크
    if (finalEmployeeId) {
        const existingEmps = await queryTable('user', { filters: { employeeId: finalEmployeeId } });
        if (existingEmps.length > 0) throw new Error('이미 존재하는 사번입니다.');
    }

    await insertRows('user', [{ 
        id: crypto.randomUUID(),
        username: trimmedUsername, 
        role, 
        fullName: fullName?.trim(), 
        employeeId: finalEmployeeId, 
        isActive: 1,
        password: password ? hashPassword(password) : undefined
    }]);

    revalidatePath('/users');
    revalidatePath('/');
    return { success: true };
}

/**
 * 엑셀 데이터를 통해 다수의 사용자를 일괄 등록합니다.
 * @param usersData 사용자 데이터 배열
 */
export async function bulkCreateUsersAction(usersData: any[]) {
    const session = await getSessionAction();
    if (!session || (session.role !== 'ADMIN' && session.role !== 'EDITOR')) {
        throw new Error('접근 권한이 없습니다.');
    }

    let createdCount = 0;
    let skippedCount = 0;
    const skippedItems: any[] = [];

    for (const data of usersData) {
        try {
            const { username, role, fullName, employeeId, password } = data;
            if (!username) {
                skippedCount++;
                skippedItems.push({ username: 'N/A', reason: '아이디 누락' });
                continue;
            }

            const trimmedUsername = String(username).trim();
            const finalEmployeeId = employeeId ? String(employeeId).trim() : null;
            const finalRole = (role && ['ADMIN', 'EDITOR', 'VIEWER'].includes(String(role).toUpperCase())) 
                ? String(role).toUpperCase() 
                : 'VIEWER';
            
            // 아이디 중복 체크
            const existingUsers = await queryTable('user', { filters: { username: trimmedUsername } });
            if (existingUsers.length > 0) {
                skippedCount++;
                skippedItems.push({ username: trimmedUsername, reason: '아이디 중복' });
                continue;
            }

            // 사번 중복 체크
            if (finalEmployeeId) {
                const existingEmps = await queryTable('user', { filters: { employeeId: finalEmployeeId } });
                if (existingEmps.length > 0) {
                    skippedCount++;
                    skippedItems.push({ username: trimmedUsername, reason: '사번 중복' });
                    continue;
                }
            }

            // 비밀번호 설정 (비어있으면 123456)
            const finalPassword = (password && String(password).trim()) ? String(password).trim() : '123456';

            await insertRows('user', [{ 
                id: crypto.randomUUID(),
                username: trimmedUsername, 
                role: finalRole, 
                fullName: fullName ? String(fullName).trim() : null, 
                employeeId: finalEmployeeId, 
                isActive: 1,
                password: hashPassword(finalPassword)
            }]);
            createdCount++;
        } catch (err) {
            console.error('Bulk upload error for item:', data, err);
            skippedCount++;
            skippedItems.push({ username: data.username || 'Unknown', reason: '알 수 없는 오류' });
        }
    }

    revalidatePath('/users');
    revalidatePath('/');
    
    return { 
        success: true, 
        createdCount, 
        skippedCount, 
        skippedItems 
    };
}

export async function deleteUserAction(userId: string) {
    const session = await getSessionAction();
    if (!session || (session.role !== 'ADMIN' && session.role !== 'EDITOR')) {
        throw new Error('접근 권한이 없습니다.');
    }

    // 자기 자신 삭제 방지
    if (session.id === userId) {
        throw new Error('본인의 계정은 삭제할 수 없습니다.');
    }

    // 기본 관리자 계정 삭제 방지
    const targetUsers = await queryTable('user', { filters: { id: userId } });
    const targetUser = targetUsers[0];
    if (targetUser?.username === 'admin_user') {
        throw new Error('기본 관리자 계정은 삭제할 수 없습니다.');
    }

    await deleteRows('user', { filters: { id: userId } });

    revalidatePath('/users');
    revalidatePath('/');
    return { success: true };
}

/**
 * 보고서에 대한 사용자 접근 권한을 업데이트합니다.
 */
export async function updateReportAccessAction(reportId: string, userIds: string[]) {
    const session = await getSessionAction();
    if (!session || (session.role !== 'ADMIN' && session.role !== 'EDITOR')) {
        throw new Error('접근 권한이 없습니다.');
    }

    // 기존 권한 삭제
    await deleteRows('report_access', { filters: { reportId } });
    
    // 신규 권한 삽입
    if (userIds.length > 0) {
        await insertRows('report_access', userIds.map(userId => ({
            reportId,
            userId
        })));
    }

    revalidatePath(`/report/${reportId}`);
    revalidatePath(`/report/${reportId}/input`);
    revalidatePath('/');
    return { success: true };
}

/**
 * 보고서에 접근 권한이 있는 사용자 목록을 가져옵니다.
 */
export async function getAuthorizedUsersForReportAction(reportId: string) {
    const accessList = await queryTable('report_access', { filters: { reportId } });
    const userIds = accessList.map((a: any) => a.userId);
    
    if (userIds.length === 0) return [];
    
    const users = await Promise.all(
        userIds.map(async (id: string) => {
            const results = await queryTable('user', { filters: { id } });
            return results[0];
        })
    );
    
    return users.filter(u => u);
}

/**
 * 삭제된 데이터 행들을 복구합니다.
 */
export async function restoreRowsAction(reportId: string, rowIds: string[]) {
    const user = await getSessionAction();
    if (!user) throw new Error('인증이 필요합니다.');
    const updaterId = user.id;

    const isAuthorized = await checkReportAuthorization(reportId, user.id, user.role);
    if (!isAuthorized) throw new Error('해당 보고서에 대한 접근 권한이 없습니다.');

    for (const rowId of rowIds) {
        const rows = await queryTable('report_row', { filters: { id: rowId } });
        const row = rows[0];
        if (!row) continue;

        // 논리적 삭제 해제
        await updateRows('report_row', {
            isDeleted: 0,
            deletedAt: null,
            updaterId: updaterId,
            updatedAt: new Date().toISOString()
        }, { filters: { id: rowId } });

        // 복구 이력 생성
        await insertRows('report_row_history', [{
            id: crypto.randomUUID(),
            rowId: rowId,
            oldData: row.data,
            newData: JSON.stringify({ ...JSON.parse(row.data), _restored: true }),
            changeType: 'RESTORE',
            changedById: updaterId || 'system',
            changedAt: new Date().toISOString()
        }]);
    }

    revalidatePath(`/report/${reportId}`);
    revalidatePath(`/report/${reportId}/input`);
    return { success: true };
}

/**
 * 핀 고정된 차트 목록을 관리하기 위한 영구 저장소 경로
 */
const PINNED_CHARTS_PATH = path.join(process.cwd(), 'pinned_charts.json');

/**
 * 핀 고정된 차트 설정을 저장합니다.
 */
export async function savePinnedChartAction(chartId: string, config: any) {
    const user = await getSessionAction();
    if (!user) throw new Error('인증이 필요합니다.');

    let pinned: any[] = [];
    try {
        const fileContent = await fs.readFile(PINNED_CHARTS_PATH, 'utf-8');
        pinned = JSON.parse(fileContent);
    } catch (e) {
        // 파일이 없으면 빈 배열로 시작
    }

    // 기존에 있으면 업데이트, 없으면 추가
    const existingIndex = pinned.findIndex(p => p.id === chartId);
    if (existingIndex > -1) {
        pinned[existingIndex] = { ...pinned[existingIndex], config, updatedAt: new Date().toISOString() };
    } else {
        pinned.push({
            id: chartId,
            userId: user.id,
            config,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        });
    }

    await fs.writeFile(PINNED_CHARTS_PATH, JSON.stringify(pinned, null, 2));
    revalidatePath('/dashboard');
    return { success: true };
}

/**
 * 동적 플레이스홀더($TODAY, $TODAY-N 등)를 실제 날짜 값으로 변환합니다.
 */
function resolveDynamicValue(val: any): any {
    if (typeof val !== 'string') return val;
    
    const today = new Date();
    // sv-SE(스웨덴) 로케일은 항상 YYYY-MM-DD 형식을 보장하며, KST 타임존을 명시합니다.
    const kstTodayStr = today.toLocaleDateString('sv-SE', { timeZone: 'Asia/Seoul' });
    
    if (val === '$TODAY') return kstTodayStr;
    
    const match = val.match(/^\$TODAY-(\d+)$/);
    if (match) {
        const days = parseInt(match[1], 10);
        const targetDate = new Date(today);
        targetDate.setDate(today.getDate() - days);
        return targetDate.toLocaleDateString('en-CA', { timeZone: 'Asia/Seoul' });
    }
    
    return val;
}

/**
 * 인자 객체 전체를 순회하며 동적 플레이스홀더를 치환합니다.
 */
function resolveDynamicArgs(args: any): any {
    if (!args || typeof args !== 'object') return args;
    
    const resolvedArgs: any = Array.isArray(args) ? [] : {};
    for (const [key, value] of Object.entries(args)) {
        if (value && typeof value === 'object') {
            resolvedArgs[key] = resolveDynamicArgs(value);
        } else {
            resolvedArgs[key] = resolveDynamicValue(value);
        }
    }
    return resolvedArgs;
}

/**
 * 차트 설명 내의 날짜 정보를 동적으로 변환합니다.
 */
function resolveDynamicDescription(desc: string, args: any): string {
    if (!desc) return desc;
    let resolvedDesc = desc;
    
    // 설명 내에 "$TODAY[-N]" 형태의 플레이스홀더가 있으면 직접 치환
    resolvedDesc = resolvedDesc.replace(/\$TODAY(?:-(\d+))?/g, (match) => {
        return resolveDynamicValue(match);
    });

    // 기존의 YYYY-MM-DD 형태 텍스트 치환 로직 (백업)
    if (args?.startDate && args?.endDate) {
        const sDate = resolveDynamicValue(args.startDate);
        const eDate = resolveDynamicValue(args.endDate);
        
        resolvedDesc = resolvedDesc.replace(/\d{4}-\d{2}-\d{2}/g, (match, offset) => {
            return offset < resolvedDesc.indexOf('부터') ? sDate : eDate;
        });
    }
    
    return resolvedDesc;
}

/**
 * 툴 호출 결과를 차트 데이터 형식으로 변환합니다.
 */
function mapRefreshedData(rawData: any, mapping: any): any[] {
    let newData: any[] = [];
    
    // 1. 결과 객체 내에 배열이 있는 경우 우선 처리 (상세 내역 우선)
    // 'result' 또는 'transactions' 키를 유연하게 지원
    const records = (rawData && rawData.result && Array.isArray(rawData.result)) ? rawData.result :
                  (rawData && rawData.transactions && Array.isArray(rawData.transactions)) ? rawData.transactions : null;

    if (records) {
        newData = records.map((row: any) => {
            if (mapping && typeof mapping === 'object' && !mapping.label && !mapping.value) {
                const mappedRow: any = {};
                for (const [targetKey, sourceKey] of Object.entries(mapping)) {
                    mappedRow[targetKey] = row[sourceKey as string] ?? row[targetKey] ?? '';
                }
                return mappedRow;
            }
            return {
                label: mapping?.label && row[mapping.label] !== undefined ? row[mapping.label] : Object.values(row)[0],
                value: mapping?.value && row[mapping.value] !== undefined ? row[mapping.value] : Object.values(row)[1]
            };
        });
    }
    // 2. 배열 형태의 결과 처리
    else if (Array.isArray(rawData)) {
        newData = rawData.map(row => {
            if (mapping && typeof mapping === 'object' && !mapping.label && !mapping.value) {
                const mappedRow: any = {};
                for (const [targetKey, sourceKey] of Object.entries(mapping)) {
                    mappedRow[targetKey] = row[sourceKey as string] ?? row[targetKey] ?? '';
                }
                return mappedRow;
            }
            return {
                label: mapping?.label && row[mapping.label] !== undefined ? row[mapping.label] : (row.month || row.name || row.label || row.date),
                value: mapping?.value && row[mapping.value] !== undefined ? row[mapping.value] : (row.amount || row.value || row.count || row.total)
            };
        });
    } 
    // 3. 카테고리 요약 형태 처리
    else if (rawData && rawData.categorySummary) {
        newData = Object.entries(rawData.categorySummary).map(([label, value]) => ({ label, value }));
    } 
    
    return newData;
}

/**
 * 핀 고정된 차트 목록을 가져옵니다.
 */
export async function getPinnedChartsAction() {
    const user = await getSessionAction();
    if (!user) return [];

    try {
        const fileContent = await fs.readFile(PINNED_CHARTS_PATH, 'utf-8');
        const pinned = JSON.parse(fileContent);
        const userPinned = pinned.filter((p: any) => p.userId === user.id);

        // 실시간 데이터 동기화 (병렬 처리)
        let hasChanges = false;
        const refreshedCharts = await Promise.all(userPinned.map(async (item: any) => {
            if (item.config.refreshMetadata) {
                try {
                    const { tool, args: originalArgs, mapping } = item.config.refreshMetadata;
                    const args = resolveDynamicArgs(originalArgs);
                    
                    if (item.config.sourceDescription) {
                        item.config.sourceDescription = resolveDynamicDescription(item.config.sourceDescription, originalArgs);
                    }
                    
                    const rawData = await runAITool(tool, args);
                    const newData = mapRefreshedData(rawData, mapping);

                    if (newData.length > 0) {
                        item.config.data = newData;
                        item.refreshedAt = new Date().toISOString();
                        hasChanges = true;
                    }
                } catch (e) {
                    console.error(`[Refresh Error] Chart ${item.id}:`, e);
                }
            }
            return item;
        }));

        // 변경된 내용이 있으면 전체 목록 파일에 영구 저장 (Consistency 보장)
        if (hasChanges) {
            // 원본 목록 중 현재 사용자의 것만 업데이트하여 다시 저장
            const updatedPinned = pinned.map((p: any) => {
                const refreshed = refreshedCharts.find((rc: any) => rc.id === p.id);
                return refreshed || p;
            });
            await fs.writeFile(PINNED_CHARTS_PATH, JSON.stringify(updatedPinned, null, 2));
        }

        return refreshedCharts;
    } catch (e) {
        return [];
    }
}

/**
 * 핀 고정된 차트를 삭제합니다.
 */
export async function deletePinnedChartAction(chartId: string) {
    const user = await getSessionAction();
    if (!user) throw new Error('인증이 필요합니다.');

    try {
        const fileContent = await fs.readFile(PINNED_CHARTS_PATH, 'utf-8');
        let pinned = JSON.parse(fileContent);
        pinned = pinned.filter((p: any) => p.id !== chartId);
        await fs.writeFile(PINNED_CHARTS_PATH, JSON.stringify(pinned, null, 2));
        revalidatePath('/dashboard');
        return { success: true };
    } catch (e) {
        return { success: false };
    }
}

/**
 * 특정 차트의 데이터를 즉시 새로고침합니다.
 */
export async function refreshIndividualChartAction(chartId: string) {
    const user = await getSessionAction();
    if (!user) throw new Error('인증이 필요합니다.');

    try {
        const fileContent = await fs.readFile(PINNED_CHARTS_PATH, 'utf-8');
        let pinned = JSON.parse(fileContent);
        const chartIndex = pinned.findIndex((p: any) => p.id === chartId);
        if (chartIndex === -1) throw new Error('차트를 찾을 수 없습니다.');

        const item = pinned[chartIndex];
        if (!item.config.refreshMetadata) return { success: true, item };

        const { tool, args: originalArgs, mapping } = item.config.refreshMetadata;
        
        // 동적 인자 처리
        const args = resolveDynamicArgs(originalArgs);
        
        // 설명 정보 업데이트
        if (item.config.sourceDescription) {
            item.config.sourceDescription = resolveDynamicDescription(item.config.sourceDescription, originalArgs);
        }

        const rawData = await runAITool(tool, args);
        const newData = mapRefreshedData(rawData, mapping);

        if (newData.length > 0) {
            item.config.data = newData;
            item.refreshedAt = new Date().toISOString();
            pinned[chartIndex] = item;
            await fs.writeFile(PINNED_CHARTS_PATH, JSON.stringify(pinned, null, 2));
        }

        revalidatePath('/dashboard');
        return { success: true, item };
    } catch (e) {
        console.error('Refresh Action Error:', e);
        return { success: false };
    }
}

/**
 * 차트의 레이아웃(너비 등) 설정을 업데이트합니다.
 */
export async function updateChartLayoutAction(chartId: string, layout: any) {
    const user = await getSessionAction();
    if (!user) throw new Error('인증이 필요합니다.');

    try {
        const fileContent = await fs.readFile(PINNED_CHARTS_PATH, 'utf-8');
        let pinned = JSON.parse(fileContent);
        const chartIndex = pinned.findIndex((p: any) => p.id === chartId);
        if (chartIndex === -1) throw new Error('차트를 찾을 수 없습니다.');

        pinned[chartIndex].layout = layout;
        pinned[chartIndex].updatedAt = new Date().toISOString();

        await fs.writeFile(PINNED_CHARTS_PATH, JSON.stringify(pinned, null, 2));
        revalidatePath('/dashboard');
        return { success: true };
    } catch (e) {
        console.error('Update Layout Action Error:', e);
        return { success: false };
    }
}

// AI 분석 스튜디오 세션 테이블 초기화 여부를 서버 메모리에 캐싱
let isAIStudioSessionTableInitialized = false;

/**
 * AI 분석 스튜디오의 세션 상태를 서버에 저장합니다.
 */
export async function saveAIStudioSessionAction(data: any) {
    const user = await getSessionAction();
    if (!user) throw new Error('인증이 필요합니다.');

    const tableName = 'ai_studio_session';
    
    try {
        const sessionData = {
            userId: user.id,
            data: JSON.stringify(data),
            updatedAt: new Date().toISOString()
        };

        // 1. 초기 1회 또는 오류 발생 시 테이블 생성 시도 (Lazy Creation)
        if (!isAIStudioSessionTableInitialized) {
            try {
                await queryTable(tableName, { limit: 1 });
                isAIStudioSessionTableInitialized = true;
            } catch (e) {
                // 테이블이 없으면 생성
                await createTable('AI Studio Session', [
                    { name: 'userId', type: 'TEXT', notNull: true },
                    { name: 'data', type: 'TEXT', notNull: true },
                    { name: 'updatedAt', type: 'TEXT', notNull: true }
                ], { tableName, uniqueKeyColumns: ['userId'] });
                isAIStudioSessionTableInitialized = true;
            }
        }

        // 2. Upsert (userId 기준)
        const existing = await queryTable(tableName, { filters: { userId: user.id } });
        
        if (existing && existing.length > 0) {
            await updateRows(tableName, {
                data: sessionData.data,
                updatedAt: sessionData.updatedAt
            }, { filters: { userId: user.id } });
        } else {
            await insertRows(tableName, [sessionData]);
        }

        return { success: true };
    } catch (e) {
        console.error('Save AI Studio Session Error:', e);
        // 오류 발생 시 다음 재시도에서 테이블 체크를 다시 하도록 플래그 리셋
        isAIStudioSessionTableInitialized = false;
        return { success: false };
    }
}

/**
 * 서버에서 AI 분석 스튜디오의 세션 상태를 불러옵니다.
 */
export async function getAIStudioSessionAction() {
    const user = await getSessionAction();
    if (!user) return null;

    const tableName = 'ai_studio_session';
    
    try {
        const results = await queryTable(tableName, { filters: { userId: user.id } });
        if (results && results.length > 0) {
            return JSON.parse(results[0].data);
        }
    } catch (e) {
        // 테이블이 없거나 데이터가 없는 경우 무시 (새로운 분석을 위해 null 반환)
    }
    return null;
}

/**
 * 서버의 AI 분석 스튜디오 세션 상태를 초기화합니다.
 */
export async function clearAIStudioSessionAction() {
    const user = await getSessionAction();
    if (!user) return { success: false };

    const tableName = 'ai_studio_session';
    
    try {
        await deleteRows(tableName, { filters: { userId: user.id } });
        return { success: true };
    } catch (e) {
        return { success: false };
    }
}
