'use server';

import { revalidatePath } from 'next/cache';
import { redirect } from 'next/navigation';
import { cookies } from 'next/headers';
import prisma from '@/lib/prisma';
import { parseExcelWorkbook } from '@/lib/excel-parser';
import { analyzeExcelImage, extractDataFromImage, recommendSchemaFromSample } from '@/lib/ai-vision';
import crypto from 'crypto';
import fs from 'fs/promises';
import path from 'path';
import { notifyNewDataRow, notifyBulkUpload } from '@/lib/notifications';

// Password Security Utilities
const SALT_SIZE = 16;
const KEY_LEN = 64;

function hashPassword(password: string): string {
    const salt = crypto.randomBytes(SALT_SIZE).toString('hex');
    const derivedKey = crypto.scryptSync(password, salt, KEY_LEN);
    return `${salt}:${derivedKey.toString('hex')}`;
}

function verifyPassword(password: string, storedHash: string): boolean {
    if (!storedHash) return false;
    const parts = storedHash.split(':');
    if (parts.length !== 2) return false;
    const [salt, hash] = parts;
    const derivedKey = crypto.scryptSync(password, salt, KEY_LEN);
    return derivedKey.toString('hex') === hash;
}

/**
 * 보고서에 대한 사용자의 접근 권한을 확인합니다.
 * ADMIN, EDITOR는 모든 권한을 가지며, VIEWER는 명시적으로 권한이 부여되었거나 소유자인 경우에만 허용합니다.
 */
async function checkReportAuthorization(reportId: string, userId: string, role: string) {
    if (role === 'ADMIN' || role === 'EDITOR') return true;
    
    const report = await prisma.report.findUnique({
        where: { id: reportId },
        select: { 
            ownerId: true,
            authorizedUsers: { where: { id: userId }, select: { id: true } }
        }
    });
    
    if (!report) return false;
    if (report.ownerId === userId) return true;
    if (report.authorizedUsers.length > 0) return true;
    
    return false;
}

export async function uploadFileAction(formData: FormData) {
    const file = formData.get('file') as File;
    if (!file) throw new Error('파일이 없습니다.');

    const bytes = await file.arrayBuffer();
    const buffer = Buffer.from(bytes);

    const uploadDir = path.join(process.cwd(), 'public', 'uploads');
    try {
        await fs.access(uploadDir);
    } catch {
        await fs.mkdir(uploadDir, { recursive: true });
    }

    const uniqueName = `${Date.now()}-${file.name.replace(/\s+/g, '_')}`;
    const filePath = path.join(uploadDir, uniqueName);
    await fs.writeFile(filePath, buffer);

    return { url: `/uploads/${uniqueName}`, name: file.name };
}

export async function getSchemaRecommendationAction(reportId: string) {
    const report = await prisma.report.findUnique({ where: { id: reportId } });
    if (!report) throw new Error('보고서를 찾을 수 없습니다.');

    const currentColumns = JSON.parse(report.columns);
    const sampleRows = await prisma.reportRow.findMany({
        where: { reportId },
        take: 20
    });

    const rowsData = sampleRows.map(r => JSON.parse(r.data));
    const recommendation = await recommendSchemaFromSample(currentColumns, rowsData);
    
    return recommendation.columns;
}

/**
 * 데이터 행의 중복 여부를 판단하기 위한 해시값을 생성합니다.
 * @param rowData 객체 형태의 행 데이터
 * @param columns 컬럼 정의 배열
 */
export async function generateContentHash(rowData: any, columns: any[]) {
    // 자동 생성 필드(데이터 ID 등)는 중복 체크에서 제외
    // 사용자가 'isUnique'로 설정한 필드가 있다면 해당 필드들만 조합, 없으면 모든 일반 필드 조합
    const uniqueCols = columns.filter(c => c.isUnique);
    const targetCols = uniqueCols.length > 0 ? uniqueCols : columns.filter(c => !c.isAutoGenerated);
    
    const sortedKeys = targetCols.map(c => c.name).sort();
    const hashSource = sortedKeys.map(key => `${key}:${rowData[key] ?? ''}`).join('|');
    
    return crypto.createHash('sha256').update(hashSource).digest('hex');
}

export async function uploadExcelAction(formData: FormData, userId: string) {
  const user = await getSessionAction();
  if (!user) throw new Error('인증이 필요합니다.');

  const file = formData.get('file') as File;
  const configsJson = formData.get('configsJson') as string;
  if (!file) throw new Error('파일이 없습니다.');

  const buffer = Buffer.from(await file.arrayBuffer());
  const configs = configsJson ? JSON.parse(configsJson) : [];
  
  // Use the advanced parser with user-defined configs (header row index, selected fields)
  const sheetResults = parseExcelWorkbook(buffer, configs);

  // Store each sheet/table as a separate report
  for (const sheet of sheetResults) {
    for (const table of sheet.tables) {
      if (table.columns.length === 0) continue; // Skip if no columns selected

      const newReport = await prisma.report.create({
        data: {
          name: table.name,
          sheetName: sheet.sheetName,
          columns: JSON.stringify(table.columns),
          ownerId: userId,
          rows: {
            create: table.rows.map(row => ({
              data: JSON.stringify(row)
            }))
          }
        }
      });

      // 슬랙 알림 발송 - 신규 보고서 생성 및 초기 데이터 알림
      if (table.rows.length > 0) {
        notifyBulkUpload(table.name, user.fullName || user.username, table.rows.length, table.rows[0], table.columns, null).catch(console.error);
      }
    }
  }

  revalidatePath('/');
}

export async function addRowAction(reportId: string, rowData: any) {
  // 4. 세션 사용자 확인 및 권한 체크
  const user = await getSessionAction();
  if (!user) throw new Error('인증이 필요합니다.');
  
  const isAuthorized = await checkReportAuthorization(reportId, user.id, user.role);
  if (!isAuthorized) throw new Error('해당 보고서에 대한 접근 권한이 없습니다.');

  const report = await prisma.report.findUnique({ where: { id: reportId } });
  if (!report) throw new Error('보고서를 찾을 수 없습니다.');

  const columns = JSON.parse(report.columns);
  
  // 1. 중복 체크
  const hash = await generateContentHash(rowData, columns);
  const existing = await prisma.reportRow.findFirst({
      where: { reportId, contentHash: hash, isDeleted: false } as any
  });
  
  if (existing) {
      throw new Error('이미 동일한 내용의 데이터가 존재합니다. (중복 방지)');
  }

  // 2. DID-일련번호 자동 키 생성
  const rowCount = await prisma.reportRow.count({ where: { reportId } });
  const nextSerial = (rowCount + 1).toString().padStart(6, '0');
  
  const finalData = { ...rowData };
  columns.forEach((col: any) => {
    if (col.isAutoGenerated) {
        finalData[col.name] = `DID-${nextSerial}`;
    }
  });

  // 3. Server-side Validation
  for (const col of columns) {
    if (col.isAutoGenerated) continue;
    const val = finalData[col.name];

    if (col.isRequired && (val === undefined || val === null || val === '')) {
        throw new Error(`'${col.name}' 필드는 필수입니다.`);
    }

    if ((col.type === 'number' || col.type === 'currency') && val !== '' && val !== null && val !== undefined) {
        const sVal = String(val);
        const cleanVal = sVal.replace(/[^0-9.-]/g, '').trim();
        if (isNaN(Number(cleanVal))) {
            throw new Error('필드 ' + col.name + '에는 숫자만 입력 가능합니다.');
        }
        finalData[col.name] = Number(cleanVal);
    }
  }

  const creatorId = user.id;

  // 5. 저장
  await prisma.reportRow.create({
      data: {
        reportId,
        data: JSON.stringify(finalData),
        contentHash: hash,
        creatorId: creatorId
      } as any
    });
    
  // 슬랙 알림 발송 - 비동기로 처리하여 사용자 응답 속도에 영향을 주지 않음
  notifyNewDataRow(report.name, user.fullName || user.username, finalData, columns, report.slackWebhookUrl).catch(console.error);

  revalidatePath(`/report/${reportId}`);
  return { success: true };
}

/**
 * 특정 행의 상세 감사 정보(생성/수정/이력)를 조회합니다.
 */
export async function getRowHistoryAction(rowId: string) {
    const row = await prisma.reportRow.findUnique({
        where: { id: rowId },
        include: {
            creator: { select: { id: true, username: true, fullName: true } },
            updater: { select: { id: true, username: true, fullName: true } },
            histories: {
                orderBy: { changedAt: 'desc' },
                include: {
                    // changedBy relation might not exist in schema, checking...
                }
            }
        }
    });

    if (!row) throw new Error('데이터를 찾을 수 없습니다.');

    // 히스토리 작성자 정보를 위해 모든 history에 대해 사용자 정보 추가 조회
    const historyWithUsers = await Promise.all(
        row.histories.map(async (h) => {
            const user = await prisma.user.findUnique({
                where: { id: h.changedById },
                select: { id: true, username: true, fullName: true }
            });
            return { ...h, changedBy: user };
        })
    );

    return {
        id: row.id,
        createdAt: row.createdAt,
        updatedAt: row.updatedAt,
        creator: row.creator,
        updater: row.updater,
        histories: historyWithUsers
    };
}

export async function deleteReportAction(reportId: string) {
    await prisma.report.update({
        where: { id: reportId },
        data: { 
            isDeleted: true,
            deletedAt: new Date()
        } as any
    });
    revalidatePath('/');
    revalidatePath('/archive');
}

export async function restoreReportAction(reportId: string) {
    await prisma.report.update({
        where: { id: reportId },
        data: { 
            isDeleted: false,
            deletedAt: null
        } as any
    });
    revalidatePath('/');
    revalidatePath('/archive');
}

export async function permanentDeleteReportAction(reportId: string) {
    // 1. 데이터(행) 먼저 삭제
    await prisma.reportRow.deleteMany({ where: { reportId } });
    // 2. 보고서 본체 삭제
    await prisma.report.delete({ where: { id: reportId } });
    
    revalidatePath('/');
    revalidatePath('/archive');
}

export async function deleteRowsAction(reportId: string, rowIds: string[]) {
    const user = await getSessionAction();
    if (!user) throw new Error('인증이 필요합니다.');
    const updaterId = user.id;

    const isAuthorized = await checkReportAuthorization(reportId, user.id, user.role);
    if (!isAuthorized) throw new Error('해당 보고서에 대한 접근 권한이 없습니다.');

    const rows = await prisma.reportRow.findMany({
        where: { id: { in: rowIds } }
    });

    // 일반 사용자(VIEWER) 권한 일 때 타인의 데이터 삭제 시도 차단
    if (user.role === 'VIEWER') {
        const hasUnauthorized = rows.some(r => r.creatorId !== user.id);
        if (hasUnauthorized) {
            throw new Error('본인이 작성하지 않은 데이터는 삭제할 수 없습니다.');
        }
    }

    // 2. 논리적 삭제 및 이력 생성 (트랜잭션 권장하나 여기서는 순차 처리)
    for (const row of rows) {
        await prisma.reportRow.update({
            where: { id: row.id },
            data: {
                isDeleted: true,
                deletedAt: new Date(),
                updaterId: updaterId
            } as any
        });

        await prisma.reportRowHistory.create({
            data: {
                rowId: row.id,
                oldData: row.data,
                newData: JSON.stringify({ ...JSON.parse(row.data), _deleted: true }),
                changeType: 'DELETE',
                changedById: updaterId || 'system'
            }
        });
    }

    revalidatePath(`/report/${reportId}`);
    revalidatePath('/archive');
}

export async function bulkUpdateRowsAction(
    reportId: string, 
    rowIds: string[], 
    fieldName: string, 
    actionType: 'OVERWRITE' | 'FIND_REPLACE', 
    params: { value?: any; find?: string; replace?: string }
) {
    const user = await getSessionAction();
    if (!user) throw new Error('인증이 필요합니다.');
    
    const isAuthorized = await checkReportAuthorization(reportId, user.id, user.role);
    if (!isAuthorized) throw new Error('해당 보고서에 대한 접근 권한이 없습니다.');

    const report = await prisma.report.findUnique({ where: { id: reportId } });
    if (!report) throw new Error('보고서를 찾을 수 없습니다.');

    const columns = JSON.parse(report.columns);
    const colDef = columns.find((c: any) => c.name === fieldName);
    if (!colDef) throw new Error('컬럼 정의를 찾을 수 없습니다.');

    // 1. 대상 행 로드
    const rows = await prisma.reportRow.findMany({
        where: { id: { in: rowIds }, reportId }
    });

    if (rows.length === 0) throw new Error('수정할 데이터가 없습니다.');

    const updaterId = user.id;

    // 일반 사용자(VIEWER) 권한 일 때 타인의 데이터 수정 시도 차단
    if (user.role === 'VIEWER') {
        const hasUnauthorized = rows.some(r => r.creatorId !== user.id);
        if (hasUnauthorized) {
            throw new Error('본인이 작성하지 않은 데이터는 일괄 수정할 수 없습니다.');
        }
    }

    // 2. 일괄 업데이트 처리
    for (const row of rows) {
        const oldData = row.data;
        const rowData = JSON.parse(row.data);
        let newValue = params.value;

        if (actionType === 'FIND_REPLACE') {
            const currentVal = String(rowData[fieldName] || '');
            newValue = currentVal.replace(new RegExp(params.find || '', 'g'), params.replace || '');
            
            // 타입 복원 (숫자/통화인 경우)
            if (colDef.type === 'number' || colDef.type === 'currency') {
                const cleanVal = newValue.replace(/[^0-9.-]/g, '').trim();
                newValue = isNaN(Number(cleanVal)) ? newValue : Number(cleanVal);
            }
        }

        // 유효성 검사 (Overwrite인 경우에도 적용)
        if (colDef.type === 'number' || colDef.type === 'currency') {
            const sVal = String(newValue);
            const cleanVal = sVal.replace(/[^0-9.-]/g, '').trim();
            if (isNaN(Number(cleanVal))) {
                throw new Error(`${fieldName} 필드에는 숫자만 입력 가능합니다.`);
            }
            newValue = Number(cleanVal);
        }

        rowData[fieldName] = newValue;

        // 중복 체크용 해시 재생성
        const newHash = await generateContentHash(rowData, columns);
        
        // 3. 개별 업데이트 및 이력 생성
        const updatedRow = await prisma.reportRow.update({
            where: { id: row.id },
            data: {
                data: JSON.stringify(rowData),
                contentHash: newHash,
                updaterId: updaterId,
                updatedAt: new Date()
            } as any
        });

        await prisma.reportRowHistory.create({
            data: {
                rowId: row.id,
                oldData: oldData,
                newData: updatedRow.data,
                changeType: 'UPDATE',
                changedById: updaterId || 'system'
            }
        });
    }

    revalidatePath(`/report/${reportId}`);
    return { success: true, count: rows.length };
}


export async function updateSingleRowAction(
    reportId: string, 
    rowId: string, 
    newData: any
) {
    const user = await getSessionAction();
    if (!user) throw new Error('인증이 필요합니다.');
    
    const isAuthorized = await checkReportAuthorization(reportId, user.id, user.role);
    if (!isAuthorized) throw new Error('해당 보고서에 대한 접근 권한이 없습니다.');

    const report = await prisma.report.findUnique({ where: { id: reportId } });
    if (!report) throw new Error('보고서를 찾을 수 없습니다.');

    const columns = JSON.parse(report.columns);
    
    // 1. 중복 체크용 해시 생성
    const hash = await generateContentHash(newData, columns);
    const existing = await prisma.reportRow.findFirst({
        where: { 
            reportId, 
            contentHash: hash,
            id: { not: rowId } // 자신은 제외
        } as any
    });
    
    if (existing) {
        throw new Error('이미 동일한 내용의 데이터가 존재합니다. (중복 방지)');
    }

    // 2. 유효성 검사
    const finalData = { ...newData };
    for (const col of columns) {
        if (col.isAutoGenerated) continue;
        const val = finalData[col.name];

        if (col.isRequired && (val === undefined || val === null || val === '')) {
            throw new Error(`'${col.name}' 필드는 필수입니다.`);
        }

        if ((col.type === 'number' || col.type === 'currency') && val !== '' && val !== null && val !== undefined) {
            const sVal = String(val);
            const cleanVal = sVal.replace(/[^0-9.-]/g, '').trim();
            if (isNaN(Number(cleanVal))) {
                throw new Error(`${col.name} 필드에는 숫자만 입력 가능합니다.`);
            }
            finalData[col.name] = Number(cleanVal);
        }
    }

    // 3. 업데이트 및 이력 생성
    const updaterId = user.id;
    const oldRow = await prisma.reportRow.findUnique({ where: { id: rowId } });
    
    if (!oldRow) throw new Error('기존 데이터를 찾을 수 없습니다.');

    // 일반 사용자(VIEWER) 권한 일 때 타인의 데이터 수정 시도 차단
    if (user.role === 'VIEWER' && oldRow.creatorId !== user.id) {
        throw new Error('본인이 작성하지 않은 데이터는 수정할 수 없습니다.');
    }

    const updatedRow = await prisma.reportRow.update({
        where: { id: rowId },
        data: {
            data: JSON.stringify(finalData),
            contentHash: hash,
            updaterId: updaterId,
            updatedAt: new Date()
        } as any
    });

    if (oldRow) {
        await prisma.reportRowHistory.create({
            data: {
                rowId: rowId,
                oldData: oldRow.data,
                newData: updatedRow.data,
                changeType: 'UPDATE',
                changedById: updaterId || 'system'
            }
        });
    }

    revalidatePath(`/report/${reportId}`);
    return { success: true };
}

export async function renameReportAction(reportId: string, newName: string) {
    await prisma.report.update({
        where: { id: reportId },
        data: { name: newName }
    });
    revalidatePath(`/report/${reportId}`);
    revalidatePath('/');
}

export async function updateReportWebhookAction(reportId: string, webhookUrl: string | null) {
    const user = await getSessionAction();
    if (!user) throw new Error('인증이 필요합니다.');

    const isAuthorized = await checkReportAuthorization(reportId, user.id, user.role);
    if (!isAuthorized) throw new Error('해당 보고서에 대한 접근 권한이 없습니다.');

    await prisma.report.update({
        where: { id: reportId },
        data: { slackWebhookUrl: webhookUrl }
    });
    
    revalidatePath(`/report/${reportId}`);
    return { success: true };
}

export async function updateReportSchemaAction(reportId: string, columns: any[]) {
    await prisma.report.update({
        where: { id: reportId },
        data: { columns: JSON.stringify(columns) }
    });
    revalidatePath(`/report/${reportId}`);
}

export async function analyzeExcelScreenshotAction(formData: FormData) {
  const image = formData.get('image') as File;
  if (!image) throw new Error('이미지 파일이 없습니다.');

  const arrayBuffer = await image.arrayBuffer();
  const buffer = Buffer.from(arrayBuffer);
  const base64 = buffer.toString('base64');
  const mimeType = image.type;

  return await analyzeExcelImage(base64, mimeType);
}

export async function addRowsAction(reportId: string, rows: any[]) {
    const user = await getSessionAction();
    if (!user) throw new Error('인증이 필요합니다.');

    const isAuthorized = await checkReportAuthorization(reportId, user.id, user.role);
    if (!isAuthorized) throw new Error('해당 보고서에 대한 접근 권한이 없습니다.');

    const creatorId = user.id;

    const report = await prisma.report.findUnique({ where: { id: reportId } });
    if (!report) throw new Error('보고서를 찾을 수 없습니다.');
  
    const columns = JSON.parse(report.columns);
    const initialRowCount = await prisma.reportRow.count({ where: { reportId } });
    let skippedCount = 0;
    
    // 1. 기존 데이터의 해시값 로드 (중복 체크용) - 삭제되지 않은 행만 대상
    const existingRows = await prisma.reportRow.findMany({
        where: { reportId, contentHash: { not: null }, isDeleted: false } as any,
        select: { contentHash: true } as any
    });
    const existingHashes = new Set(existingRows.map(function(r: any) { return r.contentHash; }));

    // 2. 각 행당 유효성 검사 및 정제
    const cleanedRowsToInsert = [];
    
    for (const rowData of rows) {
        const finalData: any = {};
        
        // 매핑
        columns.forEach((col: any) => {
            if (!col.isAutoGenerated) {
                finalData[col.name] = rowData[col.name];
            }
        });

        // 중복 체크용 해시 생성
        const hash = await generateContentHash(finalData, columns);
        
        if (existingHashes.has(hash)) {
            skippedCount++;
            continue; 
        }

        // 유효성 검사 및 정제
        for (const col of columns) {
            if (col.isAutoGenerated) continue;
            const val = finalData[col.name];

            if (col.isRequired && (val === undefined || val === null || val === '')) {
                if (val !== 0) throw new Error('필드 ' + col.name + '에 값이 누락되었습니다.');
            }

            if ((col.type === 'number' || col.type === 'currency') && val !== '' && val !== null && val !== undefined) {
                const sVal = String(val);
                const cleanVal = sVal.replace(/[^0-9.-]/g, '').trim();
                const numericVal = Number(cleanVal);
                if (!isNaN(numericVal)) {
                    finalData[col.name] = numericVal;
                }
            }
        }

        // 인서트 데이터 구성
        const nextSerial = (initialRowCount + cleanedRowsToInsert.length + 1).toString().padStart(6, '0');
        const rowWithMetadata: any = { ...finalData };
        
        columns.forEach((col: any) => {
            if (col.isAutoGenerated) {
                rowWithMetadata[col.name] = 'DID-' + nextSerial;
            }
        });

        cleanedRowsToInsert.push({
            data: JSON.stringify(rowWithMetadata),
            contentHash: hash,
            reportId: reportId,
            creatorId: creatorId
        });
        
        existingHashes.add(hash);
    }
  
    if (cleanedRowsToInsert.length > 0) {
        await prisma.reportRow.createMany({
            data: cleanedRowsToInsert as any
        });
    }
  
    if (cleanedRowsToInsert.length > 0) {
        // 슬랙 알림 발송 - 첫 번째 행을 대표 데이터로 사용
        const firstRowData = JSON.parse(cleanedRowsToInsert[0].data);
        notifyBulkUpload(report.name, user.fullName || user.username, cleanedRowsToInsert.length, firstRowData, columns, report.slackWebhookUrl).catch(console.error);
    }

    revalidatePath('/report/' + reportId);
    return { 
        success: true, 
        addedCount: cleanedRowsToInsert.length, 
        skippedCount 
    };
}

export async function createManualReportAction(name: string, sheetName: string, columns: any[]) {
    // 1. 유저 확인
    let user = await prisma.user.findUnique({ where: { username: 'admin_user' } });
    if (!user) {
        user = await prisma.user.create({
            data: { username: 'admin_user', role: 'ADMIN' }
        });
    }

    // 2. 컬럼 준비 (Data ID 가 없으면 첫 번째로 자동 추가)
    // 엑셀 업로드와 동일하게 isAutoGenerated: true 인 컬럼을 DID-XXXXXX 용으로 사용합니다.
    const hasAutoId = columns.some(c => c.isAutoGenerated);
    let finalColumns = [...columns];
    if (!hasAutoId) {
        finalColumns = [
            { id: 'did', name: '데이터 ID', type: 'string', isRequired: true, isAutoGenerated: true },
            ...columns
        ];
    }

    // 3. 보고서 생성
    const report = await prisma.report.create({
        data: {
            name,
            sheetName,
            columns: JSON.stringify(finalColumns),
            ownerId: user.id
        }
    });

    revalidatePath('/');
    redirect(`/report/${report.id}?action=new`);
}

export async function analyzeImageAndExtractDataAction(formData: FormData, columnsJson: string) {
    try {
        const image = formData.get('image') as File;
        if (!image) throw new Error('이미지 파일이 없습니다.');
        
        console.log(`Analyzing image: ${image.name}, size: ${Math.round(image.size / 1024)} KB, type: ${image.type}`);

        const columns = JSON.parse(columnsJson);
        const arrayBuffer = await image.arrayBuffer();
        const buffer = Buffer.from(arrayBuffer);
        const base64 = buffer.toString('base64');
        const mimeType = image.type;

        const extractedData = await extractDataFromImage(base64, mimeType, columns);
        return { success: true, data: extractedData };
    } catch (error: any) {
        console.error("AI Analysis Action Error:", error);
        // 에러 메시지를 가공하여 사용자에게 친숙하게 전달
        let errorMessage = error.message || '이미지를 분석하는 중 오류가 발생했습니다.';
        if (errorMessage.includes('413')) {
            errorMessage = '이미지 용량이 너무 큽니다. 더 작은 이미지를 사용해 주세요.';
        }
        return { success: false, error: errorMessage };
    }
}


export async function loginAction(username: string, password?: string) {
    const trimmedUsername = username.trim();

    // Check if admin_user exists, create if not
    const existingAdmin = await prisma.user.findUnique({ where: { username: 'admin_user' } });
    if (!existingAdmin) {
        await prisma.user.create({
            data: { 
                username: 'admin_user', 
                role: 'ADMIN', 
                fullName: '초기 관리자', 
                isActive: true,
                password: hashPassword('admin123!') // 기본 비밀번호 설정
            }
        });
    } else if (!existingAdmin.isActive && trimmedUsername === 'admin_user') {
        // Emergency reactivate admin_user if it's the target login and is deactivated
        await prisma.user.update({
            where: { username: 'admin_user' },
            data: { isActive: true }
        });
    }

    const user = await prisma.user.findUnique({ where: { username: trimmedUsername } });
    
    if (!user || !user.isActive) {
        throw new Error('존재하지 않거나 비활성화된 계정입니다.');
    }

    // 비밀번호 검증 (이미 설정된 비밀번호가 있는 경우)
    if (user.password && password) {
        const isValid = verifyPassword(password, user.password);
        if (!isValid) {
            throw new Error('비밀번호가 일치하지 않습니다.');
        }
    } else if (user.password && !password) {
        throw new Error('비밀번호를 입력해 주세요.');
    }
    // 레거시 대응: 비밀번호가 없는 계정은 아이디만으로 로그인 허용 가능하나 보안상 권장 안 함.
    // 여기서는 비밀번호가 있는 경우만 검증하도록 함.

    const cookieStore = await cookies();
    cookieStore.set('session_user_id', user.id, {
        httpOnly: true,
        secure: process.env.NODE_ENV === 'production',
        sameSite: 'lax',
        maxAge: 60 * 60 * 24 * 7, // 1 week
        path: '/'
    });

    return { success: true, user };
}

export async function logoutAction() {
    const cookieStore = await cookies();
    cookieStore.delete('session_user_id');
    return { success: true };
}

export async function getSessionAction() {
    const cookieStore = await cookies();
    const userId = cookieStore.get('session_user_id')?.value;
    
    if (!userId) return null;

    const user = await prisma.user.findUnique({ 
        where: { id: userId },
        select: { id: true, username: true, role: true, fullName: true, isActive: true }
    });

    if (!user || !user.isActive) {
        return null;
    }

    return user;
}


export async function getUsersAction() {
    const session = await getSessionAction();
    if (!session || (session.role !== 'ADMIN' && session.role !== 'EDITOR')) {
        throw new Error('접근 권한이 없습니다.');
    }

    const users = await prisma.user.findMany({
        select: { 
            id: true, 
            username: true, 
            role: true, 
            fullName: true, 
            employeeId: true, 
            isActive: true, 
            lastLoginAt: true,
            password: true
        },
        orderBy: { username: 'asc' }
    });

    return users.map(user => ({
        ...user,
        hasPassword: !!user.password,
        password: undefined
    }));
}

export async function updateUserAction(userId: string, data: any) {
    const session = await getSessionAction();
    if (!session || (session.role !== 'ADMIN' && session.role !== 'EDITOR')) {
        throw new Error('접근 권한이 없습니다.');
    }

    // admin_user 본인의 역할이나 활성화 상태 변경은 제한 (안전장치)
    const targetUser = await prisma.user.findUnique({ where: { id: userId } });
    if (targetUser?.username === 'admin_user') {
        if (data.role !== 'ADMIN' || data.isActive === false) {
            throw new Error('기본 관리자 계정의 권한이나 활성 상태는 변경할 수 없습니다.');
        }
    }

    const { username, role, fullName, employeeId, isActive, password } = data;
    const finalEmployeeId = employeeId?.trim() || null;

    // 아이디 중복 체크 (수정 시 본인 제외)
    if (username) {
        const trimmedUsername = username.trim();
        const existingUsername = await prisma.user.findUnique({ where: { username: trimmedUsername } });
        if (existingUsername && existingUsername.id !== userId) {
            throw new Error('이미 사용 중인 아이디입니다.');
        }
    }

    // 사번 중복 체크 (수정 시 본인 제외)
    if (finalEmployeeId) {
        const existingEmp = await prisma.user.findUnique({ where: { employeeId: finalEmployeeId } });
        if (existingEmp && existingEmp.id !== userId) {
            throw new Error('이미 다른 사용자가 사용 중인 사번입니다.');
        }
    }
    
    await prisma.user.update({
        where: { id: userId },
        data: { 
            username: username?.trim(), 
            role, 
            fullName: fullName?.trim(), 
            employeeId: finalEmployeeId, 
            isActive: isActive === undefined ? true : isActive,
            ...(password ? { password: hashPassword(password) } : {})
        }
    });

    revalidatePath('/users');
    revalidatePath('/');
    return { success: true };
}

export async function createUserAction(data: any) {
    const session = await getSessionAction();
    if (!session || (session.role !== 'ADMIN' && session.role !== 'EDITOR')) {
        throw new Error('접근 권한이 없습니다.');
    }

    const { username, role, fullName, employeeId, password } = data;
    const trimmedUsername = username.trim();
    const finalEmployeeId = employeeId?.trim() || null;
    
    // 아이디 중복 체크
    const existing = await prisma.user.findUnique({ where: { username: trimmedUsername } });
    if (existing) throw new Error('이미 존재하는 아이디입니다.');

    // 사번 중복 체크
    if (finalEmployeeId) {
        const existingEmp = await prisma.user.findUnique({ where: { employeeId: finalEmployeeId } });
        if (existingEmp) throw new Error('이미 존재하는 사번입니다.');
    }

    await prisma.user.create({
        data: { 
            username: trimmedUsername, 
            role, 
            fullName: fullName?.trim(), 
            employeeId: finalEmployeeId, 
            isActive: true,
            password: password ? hashPassword(password) : undefined
        }
    });

    revalidatePath('/users');
    revalidatePath('/');
    return { success: true };
}

/**
 * 엑셀 데이터를 통해 다수의 사용자를 일괄 등록합니다.
 * @param usersData 사용자 데이터 배열
 */
export async function bulkCreateUsersAction(usersData: any[]) {
    const session = await getSessionAction();
    if (!session || (session.role !== 'ADMIN' && session.role !== 'EDITOR')) {
        throw new Error('접근 권한이 없습니다.');
    }

    let createdCount = 0;
    let skippedCount = 0;
    const skippedItems: any[] = [];

    for (const data of usersData) {
        try {
            const { username, role, fullName, employeeId, password } = data;
            if (!username) {
                skippedCount++;
                skippedItems.push({ username: 'N/A', reason: '아이디 누락' });
                continue;
            }

            const trimmedUsername = String(username).trim();
            const finalEmployeeId = employeeId ? String(employeeId).trim() : null;
            const finalRole = (role && ['ADMIN', 'EDITOR', 'VIEWER'].includes(String(role).toUpperCase())) 
                ? String(role).toUpperCase() 
                : 'VIEWER';
            
            // 아이디 중복 체크
            const existing = await prisma.user.findUnique({ where: { username: trimmedUsername } });
            if (existing) {
                skippedCount++;
                skippedItems.push({ username: trimmedUsername, reason: '아이디 중복' });
                continue;
            }

            // 사번 중복 체크
            if (finalEmployeeId) {
                const existingEmp = await prisma.user.findUnique({ where: { employeeId: finalEmployeeId } });
                if (existingEmp) {
                    skippedCount++;
                    skippedItems.push({ username: trimmedUsername, reason: '사번 중복' });
                    continue;
                }
            }

            // 비밀번호 설정 (비어있으면 123456)
            const finalPassword = (password && String(password).trim()) ? String(password).trim() : '123456';

            await prisma.user.create({
                data: { 
                    username: trimmedUsername, 
                    role: finalRole, 
                    fullName: fullName ? String(fullName).trim() : null, 
                    employeeId: finalEmployeeId, 
                    isActive: true,
                    password: hashPassword(finalPassword)
                }
            });
            createdCount++;
        } catch (err) {
            console.error('Bulk upload error for item:', data, err);
            skippedCount++;
            skippedItems.push({ username: data.username || 'Unknown', reason: '알 수 없는 오류' });
        }
    }

    revalidatePath('/users');
    revalidatePath('/');
    
    return { 
        success: true, 
        createdCount, 
        skippedCount, 
        skippedItems 
    };
}

export async function deleteUserAction(userId: string) {
    const session = await getSessionAction();
    if (!session || (session.role !== 'ADMIN' && session.role !== 'EDITOR')) {
        throw new Error('접근 권한이 없습니다.');
    }

    // 자기 자신 삭제 방지
    if (session.id === userId) {
        throw new Error('본인의 계정은 삭제할 수 없습니다.');
    }

    // 기본 관리자 계정 삭제 방지
    const targetUser = await prisma.user.findUnique({ where: { id: userId } });
    if (targetUser?.username === 'admin_user') {
        throw new Error('기본 관리자 계정은 삭제할 수 없습니다.');
    }

    await prisma.user.delete({
        where: { id: userId }
    });

    revalidatePath('/users');
    revalidatePath('/');
    return { success: true };
}

/**
 * 보고서에 대한 사용자 접근 권한을 업데이트합니다.
 */
export async function updateReportAccessAction(reportId: string, userIds: string[]) {
    const session = await getSessionAction();
    if (!session || (session.role !== 'ADMIN' && session.role !== 'EDITOR')) {
        throw new Error('접근 권한이 없습니다.');
    }

    await prisma.report.update({
        where: { id: reportId },
        data: {
            authorizedUsers: {
                set: userIds.map(id => ({ id }))
            }
        }
    });

    revalidatePath(`/report/${reportId}`);
    revalidatePath(`/report/${reportId}/input`);
    revalidatePath('/');
    return { success: true };
}

/**
 * 보고서에 접근 권한이 있는 사용자 목록을 가져옵니다.
 */
export async function getAuthorizedUsersForReportAction(reportId: string) {
    const report = await prisma.report.findUnique({
        where: { id: reportId },
        select: { authorizedUsers: { select: { id: true, username: true, fullName: true, role: true } } }
    });
    return report?.authorizedUsers || [];
}

/**
 * 삭제된 데이터 행들을 복구합니다.
 */
export async function restoreRowsAction(reportId: string, rowIds: string[]) {
    const user = await getSessionAction();
    if (!user) throw new Error('인증이 필요합니다.');
    const updaterId = user.id;

    const isAuthorized = await checkReportAuthorization(reportId, user.id, user.role);
    if (!isAuthorized) throw new Error('해당 보고서에 대한 접근 권한이 없습니다.');

    const rows = await prisma.reportRow.findMany({
        where: { id: { in: rowIds } }
    });

    for (const row of rows) {
        // 논리적 삭제 해제
        const updatedRow = await prisma.reportRow.update({
            where: { id: row.id },
            data: {
                isDeleted: false,
                deletedAt: null,
                updaterId: updaterId,
                updatedAt: new Date()
            } as any
        });

        // 복구 이력 생성
        await prisma.reportRowHistory.create({
            data: {
                rowId: row.id,
                oldData: row.data,
                newData: updatedRow.data,
                changeType: 'RESTORE',
                changedById: updaterId || 'system'
            }
        });
    }

    revalidatePath(`/report/${reportId}`);
    revalidatePath(`/report/${reportId}/input`);
    return { success: true };
}
