'use server';

import { revalidatePath } from 'next/cache';
import { redirect } from 'next/navigation';
import prisma from '@/lib/prisma';
import { parseExcelWorkbook } from '@/lib/excel-parser';
import { analyzeExcelImage, extractDataFromImage, recommendSchemaFromSample } from '@/lib/ai-vision';
import crypto from 'crypto';
import fs from 'fs/promises';
import path from 'path';

export async function uploadFileAction(formData: FormData) {
    const file = formData.get('file') as File;
    if (!file) throw new Error('파일이 없습니다.');

    const bytes = await file.arrayBuffer();
    const buffer = Buffer.from(bytes);

    const uploadDir = path.join(process.cwd(), 'public', 'uploads');
    try {
        await fs.access(uploadDir);
    } catch {
        await fs.mkdir(uploadDir, { recursive: true });
    }

    const uniqueName = `${Date.now()}-${file.name.replace(/\s+/g, '_')}`;
    const filePath = path.join(uploadDir, uniqueName);
    await fs.writeFile(filePath, buffer);

    return { url: `/uploads/${uniqueName}`, name: file.name };
}

export async function getSchemaRecommendationAction(reportId: string) {
    const report = await prisma.report.findUnique({ where: { id: reportId } });
    if (!report) throw new Error('보고서를 찾을 수 없습니다.');

    const currentColumns = JSON.parse(report.columns);
    const sampleRows = await prisma.reportRow.findMany({
        where: { reportId },
        take: 20
    });

    const rowsData = sampleRows.map(r => JSON.parse(r.data));
    const recommendation = await recommendSchemaFromSample(currentColumns, rowsData);
    
    return recommendation.columns;
}

/**
 * 데이터 행의 중복 여부를 판단하기 위한 해시값을 생성합니다.
 * @param rowData 객체 형태의 행 데이터
 * @param columns 컬럼 정의 배열
 */
export async function generateContentHash(rowData: any, columns: any[]) {
    // 자동 생성 필드(데이터 ID 등)는 중복 체크에서 제외
    // 사용자가 'isUnique'로 설정한 필드가 있다면 해당 필드들만 조합, 없으면 모든 일반 필드 조합
    const uniqueCols = columns.filter(c => c.isUnique);
    const targetCols = uniqueCols.length > 0 ? uniqueCols : columns.filter(c => !c.isAutoGenerated);
    
    const sortedKeys = targetCols.map(c => c.name).sort();
    const hashSource = sortedKeys.map(key => `${key}:${rowData[key] ?? ''}`).join('|');
    
    return crypto.createHash('sha256').update(hashSource).digest('hex');
}

export async function uploadExcelAction(formData: FormData, userId: string) {
  const file = formData.get('file') as File;
  const configsJson = formData.get('configsJson') as string;
  if (!file) throw new Error('파일이 없습니다.');

  const buffer = Buffer.from(await file.arrayBuffer());
  const configs = configsJson ? JSON.parse(configsJson) : [];
  
  // Use the advanced parser with user-defined configs (header row index, selected fields)
  const sheetResults = parseExcelWorkbook(buffer, configs);

  // Store each sheet/table as a separate report
  for (const sheet of sheetResults) {
    for (const table of sheet.tables) {
      if (table.columns.length === 0) continue; // Skip if no columns selected

      await prisma.report.create({
        data: {
          name: table.name,
          sheetName: sheet.sheetName,
          columns: JSON.stringify(table.columns),
          ownerId: userId,
          rows: {
            create: table.rows.map(row => ({
              data: JSON.stringify(row)
            }))
          }
        }
      });
    }
  }

  revalidatePath('/');
}

export async function addRowAction(reportId: string, rowData: any) {
  const report = await prisma.report.findUnique({ where: { id: reportId } });
  if (!report) throw new Error('보고서를 찾을 수 없습니다.');

  const columns = JSON.parse(report.columns);
  
  // 1. 중복 체크
  const hash = await generateContentHash(rowData, columns);
  const existing = await prisma.reportRow.findFirst({
      where: { reportId, contentHash: hash } as any
  });
  
  if (existing) {
      throw new Error('이미 동일한 내용의 데이터가 존재합니다. (중복 방지)');
  }

  // 2. DID-일련번호 자동 키 생성
  const rowCount = await prisma.reportRow.count({ where: { reportId } });
  const nextSerial = (rowCount + 1).toString().padStart(6, '0');
  
  const finalData = { ...rowData };
  columns.forEach((col: any) => {
    if (col.isAutoGenerated) {
        finalData[col.name] = `DID-${nextSerial}`;
    }
  });

  // 3. Server-side Validation
  for (const col of columns) {
    if (col.isAutoGenerated) continue;
    const val = finalData[col.name];

    if (col.isRequired && (val === undefined || val === null || val === '')) {
        throw new Error(`'${col.name}' 필드는 필수입니다.`);
    }

    if ((col.type === 'number' || col.type === 'currency') && val !== '' && val !== null && val !== undefined) {
        const sVal = String(val);
        const cleanVal = sVal.replace(/[^0-9.-]/g, '').trim();
        if (isNaN(Number(cleanVal))) {
            throw new Error('필드 ' + col.name + '에는 숫자만 입력 가능합니다.');
        }
        finalData[col.name] = Number(cleanVal);
    }
  }

  // 4. 저장
  await prisma.reportRow.create({
      data: {
        reportId,
        data: JSON.stringify(finalData),
        contentHash: hash
      } as any
    });
  revalidatePath(`/report/${reportId}`);
}

export async function deleteReportAction(reportId: string) {
    await prisma.report.update({
        where: { id: reportId },
        data: { 
            isDeleted: true,
            deletedAt: new Date()
        } as any
    });
    revalidatePath('/');
    revalidatePath('/archive');
}

export async function restoreReportAction(reportId: string) {
    await prisma.report.update({
        where: { id: reportId },
        data: { 
            isDeleted: false,
            deletedAt: null
        } as any
    });
    revalidatePath('/');
    revalidatePath('/archive');
}

export async function permanentDeleteReportAction(reportId: string) {
    // 1. 데이터(행) 먼저 삭제
    await prisma.reportRow.deleteMany({ where: { reportId } });
    // 2. 보고서 본체 삭제
    await prisma.report.delete({ where: { id: reportId } });
    
    revalidatePath('/');
    revalidatePath('/archive');
}

export async function deleteRowsAction(reportId: string, rowIds: string[]) {
    await prisma.reportRow.deleteMany({
        where: { id: { in: rowIds } }
    });
    revalidatePath(`/report/${reportId}`);
}

export async function bulkUpdateRowsAction(
    reportId: string, 
    rowIds: string[], 
    fieldName: string, 
    actionType: 'OVERWRITE' | 'FIND_REPLACE', 
    params: { value?: any; find?: string; replace?: string }
) {
    const report = await prisma.report.findUnique({ where: { id: reportId } });
    if (!report) throw new Error('보고서를 찾을 수 없습니다.');

    const columns = JSON.parse(report.columns);
    const colDef = columns.find((c: any) => c.name === fieldName);
    if (!colDef) throw new Error('컬럼 정의를 찾을 수 없습니다.');

    // 1. 대상 행 로드
    const rows = await prisma.reportRow.findMany({
        where: { id: { in: rowIds }, reportId }
    });

    if (rows.length === 0) throw new Error('수정할 데이터가 없습니다.');

    // 2. 일괄 업데이트 처리
    for (const row of rows) {
        const rowData = JSON.parse(row.data);
        let newValue = params.value;

        if (actionType === 'FIND_REPLACE') {
            const currentVal = String(rowData[fieldName] || '');
            newValue = currentVal.replace(new RegExp(params.find || '', 'g'), params.replace || '');
            
            // 타입 복원 (숫자/통화인 경우)
            if (colDef.type === 'number' || colDef.type === 'currency') {
                const cleanVal = newValue.replace(/[^0-9.-]/g, '').trim();
                newValue = isNaN(Number(cleanVal)) ? newValue : Number(cleanVal);
            }
        }

        // 유효성 검사 (Overwrite인 경우에도 적용)
        if (colDef.type === 'number' || colDef.type === 'currency') {
            const sVal = String(newValue);
            const cleanVal = sVal.replace(/[^0-9.-]/g, '').trim();
            if (isNaN(Number(cleanVal))) {
                throw new Error(`${fieldName} 필드에는 숫자만 입력 가능합니다.`);
            }
            newValue = Number(cleanVal);
        }

        rowData[fieldName] = newValue;

        // 중복 체크용 해시 재생성
        const newHash = await generateContentHash(rowData, columns);
        
        // 3. 개별 업데이트 (간단한 구현을 위해 순차 처리)
        await prisma.reportRow.update({
            where: { id: row.id },
            data: {
            data: JSON.stringify(rowData),
            contentHash: newHash
        } as any
    });
    }

    revalidatePath(`/report/${reportId}`);
    return { success: true, count: rows.length };
}


export async function updateSingleRowAction(
    reportId: string, 
    rowId: string, 
    newData: any
) {
    const report = await prisma.report.findUnique({ where: { id: reportId } });
    if (!report) throw new Error('보고서를 찾을 수 없습니다.');

    const columns = JSON.parse(report.columns);
    
    // 1. 중복 체크용 해시 생성
    const hash = await generateContentHash(newData, columns);
    const existing = await prisma.reportRow.findFirst({
        where: { 
            reportId, 
            contentHash: hash,
            id: { not: rowId } // 자신은 제외
        } as any
    });
    
    if (existing) {
        throw new Error('이미 동일한 내용의 데이터가 존재합니다. (중복 방지)');
    }

    // 2. 유효성 검사
    const finalData = { ...newData };
    for (const col of columns) {
        if (col.isAutoGenerated) continue;
        const val = finalData[col.name];

        if (col.isRequired && (val === undefined || val === null || val === '')) {
            throw new Error(`'${col.name}' 필드는 필수입니다.`);
        }

        if ((col.type === 'number' || col.type === 'currency') && val !== '' && val !== null && val !== undefined) {
            const sVal = String(val);
            const cleanVal = sVal.replace(/[^0-9.-]/g, '').trim();
            if (isNaN(Number(cleanVal))) {
                throw new Error(`${col.name} 필드에는 숫자만 입력 가능합니다.`);
            }
            finalData[col.name] = Number(cleanVal);
        }
    }

    // 3. 업데이트
    await prisma.reportRow.update({
        where: { id: rowId },
        data: {
            data: JSON.stringify(finalData),
            contentHash: hash
        } as any
    });

    revalidatePath(`/report/${reportId}`);
    return { success: true };
}

export async function renameReportAction(reportId: string, newName: string) {

    await prisma.report.update({
        where: { id: reportId },
        data: { name: newName }
    });
    revalidatePath('/');
    revalidatePath(`/report/${reportId}`);
}

export async function updateReportSchemaAction(reportId: string, columns: any[]) {
    await prisma.report.update({
        where: { id: reportId },
        data: { columns: JSON.stringify(columns) }
    });
    revalidatePath(`/report/${reportId}`);
}

export async function analyzeExcelScreenshotAction(formData: FormData) {
  const image = formData.get('image') as File;
  if (!image) throw new Error('이미지 파일이 없습니다.');

  const arrayBuffer = await image.arrayBuffer();
  const buffer = Buffer.from(arrayBuffer);
  const base64 = buffer.toString('base64');
  const mimeType = image.type;

  return await analyzeExcelImage(base64, mimeType);
}

export async function addRowsAction(reportId: string, rows: any[]) {
    const report = await prisma.report.findUnique({ where: { id: reportId } });
    if (!report) throw new Error('보고서를 찾을 수 없습니다.');
  
    const columns = JSON.parse(report.columns);
    const initialRowCount = await prisma.reportRow.count({ where: { reportId } });
    let skippedCount = 0;
    
    // 1. 기존 데이터의 해시값 로드 (중복 체크용)
    const existingRows = await prisma.reportRow.findMany({
        where: { reportId, contentHash: { not: null } } as any,
        select: { contentHash: true } as any
    });
    const existingHashes = new Set(existingRows.map(function(r: any) { return r.contentHash; }));

    // 2. 각 행당 유효성 검사 및 정제
    const cleanedRowsToInsert = [];
    
    for (const rowData of rows) {
        const finalData: any = {};
        
        // 매핑
        columns.forEach((col: any) => {
            if (!col.isAutoGenerated) {
                finalData[col.name] = rowData[col.name];
            }
        });

        // 중복 체크용 해시 생성
        const hash = await generateContentHash(finalData, columns);
        
        if (existingHashes.has(hash)) {
            skippedCount++;
            continue; 
        }

        // 유효성 검사 및 정제
        for (const col of columns) {
            if (col.isAutoGenerated) continue;
            const val = finalData[col.name];

            if (col.isRequired && (val === undefined || val === null || val === '')) {
                if (val !== 0) throw new Error('필드 ' + col.name + '에 값이 누락되었습니다.');
            }

            if ((col.type === 'number' || col.type === 'currency') && val !== '' && val !== null && val !== undefined) {
                const sVal = String(val);
                const cleanVal = sVal.replace(/[^0-9.-]/g, '').trim();
                const numericVal = Number(cleanVal);
                if (!isNaN(numericVal)) {
                    finalData[col.name] = numericVal;
                }
            }
        }

        // 인서트 데이터 구성
        const nextSerial = (initialRowCount + cleanedRowsToInsert.length + 1).toString().padStart(6, '0');
        const rowWithMetadata: any = { ...finalData };
        
        columns.forEach((col: any) => {
            if (col.isAutoGenerated) {
                rowWithMetadata[col.name] = 'DID-' + nextSerial;
            }
        });

        cleanedRowsToInsert.push({
            data: JSON.stringify(rowWithMetadata),
            contentHash: hash,
            reportId: reportId
        });
        
        existingHashes.add(hash);
    }
  
    if (cleanedRowsToInsert.length > 0) {
        await prisma.reportRow.createMany({
            data: cleanedRowsToInsert as any
        });
    }
  
    revalidatePath('/report/' + reportId);
    return { 
        success: true, 
        addedCount: cleanedRowsToInsert.length, 
        skippedCount 
    };
}

export async function createManualReportAction(name: string, sheetName: string, columns: any[]) {
    // 1. 유저 확인
    let user = await prisma.user.findUnique({ where: { username: 'admin_user' } });
    if (!user) {
        user = await prisma.user.create({
            data: { username: 'admin_user', role: 'ADMIN' }
        });
    }

    // 2. 컬럼 준비 (Data ID 가 없으면 첫 번째로 자동 추가)
    // 엑셀 업로드와 동일하게 isAutoGenerated: true 인 컬럼을 DID-XXXXXX 용으로 사용합니다.
    const hasAutoId = columns.some(c => c.isAutoGenerated);
    let finalColumns = [...columns];
    if (!hasAutoId) {
        finalColumns = [
            { id: 'did', name: '데이터 ID', type: 'string', isRequired: true, isAutoGenerated: true },
            ...columns
        ];
    }

    // 3. 보고서 생성
    const report = await prisma.report.create({
        data: {
            name,
            sheetName,
            columns: JSON.stringify(finalColumns),
            ownerId: user.id
        }
    });

    revalidatePath('/');
    redirect(`/report/${report.id}?action=new`);
}

export async function analyzeImageAndExtractDataAction(formData: FormData, columnsJson: string) {
    try {
        const image = formData.get('image') as File;
        if (!image) throw new Error('이미지 파일이 없습니다.');
        
        console.log(`Analyzing image: ${image.name}, size: ${Math.round(image.size / 1024)} KB, type: ${image.type}`);

        const columns = JSON.parse(columnsJson);
        const arrayBuffer = await image.arrayBuffer();
        const buffer = Buffer.from(arrayBuffer);
        const base64 = buffer.toString('base64');
        const mimeType = image.type;

        const extractedData = await extractDataFromImage(base64, mimeType, columns);
        return { success: true, data: extractedData };
    } catch (error: any) {
        console.error("AI Analysis Action Error:", error);
        // 에러 메시지를 가공하여 사용자에게 친숙하게 전달
        let errorMessage = error.message || '이미지를 분석하는 중 오류가 발생했습니다.';
        if (errorMessage.includes('413')) {
            errorMessage = '이미지 용량이 너무 큽니다. 더 작은 이미지를 사용해 주세요.';
        }
        return { success: false, error: errorMessage };
    }
}
