'use client';

import React, { useState } from 'react';
import { X, Loader2, Edit3, Repeat, AlertCircle, ChevronDown, Check } from 'lucide-react';
import { bulkUpdateRowsAction } from '@/app/actions';

interface Column {
  name: string;
  type: string;
  options?: string[];
  isAutoGenerated?: boolean;
}

interface BulkEditModalProps {
  reportId: string;
  selectedIds: string[];
  columns: Column[];
  onClose: () => void;
  onSuccess: (count: number) => void;
  onStatusShow?: (title: string, message: string, type: 'success' | 'error' | 'info') => void;
}

export default function BulkEditModal({ 
  reportId, 
  selectedIds, 
  columns, 
  onClose, 
  onSuccess,
  onStatusShow 
}: BulkEditModalProps) {
  const [selectedField, setSelectedField] = useState<string>('');
  const [mode, setMode] = useState<'OVERWRITE' | 'FIND_REPLACE'>('OVERWRITE');
  const [value, setValue] = useState<any>('');
  const [findText, setFindText] = useState('');
  const [replaceText, setReplaceText] = useState('');
  const [isSubmitting, setIsSubmitting] = useState(false);

  const editableColumns = columns.filter(col => !col.isAutoGenerated);
  const currentCol = editableColumns.find(c => c.name === selectedField);
  
  // 찾아바꾸기 가능 여부 (텍스트 계열만)
  const isFindReplaceEnabled = currentCol && ['string', 'textarea', 'email', 'phone'].includes(currentCol.type);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!selectedField) return;

    setIsSubmitting(true);
    try {
      const result = await bulkUpdateRowsAction(
        reportId,
        selectedIds,
        selectedField,
        mode,
        mode === 'OVERWRITE' 
          ? { value } 
          : { find: findText, replace: replaceText }
      );

      if (result.success) {
        onSuccess(result.count);
        onClose();
      }
    } catch (error: any) {
      if (onStatusShow) {
        onStatusShow('수정 실패', error.message || '일괄 수정 중 오류가 발생했습니다.', 'error');
      } else {
        alert(error.message || '일괄 수정 중 오류가 발생했습니다.');
      }
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="fixed inset-0 bg-black/60 backdrop-blur-sm z-50 flex items-center justify-center p-4 animate-in fade-in duration-200">
      <div className="bg-white w-full max-w-lg rounded-[32px] shadow-2xl border border-gray-100 overflow-hidden flex flex-col animate-in zoom-in-95 duration-200">
        {/* Header */}
        <div className="px-8 py-6 border-b border-gray-50 flex items-center justify-between bg-gray-50/50">
          <div>
            <div className="flex items-center gap-2 mb-1">
              <Edit3 size={18} className="text-blue-600" />
              <h2 className="text-xl font-black text-gray-900 tracking-tight">데이터 일괄 수정</h2>
            </div>
            <p className="text-[11px] font-bold text-gray-400 uppercase tracking-widest">
              선택된 {selectedIds.length}건의 데이터를 수정합니다.
            </p>
          </div>
          <button 
            onClick={onClose}
            className="p-2 hover:bg-white rounded-full text-gray-400 hover:text-gray-600 transition-all border border-transparent hover:border-gray-100 shadow-sm"
          >
            <X size={20} />
          </button>
        </div>

        <form onSubmit={handleSubmit} className="p-8 space-y-8">
          {/* Field Selection */}
          <div className="space-y-3">
            <label className="text-xs font-black text-gray-400 uppercase tracking-widest flex items-center gap-2">
              <ChevronDown size={14} className="text-blue-500" />
              수정할 컬럼 선택
            </label>
            <div className="relative">
              <select
                required
                value={selectedField}
                onChange={(e) => {
                  setSelectedField(e.target.value);
                  setValue('');
                  // 텍스트 계열이 아니면 자동으로 OVERWRITE 모드로 전환
                  const col = editableColumns.find(c => c.name === e.target.value);
                  if (col && !['string', 'textarea', 'email', 'phone'].includes(col.type)) {
                    setMode('OVERWRITE');
                  }
                }}
                className="w-full pl-4 pr-10 py-3 bg-gray-50 border border-gray-100 rounded-2xl text-sm font-bold text-gray-700 focus:bg-white focus:ring-2 focus:ring-blue-100 focus:border-blue-400 outline-none transition-all appearance-none cursor-pointer"
              >
                <option value="">컬럼을 선택해 주세요</option>
                {editableColumns.map(col => (
                  <option key={col.name} value={col.name}>{col.name} ({col.type})</option>
                ))}
              </select>
              <ChevronDown size={18} className="absolute right-4 top-1/2 -translate-y-1/2 text-gray-400 pointer-events-none" />
            </div>
          </div>

          {selectedField && (
            <>
              {/* Mode Selection */}
              <div className="flex p-1 bg-gray-50 rounded-2xl border border-gray-100">
                <button
                  type="button"
                  onClick={() => setMode('OVERWRITE')}
                  className={`flex-1 flex items-center justify-center gap-2 py-3 rounded-xl text-xs font-black transition-all ${mode === 'OVERWRITE' ? 'bg-white text-blue-600 shadow-sm' : 'text-gray-400 hover:text-gray-600'}`}
                >
                  <Edit3 size={14} /> 일괄 변경 (Overwrite)
                </button>
                <button
                  type="button"
                  onClick={() => isFindReplaceEnabled && setMode('FIND_REPLACE')}
                  disabled={!isFindReplaceEnabled}
                  className={`
                    flex-1 flex items-center justify-center gap-2 py-3 rounded-xl text-xs font-black transition-all
                    ${mode === 'FIND_REPLACE' ? 'bg-white text-indigo-600 shadow-sm' : 'text-gray-400'}
                    ${!isFindReplaceEnabled ? 'opacity-30 cursor-not-allowed' : 'hover:text-gray-600'}
                  `}
                >
                  <Repeat size={14} /> 찾아바꾸기 (Replace)
                </button>
              </div>

              {!isFindReplaceEnabled && selectedField && mode === 'OVERWRITE' && (
                <p className="text-[10px] font-bold text-amber-500 flex items-center gap-1.5 -mt-4 italic">
                  <AlertCircle size={10} /> 이 컬럼 타입({currentCol?.type})은 '찾아바꾸기'를 지원하지 않습니다.
                </p>
              )}

              {/* Inputs */}
              <div className="bg-blue-50/30 p-6 rounded-3xl border border-blue-100/50 space-y-4 animate-in slide-in-from-top-2">
                {mode === 'OVERWRITE' ? (
                  <div className="space-y-4">
                    <label className="text-xs font-black text-blue-800 uppercase tracking-widest flex items-center gap-2">
                      <Check size={14} className="text-blue-600" />
                      새 값 입력
                    </label>
                    {currentCol?.type === 'select' ? (
                      <div className="relative">
                        <select
                          required
                          value={value}
                          onChange={(e) => setValue(e.target.value)}
                          className="w-full pl-4 pr-10 py-3 bg-white border border-blue-100 rounded-[20px] text-sm font-bold text-gray-700 focus:ring-4 focus:ring-blue-100 outline-none transition-all appearance-none"
                        >
                          <option value="">값을 선택하세요</option>
                          {currentCol.options?.map(opt => <option key={opt} value={opt}>{opt}</option>)}
                        </select>
                        <ChevronDown size={18} className="absolute right-4 top-1/2 -translate-y-1/2 text-blue-300 pointer-events-none" />
                      </div>
                    ) : currentCol?.type === 'boolean' ? (
                      <div className="flex gap-2">
                        {['Yes', 'No'].map(opt => (
                          <button
                            key={opt}
                            type="button"
                            onClick={() => setValue(opt)}
                            className={`flex-1 py-3 rounded-2xl text-xs font-black transition-all border ${value === opt ? 'bg-blue-600 text-white border-blue-600 shadow-lg shadow-blue-100' : 'bg-white text-gray-400 border-gray-100 hover:border-blue-200 hover:text-gray-600'}`}
                          >
                            {opt === 'Yes' ? '예 (Yes)' : '아니오 (No)'}
                          </button>
                        ))}
                      </div>
                    ) : (
                      <input
                        required
                        type={currentCol?.type === 'date' ? 'date' : 'text'}
                        value={value}
                        onChange={(e) => setValue(e.target.value)}
                        placeholder={`${selectedField}에 적용할 새 값을 입력하세요`}
                        className="w-full px-5 py-4 bg-white border border-blue-100 rounded-[24px] text-sm font-bold text-gray-700 focus:ring-4 focus:ring-blue-100 outline-none transition-all placeholder:text-gray-300"
                      />
                    )}
                  </div>
                ) : (
                  <div className="space-y-4">
                    <div className="space-y-2">
                      <label className="text-[10px] font-black text-indigo-800 uppercase tracking-widest pl-2">찾을 내용</label>
                      <input
                        required
                        type="text"
                        value={findText}
                        onChange={(e) => setFindText(e.target.value)}
                        placeholder="검색할 문자열"
                        className="w-full px-5 py-4 bg-white border border-indigo-100 rounded-[20px] text-sm font-bold text-gray-700 focus:ring-4 focus:ring-indigo-100 outline-none transition-all placeholder:text-gray-300"
                      />
                    </div>
                    <div className="flex items-center justify-center">
                       <Repeat size={16} className="text-indigo-200 rotate-90" />
                    </div>
                    <div className="space-y-2">
                      <label className="text-[10px] font-black text-indigo-800 uppercase tracking-widest pl-2">바꿀 내용</label>
                      <input
                        type="text"
                        value={replaceText}
                        onChange={(e) => setReplaceText(e.target.value)}
                        placeholder="치환할 문자열 (비워두면 삭제)"
                        className="w-full px-5 py-4 bg-white border border-indigo-100 rounded-[20px] text-sm font-bold text-gray-700 focus:ring-4 focus:ring-indigo-100 outline-none transition-all placeholder:text-gray-300"
                      />
                    </div>
                  </div>
                )}
              </div>
            </>
          )}

          {/* Footer Buttons */}
          <div className="flex gap-3 pt-4">
            <button
              type="button"
              onClick={onClose}
              className="flex-1 py-4 text-xs font-black text-gray-400 bg-gray-50 rounded-[24px] hover:bg-gray-100 transition-all border border-transparent hover:border-gray-100"
            >
              취소하기
            </button>
            <button
              type="submit"
              disabled={isSubmitting || !selectedField}
              className="flex-1 py-4 text-xs font-black text-white bg-blue-600 rounded-[24px] shadow-xl shadow-blue-100 hover:bg-blue-700 transition-all active:scale-95 disabled:opacity-50 disabled:scale-100 flex items-center justify-center gap-2"
            >
              {isSubmitting ? (
                <>
                  <Loader2 size={16} className="animate-spin" />
                  처리 중...
                </>
              ) : (
                '변경 사항 적용'
              )}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
