'use client';

import React from 'react';
import { ChevronDown } from 'lucide-react';

interface Column {
  name: string;
  type: string;
  isAutoGenerated?: boolean;
  isRequired?: boolean;
  options?: string[];
}

interface DynamicFormProps {
  columns: Column[];
  initialData?: any;
  onSubmit: (data: any) => void;
  onCancel?: () => void;
}

export default function DynamicForm({ columns, initialData = {}, onSubmit, onCancel }: DynamicFormProps) {
  const [formData, setFormData] = React.useState(initialData);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
    const { name, value, type } = e.target as any;
    setFormData((prev: any) => ({
      ...prev,
      [name]: type === 'number' ? (value === '' ? '' : Number(value)) : value,
    }));
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    
    // 최종 유효성 검사 (서버 전송 전)
    for (const col of columns) {
        if (col.isAutoGenerated) continue;
        const val = formData[col.name];

        if (col.isRequired && (val === undefined || val === null || val === '')) {
            alert(`'${col.name}' 필드는 필수 입력 항목입니다.`);
            return;
        }

        if (col.type === 'number' && val !== '' && isNaN(Number(val))) {
            alert(`'${col.name}' 필드에는 숫자만 입력 가능합니다.`);
            return;
        }
    }

    onSubmit(formData);
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-6 bg-white p-8 border rounded-xl shadow-sm">
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {columns.map((col) => {
          const val = formData[col.name];
          const isNumericType = col.type === 'number' || col.type === 'currency';
          const isInvalidType = isNumericType && val !== '' && val !== undefined && isNaN(Number(val?.toString().replace(/[,₩$¥€]/g, '')));
          
          return (
            <div key={col.name} className={`flex flex-col gap-2 ${col.isAutoGenerated ? 'opacity-70' : ''}`}>
              <label htmlFor={col.name} className="text-sm font-semibold text-gray-700 flex items-center justify-between">
                <span className="flex items-center gap-1.5 min-w-0">
                  <span className="truncate">{col.name}</span>
                  {col.isRequired && !col.isAutoGenerated && <span className="text-red-500">*</span>}
                  {!col.isAutoGenerated && (
                      <span className={`
                        text-[8px] font-black px-1.5 py-0.5 rounded border uppercase tracking-tighter shrink-0
                        ${col.type === 'number' ? 'bg-blue-50 text-blue-600 border-blue-100' : 
                          col.type === 'date' ? 'bg-green-50 text-green-600 border-green-100' : 
                          col.type === 'currency' ? 'bg-purple-50 text-purple-600 border-purple-100' :
                          'bg-gray-50 text-gray-500 border-gray-200'}
                      `}>
                        {col.type === 'number' ? 'NUM' : col.type === 'date' ? 'DATE' : col.type === 'currency' ? 'CURRENCY' : 'TEXT'}
                      </span>
                  )}
                </span>
                {col.isAutoGenerated && <span className="text-[10px] font-black text-indigo-500 bg-indigo-50 px-2 py-0.5 rounded-md">AUTO_KEY</span>}
              </label>
              <div className="relative flex items-stretch">
                  {col.type === 'currency' && (
                      <select 
                        className="bg-gray-50 border border-r-0 border-gray-200 rounded-l-lg px-2 text-xs font-bold text-gray-500 outline-none focus:ring-0 appearance-none cursor-pointer hover:bg-gray-100 transition-colors"
                        onChange={(e) => {
                            const symbol = e.target.value;
                            const currentVal = formData[col.name]?.toString() || '';
                            const cleanVal = currentVal.replace(/^[₩$¥€]\s?/, '');
                            setFormData((prev: any) => ({
                                ...prev,
                                [col.name]: `${symbol} ${cleanVal}`.trim()
                            }));
                        }}
                        defaultValue="₩"
                      >
                          <option value="₩">₩ (KRW)</option>
                          <option value="$">$ (USD)</option>
                          <option value="€">€ (EUR)</option>
                          <option value="¥">¥ (JPY)</option>
                      </select>
                  )}
                  {col.type === 'select' ? (
                      <div className="relative w-full">
                          <select
                            id={col.name}
                            name={col.name}
                            value={formData[col.name] || ''}
                            onChange={handleChange}
                            className="w-full px-4 py-2 border border-gray-200 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-none transition-all font-medium appearance-none bg-white cursor-pointer hover:bg-gray-50"
                            required={col.isRequired}
                          >
                              <option value="">선택하세요</option>
                              {col.options?.map(opt => (
                                  <option key={opt} value={opt}>{opt}</option>
                              ))}
                          </select>
                          <ChevronDown size={14} className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400 pointer-events-none" />
                      </div>
                  ) : (
                      <input
                        id={col.name}
                        name={col.name}
                        type={col.type === 'date' ? 'date' : 'text'}
                        value={
                            col.isAutoGenerated 
                            ? (formData[col.name] || '자동 생성 데이터') 
                            : (col.type === 'currency' 
                               ? (formData[col.name]?.toString().replace(/^[₩$¥€]\s?/, '') || '') 
                               : (formData[col.name] || ''))
                        }
                        onChange={(e) => {
                            if (col.type === 'currency') {
                                const val = e.target.value;
                                const existingSymbol = formData[col.name]?.toString().match(/^[₩$¥€]/)?.[0] || '₩';
                                setFormData((prev: any) => ({
                                    ...prev,
                                    [col.name]: `${existingSymbol} ${val}`.trim()
                                }));
                            } else {
                                handleChange(e);
                            }
                        }}
                        readOnly={col.isAutoGenerated}
                        disabled={col.isAutoGenerated}
                        className={`
                           w-full px-4 py-2 border rounded-lg transition-all
                           ${col.type === 'currency' ? 'rounded-l-none' : ''}
                           ${col.isAutoGenerated ? 'bg-gray-50 text-gray-400 border-gray-100 cursor-not-allowed' : 
                             isInvalidType ? 'border-red-500 bg-red-50 focus:ring-red-500' : 'focus:ring-2 focus:ring-blue-500 focus:border-blue-500 border-gray-200'}
                        `}
                        placeholder={col.isAutoGenerated ? '자동으로 부여되는 고유키입니다' : `${col.name} 입력`}
                        required={col.isRequired && !col.isAutoGenerated}
                      />
                  )}
                  {isInvalidType && (
                      <p className="absolute -bottom-5 left-0 text-[10px] font-bold text-red-500 flex items-center gap-1 animate-in fade-in slide-in-from-top-1">
                          <span className="bg-red-500 text-white rounded-full w-3 h-3 flex items-center justify-center text-[8px]">!</span>
                          숫자 데이터만 입력 가능합니다.
                      </p>
                  )}
              </div>
            </div>
          );
        })}
      </div>
      <div className="flex justify-end gap-3 pt-4 border-t">
        {onCancel && (
          <button
            type="button"
            onClick={onCancel}
            className="px-6 py-2 text-sm font-medium text-gray-600 bg-gray-100 rounded-lg hover:bg-gray-200 transition-colors"
          >
            취소
          </button>
        )}
        <button
          type="submit"
          className="px-6 py-2 text-sm font-medium text-white bg-blue-600 rounded-lg hover:bg-blue-700 shadow-md transition-colors"
        >
          저장하기
        </button>
      </div>
    </form>
  );
}
