'use client';

import React, { useState, useMemo, useEffect } from 'react';
import { 
    Trash2, Edit3, Search, ArrowUpDown, ArrowUp, ArrowDown, FilterX, FileDown, 
    Table as TableIcon, FileText, ChevronLeft, ChevronRight, ChevronsLeft, 
    ChevronsRight, CheckCircle2, XCircle, ExternalLink, Eye, 
    History as HistoryIcon, Plus, FileSpreadsheet, Sparkles, RotateCcw, Mail, 
    Phone, Check, X as XIcon, Loader2
} from 'lucide-react';
import { deleteRowsAction, updateSingleRowAction, restoreRowsAction } from '@/app/actions/row';
import * as XLSX from 'xlsx';
import { BulkEditModal } from './BulkEditModal';
import { StatusModal } from './StatusModal';
import { AuditHistoryModal } from './AuditHistoryModal';

/**
 * 🛡️ Paranoid SafeIcon for DynamicTable
 * Prevents 'undefined' component runtime errors in this massive component.
 */
const SafeIcon = ({ icon: Icon, isMounted, ...props }: any) => {
    if (!isMounted || !Icon) return null;
    const isComponent = typeof Icon === 'function' || typeof Icon === 'object';
    if (!isComponent) return <div className="w-3 h-3 rounded-full bg-slate-300 opacity-50 shrink-0" />;
    try {
        return <Icon {...props} />;
    } catch (err) {
        return null;
    }
};

interface Column {
  name: string;
  type: string;
  autoPrefix?: string;
  isAutoGenerated?: boolean;
}

interface DynamicTableProps {
  reportId: string;
  columns: Column[];
  data: any[];
  isOwner?: boolean;
  isAdmin?: boolean;
  canEdit?: boolean;
  isReadOnly?: boolean;
  userRole?: string;
  currentUserId?: string | null;
  onStatusShow?: (title: string, message: string, type: 'success' | 'error' | 'info') => void;
  onToggleAddRecord?: () => void;
  onToggleBulkUpload?: () => void;
  onToggleAIImport?: () => void;
}

export function DynamicTable({ 
    reportId, 
    columns, 
    data, 
    isOwner = false, 
    canEdit = true,
    isReadOnly = false,
    userRole = 'VIEWER', 
    currentUserId, 
    onStatusShow,
    onToggleAddRecord,
    onToggleBulkUpload,
    onToggleAIImport
}: DynamicTableProps) {
  const [isMounted, setIsMounted] = useState(false);

  useEffect(() => {
    setIsMounted(true);
    console.log('[DIAGNOSTIC] DynamicTable module mounted');
  }, []);

  // Global window debugging
  useEffect(() => {
    if (typeof window !== 'undefined' && isMounted) {
       (window as any).DEBUG_FINANCE_ROWS = data;
    }
  }, [data, isMounted]);

  // 전체 테이블 수준에서의 권한
  const hasBaseEditAuth = !isReadOnly && canEdit && (isOwner || userRole === 'ADMIN' || userRole === 'EDITOR' || userRole === 'VIEWER');
  const hasBaseDeleteAuth = !isReadOnly && canEdit && (isOwner || userRole === 'ADMIN' || userRole === 'EDITOR' || userRole === 'VIEWER');

  // 개별 행에 대한 관리 권한 유무 확인 함수
  const isRowManager = (row: any) => {
    if (isOwner || userRole === 'ADMIN' || userRole === 'EDITOR') return true;
    return userRole === 'VIEWER' && row.creatorId === currentUserId;
  };

  const [selectedIds, setSelectedIds] = useState<string[]>([]);
  const [isDeleting, setIsDeleting] = useState(false);
  const [searchTerm, setSearchTerm] = useState('');
  const [sortConfig, setSortConfig] = useState<{ key: string; direction: 'asc' | 'desc' | null }>({ key: '데이터ID', direction: 'desc' });
  const [isExportingMenuOpen, setIsExportingMenuOpen] = useState(false);
  const [isBulkEditOpen, setIsBulkEditOpen] = useState(false);
  const [editingRowId, setEditingRowId] = useState<string | null>(null);
  const [editFormData, setEditFormData] = useState<any>({});
  const [historyRowId, setHistoryRowId] = useState<string | null>(null);
  const [showDeleted, setShowDeleted] = useState(false);
  const [isRestoring, setIsRestoring] = useState(false);
  
  const [localModalStatus, setLocalModalStatus] = useState<{
    isOpen: boolean;
    title: string;
    message: string;
    type: 'success' | 'error' | 'info';
  }>({
    isOpen: false,
    title: '',
    message: '',
    type: 'info'
  });

  const showStatus = (title: string, message: string, type: 'success' | 'error' | 'info') => {
    if (onStatusShow) {
      onStatusShow(title, message, type);
    } else {
      setLocalModalStatus({ isOpen: true, title, message, type });
    }
  };
  const [currentPage, setCurrentPage] = useState(1);
  const [itemsPerPage, setItemsPerPage] = useState(10);

  useEffect(() => {
    setCurrentPage(1);
  }, [searchTerm, sortConfig, showDeleted]);

  // 1. 데이터 필터링 및 정렬
  const processedData = useMemo(() => {
    let filtered = [...data];
    filtered = filtered.filter(row => showDeleted ? row.isDeleted : !row.isDeleted);
    if (searchTerm) {
        const lowerSearch = searchTerm.toLowerCase();
        filtered = filtered.filter(row => 
            Object.values(row).some(val => 
                val?.toString().toLowerCase().includes(lowerSearch)
            )
        );
    }
    if (sortConfig.key && sortConfig.direction) {
        filtered.sort((a, b) => {
            let aVal = a[sortConfig.key];
            let bVal = b[sortConfig.key];
            if (aVal === bVal) {
                const timeA = a.updatedAt ? new Date(a.updatedAt).getTime() : 0;
                const timeB = b.updatedAt ? new Date(b.updatedAt).getTime() : 0;
                return timeB - timeA;
            }
            if (aVal === null || aVal === undefined || aVal === '') return 1;
            if (bVal === null || bVal === undefined || bVal === '') return -1;
            const result = String(aVal).localeCompare(String(bVal), undefined, { numeric: true, sensitivity: 'base' });
            return sortConfig.direction === 'asc' ? result : -result;
        });
    }
    return filtered;
  }, [data, searchTerm, sortConfig, showDeleted]);

  // 2. 페이지네이션 계산
  const totalPages = Math.ceil(processedData.length / itemsPerPage);
  const paginatedData = useMemo(() => {
    const start = (currentPage - 1) * itemsPerPage;
    return processedData.slice(start, start + itemsPerPage);
  }, [processedData, currentPage, itemsPerPage]);

  const exportToExcel = () => {
    try {
        const exportData = processedData.map(row => {
            const rowObj: any = {};
            columns.forEach(col => {
                let val = row[col.name];
                if (col.type === 'date' && typeof val === 'number') {
                    const date = new Date(Math.round((val - 25569) * 86400 * 1000));
                    val = date.toISOString().split('T')[0];
                }
                rowObj[col.name] = val;
            });
            return rowObj;
        });
        const ws = XLSX.utils.json_to_sheet(exportData);
        const wb = XLSX.utils.book_new();
        XLSX.utils.book_append_sheet(wb, ws, 'Data');
        const excelBuffer = XLSX.write(wb, { bookType: 'xlsx', type: 'array' });
        const dataBlob = new Blob([excelBuffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;charset=UTF-8' });
        const url = window.URL.createObjectURL(dataBlob);
        const link = document.createElement('a');
        link.href = url;
        link.setAttribute('download', `export_${reportId}_${new Date().getTime()}.xlsx`);
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        window.URL.revokeObjectURL(url);
        setIsExportingMenuOpen(false);
        showStatus('다운로드 완료', '엑셀 파일 다운로드가 완료되었습니다.', 'success');
    } catch (error) {
        showStatus('다운로드 실패', '엑셀 파일을 생성하는 중 오류가 발생했습니다.', 'error');
    }
  };

  const exportToCSV = () => {
    const headers = columns.map(col => col.name).join(',');
    const csvRows = processedData.map(row => 
        columns.map(col => {
            let val = row[col.name]?.toString() || '';
            if (col.type === 'date' && typeof row[col.name] === 'number') {
                const date = new Date(Math.round((Number(row[col.name]) - 25569) * 86400 * 1000));
                val = date.toISOString().split('T')[0];
            }
            return `"${val.replace(/"/g, '""')}"`;
        }).join(',')
    );
    const csvContent = "\uFEFF" + [headers, ...csvRows].join('\n');
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement('a');
    link.href = URL.createObjectURL(blob);
    link.download = `export_${reportId}_${new Date().getTime()}.csv`;
    link.click();
    setIsExportingMenuOpen(false);
  };

  const toggleSort = (key: string) => {
    setSortConfig(prev => {
        if (prev.key === key) {
            if (prev.direction === 'asc') return { key, direction: 'desc' };
            if (prev.direction === 'desc') return { key: '', direction: null };
        }
        return { key, direction: 'asc' };
    });
  };

  const toggleSelectAll = () => {
    if (selectedIds.length === processedData.length) {
      setSelectedIds([]);
    } else {
      setSelectedIds(processedData.map(row => row.id));
    }
  };

  const toggleSelectRow = (id: string) => {
    setSelectedIds(prev => 
      prev.includes(id) ? prev.filter(i => i !== id) : [...prev, id]
    );
  };

  const handleDeleteSelected = async () => {
    if (selectedIds.length === 0) return;
    if (!confirm(`${selectedIds.length}개의 데이터를 삭제하시겠습니까?`)) return;
    setIsDeleting(true);
    try {
      const result = await deleteRowsAction(reportId, selectedIds);
      showStatus('삭제 완료', '데이터가 성공적으로 삭제되었습니다.', 'success');
      setSelectedIds([]);
    } catch (error) {
      showStatus('삭제 실패', '데이터 삭제 중 오류가 발생했습니다.', 'error');
    } finally {
      setIsDeleting(false);
    }
  };

  const handleRestoreSelected = async () => {
    if (selectedIds.length === 0) return;
    if (!confirm(`${selectedIds.length}개의 데이터를 복구하시겠습니까?`)) return;
    setIsRestoring(true);
    try {
      await restoreRowsAction(reportId, selectedIds);
      showStatus('복구 완료', '데이터가 성공적으로 복구되었습니다.', 'success');
      setSelectedIds([]);
    } catch (error: any) {
      showStatus('복구 실패', error.message || '데이터 복구 중 오류가 발생했습니다.', 'error');
    } finally {
      setIsRestoring(false);
    }
  };

  const handleSingleRestore = async (id: string) => {
    if (!confirm('이 데이터를 복구하시겠습니까?')) return;
    setIsRestoring(true);
    try {
      await restoreRowsAction(reportId, [id]);
      showStatus('복구 완료', '데이터가 성공적으로 복구되었습니다.', 'success');
    } catch (error: any) {
      showStatus('복구 실패', error.message || '데이터 복구 중 오류가 발생했습니다.', 'error');
    } finally {
      setIsRestoring(false);
    }
  };

  const handleEditStart = (row: any) => {
    setEditingRowId(row.id);
    setEditFormData({ ...row });
  };

  const handleEditCancel = () => {
    setEditingRowId(null);
    setEditFormData({});
  };

  const handleEditSave = async () => {
    if (!editingRowId) return;
    try {
      const result = await updateSingleRowAction(reportId, editingRowId, editFormData);
      if (result.success) {
        showStatus('수정 완료', '데이터가 성공적으로 수정되었습니다.', 'success');
        setEditingRowId(null);
        setEditFormData({});
      }
    } catch (error: any) {
      showStatus('수정 실패', error.message || '데이터 수정 중 오류가 발생했습니다.', 'error');
    }
  };

  const handleEditChange = (name: string, value: any) => {
    setEditFormData((prev: any) => ({ ...prev, [name]: value }));
  };

  // 🛡️ Pre-hydration Guard for the whole table
  if (!isMounted) {
    return (
        <div className="flex flex-col items-center justify-center p-20 bg-white border border-gray-100 rounded-[32px] min-h-[400px]">
            <SafeIcon icon={Loader2} isMounted={true} size={48} className="animate-spin text-slate-200" />
            <p className="mt-4 text-[10px] font-black text-slate-300 uppercase tracking-widest animate-pulse">Initializing Table Engine...</p>
        </div>
    );
  }

  return (
    <div className="space-y-6 animate-in fade-in duration-500">
      <div className="flex flex-col md:flex-row gap-6 justify-between items-center bg-white p-6 rounded-[32px] border border-slate-100 shadow-xl shadow-slate-900/5">
        <div className="relative w-full md:w-96 group">
          <SafeIcon icon={Search} isMounted={isMounted} className="absolute left-5 top-1/2 -translate-y-1/2 text-slate-400 group-focus-within:text-blue-500 transition-colors" size={20} />
          <input 
            type="text" 
            placeholder="Search within records..."
            className="w-full pl-12 pr-6 py-3.5 bg-slate-50 border border-slate-100 rounded-2xl text-sm focus:bg-white focus:ring-4 focus:ring-blue-500/5 focus:border-blue-500 outline-none transition-all placeholder:text-slate-400 font-bold"
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
          />
        </div>

        <div className="flex items-center gap-3">
            {hasBaseEditAuth && (onToggleAddRecord || onToggleBulkUpload || onToggleAIImport) && (
              <div className="flex items-center gap-3 mr-3 border-r pr-6 border-slate-100">
                {onToggleAddRecord && (
                  <button onClick={onToggleAddRecord} className="flex items-center gap-2 px-6 py-3.5 bg-blue-600 text-white font-black rounded-2xl hover:bg-blue-700 transition-all shadow-xl shadow-blue-500/20 active:scale-95 text-xs uppercase tracking-widest whitespace-nowrap">
                    <SafeIcon icon={Plus} isMounted={isMounted} size={16} strokeWidth={3} /> Add Record
                  </button>
                )}
                {onToggleBulkUpload && (
                  <button onClick={onToggleBulkUpload} className="flex items-center gap-2 px-6 py-3.5 bg-slate-900 text-white font-black rounded-2xl hover:bg-blue-600 transition-all shadow-xl shadow-slate-900/10 active:scale-95 text-xs uppercase tracking-widest whitespace-nowrap">
                    <SafeIcon icon={FileSpreadsheet} isMounted={isMounted} size={16} /> Bulk Upload
                  </button>
                )}
                {onToggleAIImport && (
                  <button onClick={onToggleAIImport} className="flex items-center gap-2 px-6 py-3.5 bg-indigo-600 text-white font-black rounded-2xl hover:bg-indigo-700 shadow-xl shadow-indigo-500/10 active:scale-95 text-xs uppercase tracking-widest group whitespace-nowrap">
                    <SafeIcon icon={Sparkles} isMounted={isMounted} size={16} className="text-yellow-300 group-hover:scale-110 transition-transform" /> AI Photo
                  </button>
                )}
              </div>
            )}

            <div className="relative">
                <button
                    onClick={() => setIsExportingMenuOpen(!isExportingMenuOpen)}
                    className="flex items-center gap-2 px-6 py-3.5 bg-white text-slate-600 font-black rounded-2xl border border-slate-100 hover:bg-slate-50 hover:border-slate-200 transition-all text-xs uppercase tracking-widest active:scale-95 shadow-lg shadow-slate-900/5"
                >
                    <SafeIcon icon={FileDown} isMounted={isMounted} size={16} /> Export
                </button>
                {isExportingMenuOpen && (
                    <div className="absolute right-0 mt-3 w-56 bg-white border border-slate-100 rounded-[24px] shadow-2xl z-20 overflow-hidden animate-in fade-in slide-in-from-top-2 border-slate-200/50">
                        <button onClick={exportToExcel} className="w-full px-6 py-4 text-left text-xs font-black text-slate-600 hover:bg-green-50 hover:text-green-700 flex items-center gap-3 border-b border-slate-50 transition-colors">
                            <SafeIcon icon={TableIcon} isMounted={isMounted} size={16} /> 엑셀 파일 (.xlsx)
                        </button>
                        <button onClick={exportToCSV} className="w-full px-6 py-4 text-left text-xs font-black text-slate-600 hover:bg-blue-50 hover:text-blue-700 flex items-center gap-3 transition-colors">
                            <SafeIcon icon={FileText} isMounted={isMounted} size={16} /> CSV 파일 (.csv)
                        </button>
                    </div>
                )}
            </div>

            <button
                onClick={() => { setShowDeleted(!showDeleted); setSelectedIds([]); }}
                className={`flex items-center gap-2 px-6 py-3.5 font-black rounded-2xl border transition-all text-xs uppercase tracking-widest active:scale-95 shadow-lg ${showDeleted ? 'bg-red-50 text-red-600 border-red-200 shadow-red-500/5' : 'bg-white text-slate-500 border-slate-100 hover:bg-slate-50 hover:border-slate-200'}`}
            >
                <SafeIcon icon={Trash2} isMounted={isMounted} size={16} className={showDeleted ? 'animate-pulse' : ''} />
                {showDeleted ? 'EXIT TRASH' : '삭제 내역'}
            </button>
            
            {hasBaseEditAuth && selectedIds.length > 0 && (
               <div className="bg-blue-600 flex items-center gap-2 p-1.5 rounded-[22px] shadow-2xl shadow-blue-500/30 animate-in fade-in slide-in-from-right-4 duration-500">
                  {!showDeleted && (
                    <button onClick={() => setIsBulkEditOpen(true)} className="flex items-center gap-2 px-6 py-3 bg-white/10 text-white text-[11px] font-black rounded-xl hover:bg-white/20 active:scale-95 transition-all uppercase tracking-widest">
                        <SafeIcon icon={Edit3} isMounted={isMounted} size={14} /> Edit All
                    </button>
                  )}
                  {showDeleted ? (
                    <button onClick={handleRestoreSelected} disabled={isRestoring} className="flex items-center gap-2 px-6 py-3 bg-green-500 text-white text-[11px] font-black rounded-xl hover:bg-green-600 active:scale-95 disabled:opacity-50 transition-all uppercase tracking-widest">
                        <SafeIcon icon={RotateCcw} isMounted={isMounted} size={14} /> Restore
                    </button>
                  ) : (
                    hasBaseDeleteAuth && (
                        <button onClick={handleDeleteSelected} disabled={isDeleting} className="flex items-center gap-2 px-6 py-3 bg-red-500 text-white text-[11px] font-black rounded-xl hover:bg-red-600 active:scale-95 disabled:opacity-50 transition-all uppercase tracking-widest">
                            <SafeIcon icon={Trash2} isMounted={isMounted} size={14} /> Delete
                        </button>
                    )
                  )}
               </div>
            )}
        </div>
      </div>

      <div className="overflow-x-auto border border-slate-100 rounded-[32px] shadow-2xl shadow-slate-900/5 bg-white min-h-[400px]">
        <table className="min-w-full divide-y divide-slate-100">
          <thead className="bg-slate-50/50">
            <tr>
              {hasBaseEditAuth && (
                <th className="px-6 py-5 text-left w-12">
                  <input type="checkbox" checked={processedData.length > 0 && selectedIds.length === processedData.length} onChange={toggleSelectAll} className="w-5 h-5 rounded border-slate-300 text-blue-600 cursor-pointer transition-all focus:ring-blue-500" />
                </th>
              )}
              {columns.map((col) => (
                <th key={col.name} onClick={() => toggleSort(col.name)} className={`px-6 py-5 text-left text-[11px] font-black uppercase tracking-widest cursor-pointer group transition-all whitespace-nowrap ${sortConfig.key === col.name ? 'text-blue-600' : 'text-slate-400 hover:text-slate-600'}`}>
                  <div className="flex items-center gap-2">
                    {col.name}
                    <span className={`transition-all ${sortConfig.key === col.name ? 'opacity-100' : 'opacity-0 group-hover:opacity-100'}`}>
                        {sortConfig.key === col.name ? (sortConfig.direction === 'asc' ? <SafeIcon icon={ArrowUp} isMounted={isMounted} size={12} /> : <SafeIcon icon={ArrowDown} isMounted={isMounted} size={12} />) : <SafeIcon icon={ArrowUpDown} isMounted={isMounted} size={12} />}
                    </span>
                  </div>
                </th>
              ))}
              {hasBaseEditAuth && <th className="px-6 py-5 text-center text-[11px] font-black uppercase tracking-widest text-slate-400 w-24">Actions</th>}
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-50">
            {paginatedData.map((row, rowIndex) => (
              <tr key={row.id || rowIndex} className={`hover:bg-blue-50/30 transition-colors group ${selectedIds.includes(row.id) ? 'bg-blue-50/50' : ''} ${row.isDeleted ? 'bg-red-50/10 opacity-70' : ''}`}>
                {hasBaseEditAuth && (
                  <td className="px-6 py-4">
                    {isRowManager(row) && <input type="checkbox" checked={selectedIds.includes(row.id)} onChange={() => toggleSelectRow(row.id)} className="w-5 h-5 rounded border-slate-300 text-blue-600 cursor-pointer transition-all focus:ring-blue-500" />}
                  </td>
                )}
                {columns.map((col) => {
                  const val = row[col.name];
                  const isEditing = editingRowId === row.id;
                  if (isEditing) {
                    if (col.isAutoGenerated) return <td key={col.name} className="px-6 py-4"><span className="text-[10px] font-black text-blue-500 bg-blue-50 px-3 py-1.5 rounded-xl border border-blue-100 uppercase tracking-widest">{row[col.name]}</span></td>;
                    return <td key={col.name} className="px-4 py-2"><input type={col.type === 'date' ? 'date' : (col.type === 'number' ? 'number' : 'text')} value={col.type === 'date' && typeof editFormData[col.name] === 'number' ? new Date(Math.round((editFormData[col.name] - 25569) * 86400 * 1000)).toISOString().split('T')[0] : (editFormData[col.name] || '')} onChange={(e) => handleEditChange(col.name, e.target.value)} className="w-full bg-slate-50 border border-slate-200 rounded-xl px-4 py-2.5 text-xs font-bold text-slate-700 focus:bg-white focus:ring-4 focus:ring-blue-500/5 focus:border-blue-500 outline-none transition-all" /></td>;
                  }
                  
                  let displayValue = val?.toString() || '-';
                  if (col.type === 'boolean') {
                    return (
                        <td key={col.name} className="px-6 py-4 whitespace-nowrap">
                          {val === 'Yes' ? (
                            <span className="flex items-center gap-1.5 text-blue-600 font-bold text-[10px] bg-blue-50 px-3 py-1.5 rounded-full border border-blue-100 uppercase tracking-widest">
                              <SafeIcon icon={CheckCircle2} isMounted={isMounted} size={12} /> YES
                            </span>
                          ) : val === 'No' ? (
                            <span className="flex items-center gap-1.5 text-red-500 font-bold text-[10px] bg-red-50 px-3 py-1.5 rounded-full border border-red-100 uppercase tracking-widest">
                              <SafeIcon icon={XCircle} isMounted={isMounted} size={12} /> NO
                            </span>
                          ) : <span className="text-slate-300">-</span>}
                        </td>
                      );
                  }
                  if (col.type === 'currency' || col.type === 'number') {
                    const numericVal = typeof val === 'number' ? val : Number(String(val || '').replace(/[^0-9.-]/g, ''));
                    const displayVal = !isNaN(numericVal) ? numericVal.toLocaleString() : (val || '-');
                    return <td key={col.name} className="px-6 py-4 text-sm font-black text-slate-900 text-right font-mono tracking-tight">{displayVal}</td>;
                  }
                  if (col.type === 'email' && val) return <td key={col.name} className="px-6 py-4"><a href={`mailto:${val}`} className="flex items-center gap-2 text-blue-600 hover:text-blue-800 transition-colors font-black text-xs decoration-2 underline-offset-4"><SafeIcon icon={Mail} isMounted={isMounted} size={12} />{val}</a></td>;
                  if (col.type === 'phone' && val) return <td key={col.name} className="px-6 py-4 text-slate-900 font-black text-xs"><div className="flex items-center gap-2 bg-slate-50 px-3 py-1 rounded-full w-fit"><SafeIcon icon={Phone} isMounted={isMounted} size={12} className="text-blue-500" />{val}</div></td>;
                  if (col.type === 'textarea' && val) return <td key={col.name} className="px-6 py-4"><div className="flex items-center gap-2 truncate max-w-[200px] text-xs font-medium text-slate-500"><SafeIcon icon={FileText} isMounted={isMounted} size={12} className="text-slate-300" />{val.toString()}</div></td>;
                  if (col.type === 'file' && val) return <td key={col.name} className="px-6 py-4"><a href={val} target="_blank" rel="noopener noreferrer" className="p-2 bg-slate-50 rounded-xl hover:bg-blue-50 transition-colors inline-block group/file"><SafeIcon icon={Eye} isMounted={isMounted} size={16} className="text-slate-400 group-hover/file:text-blue-500" /></a></td>;
                  return <td key={col.name} className={`px-6 py-4 text-xs font-bold ${col.autoPrefix ? 'text-blue-600 font-black' : 'text-slate-700'}`}>{displayValue}</td>;
                })}
                {hasBaseEditAuth && (
                  <td className="px-6 py-4 text-right">
                    {editingRowId === row.id ? (
                      <div className="flex items-center justify-center gap-2">
                        <button onClick={handleEditSave} className="p-2.5 bg-blue-600 text-white rounded-xl shadow-lg shadow-blue-500/20 active:scale-95 transition-all"><SafeIcon icon={Check} isMounted={isMounted} size={16} strokeWidth={3} /></button>
                        <button onClick={handleEditCancel} className="p-2.5 bg-slate-100 text-slate-500 rounded-xl hover:bg-slate-200 active:scale-95 transition-all"><SafeIcon icon={XIcon} isMounted={isMounted} size={16} strokeWidth={3} /></button>
                      </div>
                    ) : (
                      <div className="flex items-center justify-end gap-1 opacity-100 lg:opacity-0 lg:group-hover:opacity-100 transition-opacity">
                        <button onClick={() => setHistoryRowId(row.id)} className="p-2.5 text-slate-300 hover:text-indigo-600 hover:bg-indigo-50 rounded-xl transition-all" title="변경 이력"><SafeIcon icon={HistoryIcon} isMounted={isMounted} size={18} /></button>
                        {row.isDeleted ? (
                            isRowManager(row) && <button onClick={() => handleSingleRestore(row.id)} className="p-2.5 text-slate-300 hover:text-green-600 hover:bg-green-50 rounded-xl transition-all" title="데이터 복구"><SafeIcon icon={RotateCcw} isMounted={isMounted} size={18} /></button>
                        ) : (
                            isRowManager(row) && <button onClick={() => handleEditStart(row)} className="p-2.5 text-slate-300 hover:text-blue-600 hover:bg-blue-50 rounded-xl transition-all" title="데이터 수정"><SafeIcon icon={Edit3} isMounted={isMounted} size={18} /></button>
                        )}
                      </div>
                    )}
                  </td>
                )}
              </tr>
            ))}
            {paginatedData.length === 0 && (
              <tr><td colSpan={columns.length + 2} className="px-6 py-32 text-center"><div className="flex flex-col items-center gap-4"><div className="p-6 bg-slate-50 rounded-[32px]"><SafeIcon icon={FilterX} isMounted={isMounted} size={48} className="text-slate-200" /></div><p className="text-slate-300 font-black uppercase text-xs tracking-widest mt-2">Zero records matching current criteria</p></div></td></tr>
            )}
          </tbody>
        </table>
      </div>

      <div className="flex flex-col sm:flex-row items-center justify-between gap-6 bg-white p-6 rounded-[32px] border border-slate-100 shadow-xl shadow-slate-900/5">
        <div className="flex items-center gap-8">
          <div className="flex flex-col">
            <p className="text-xs font-black text-slate-900 uppercase tracking-widest">Total Population</p>
            <p className="text-2xl font-black text-blue-600 font-mono leading-none mt-1">{processedData.length}<span className="text-[10px] text-slate-300 ml-1">RECORDS</span></p>
          </div>
          {isReadOnly && <span className="px-4 py-1.5 bg-amber-50 text-amber-600 border border-amber-100 rounded-full text-[10px] font-black uppercase tracking-[0.2em] shadow-sm animate-pulse">Read-Only Mode</span>}
        </div>
        <div className="flex items-center gap-3">
            <button onClick={() => setCurrentPage(1)} disabled={currentPage === 1} className="p-3 bg-slate-50 text-slate-400 rounded-2xl hover:bg-slate-100 hover:text-slate-600 disabled:opacity-30 transition-all active:scale-90 border border-slate-100/50"><SafeIcon icon={ChevronsLeft} isMounted={isMounted} size={18} /></button>
            <button onClick={() => setCurrentPage(prev => Math.max(1, prev - 1))} disabled={currentPage === 1} className="p-3 bg-slate-50 text-slate-400 rounded-2xl hover:bg-slate-100 hover:text-slate-600 disabled:opacity-30 transition-all active:scale-90 border border-slate-100/50"><SafeIcon icon={ChevronLeft} isMounted={isMounted} size={18} /></button>
            
            <div className="flex items-center px-4 py-2.5 bg-slate-900 rounded-2xl shadow-xl shadow-slate-900/20 min-w-[100px] justify-center">
                <span className="text-xs font-black text-white tracking-widest">{currentPage} <span className="text-slate-500 mx-1">/</span> {totalPages || 1}</span>
            </div>
            
            <button onClick={() => setCurrentPage(prev => Math.min(totalPages, prev + 1))} disabled={currentPage === totalPages || totalPages === 0} className="p-3 bg-slate-50 text-slate-400 rounded-2xl hover:bg-slate-100 hover:text-slate-600 disabled:opacity-30 transition-all active:scale-90 border border-slate-100/50"><SafeIcon icon={ChevronRight} isMounted={isMounted} size={18} /></button>
            <button onClick={() => setCurrentPage(totalPages)} disabled={currentPage === totalPages || totalPages === 0} className="p-3 bg-slate-50 text-slate-400 rounded-2xl hover:bg-slate-100 hover:text-slate-600 disabled:opacity-30 transition-all active:scale-90 border border-slate-100/50"><SafeIcon icon={ChevronsRight} isMounted={isMounted} size={18} /></button>
        </div>
      </div>

      {isBulkEditOpen && (
        <BulkEditModal 
            isOpen={isBulkEditOpen} 
            onClose={() => setIsBulkEditOpen(false)} 
            reportId={reportId}
            selectedIds={selectedIds}
            columns={columns}
            onSuccess={() => {
                setSelectedIds([]);
                showStatus('일괄 수정 완료', '선택한 데이터가 성공적으로 수정되었습니다.', 'success');
            }}
        />
      )}

      {historyRowId && (
        <AuditHistoryModal 
            isOpen={!!historyRowId} 
            onClose={() => setHistoryRowId(null)} 
            rowId={historyRowId} 
        />
      )}

      {localModalStatus.isOpen && (
        <StatusModal
            isOpen={localModalStatus.isOpen}
            onClose={() => setLocalModalStatus(prev => ({ ...prev, isOpen: false }))}
            title={localModalStatus.title}
            message={localModalStatus.message}
            type={localModalStatus.type}
        />
      )}
    </div>
  );
}
