'use client';

import React from 'react';
import { ChevronDown, Loader2, Check, Upload, X, Phone, Mail, FileText, Type } from 'lucide-react';
import { uploadFileAction } from '@/app/actions';

interface Column {
  name: string;
  type: string;
  isAutoGenerated?: boolean;
  isRequired?: boolean;
  options?: string[];
  autoPrefix?: string;
  description?: string;
}

interface DynamicFormProps {
  columns: Column[];
  initialData?: any;
  onSubmit: (data: any) => Promise<void>;
  onCancel?: () => void;
  onStatusShow?: (title: string, message: string, type: 'success' | 'error' | 'info') => void;
}

export default function DynamicForm({ columns, initialData = {}, onSubmit, onCancel, onStatusShow }: DynamicFormProps) {
  const [formData, setFormData] = React.useState(initialData);
  const [isSubmitting, setIsSubmitting] = React.useState(false);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
    const { name, value, type } = e.target as any;
    setFormData((prev: any) => ({
      ...prev,
      [name]: type === 'number' ? (value === '' ? '' : Number(value)) : value,
    }));
  };

  const handleFileChange = async (fieldName: string, file: File) => {
    const formDataObj = new FormData();
    formDataObj.append('file', file);
    try {
        const result = await uploadFileAction(formDataObj);
        setFormData((prev: any) => ({ ...prev, [fieldName]: result.url }));
        if (onStatusShow) onStatusShow('업로드 성공', '파일이 업로드되었습니다.', 'success');
    } catch (error) {
        if (onStatusShow) onStatusShow('업로드 실패', '파일 업로드 중 오류가 발생했습니다.', 'error');
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    // 최종 유효성 검사
    for (const col of columns) {
        if (col.isAutoGenerated) continue;
        const val = formData[col.name];

        if (col.isRequired && (val === undefined || val === null || val === '')) {
            if (onStatusShow) onStatusShow('입력 누락', `'${col.name}' 필드는 필수 입력 항목입니다.`, 'error');
            else alert(`'${col.name}' 필드는 필수 입력 항목입니다.`);
            return;
        }

        const isNumericType = col.type === 'number' || col.type === 'currency';
        if (isNumericType && val !== '' && val !== undefined && isNaN(Number(val?.toString().replace(/[,₩$¥€]/g, '')))) {
            if (onStatusShow) onStatusShow('형식 오류', `'${col.name}' 필드에는 숫자만 입력 가능합니다.`, 'error');
            else alert(`'${col.name}' 필드에는 숫자만 입력 가능합니다.`);
            return;
        }

        if (col.type === 'email' && val && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(val)) {
            if (onStatusShow) onStatusShow('형식 오류', '올바른 이메일 형식이 아닙니다.', 'error');
            return;
        }

        if (col.type === 'phone' && val && !/^[\d\+\-\s]+$/.test(val)) {
            if (onStatusShow) onStatusShow('형식 오류', '올바른 전화번호 형식이 아닙니다.', 'error');
            return;
        }
    }

    setIsSubmitting(true);
    try {
        await onSubmit(formData);
        // 저장 성공 시에만 입력 필드 초기화
        setFormData(initialData);
    } catch (error) {
        // 에러는 부모(ReportDataEditor)에서 모달로 보여주므로 여기서는 폼 데이터만 유지
        console.error('제출 중 오류 발생:', error);
    } finally {
        setIsSubmitting(false);
    }
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-6 bg-white p-8 border rounded-xl shadow-sm">
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {columns.map((col) => {
          const val = formData[col.name];
          const isNumericType = col.type === 'number' || col.type === 'currency';
          const isInvalidType = isNumericType && val !== '' && val !== undefined && isNaN(Number(val?.toString().replace(/[,₩$¥€]/g, '')));
          
          return (
            <div key={col.name} className={`flex flex-col gap-2 ${col.isAutoGenerated ? 'opacity-70' : ''}`}>
              <label htmlFor={col.name} className="text-sm font-semibold text-gray-700 flex items-center justify-between">
                <span className="flex items-center gap-1.5 min-w-0">
                  <span className="truncate">{col.name}</span>
                  {col.isRequired && !col.isAutoGenerated && <span className="text-red-500">*</span>}
                  {!col.isAutoGenerated && (
                      <span className={`
                        text-[8px] font-black px-1.5 py-0.5 rounded border uppercase tracking-tighter shrink-0
                        ${col.type === 'number' || col.type === 'currency' ? 'bg-blue-50 text-blue-600 border-blue-100' : 
                          col.type === 'date' ? 'bg-green-50 text-green-600 border-green-100' : 
                          col.type === 'select' || col.type === 'boolean' ? 'bg-purple-50 text-purple-600 border-purple-100' :
                          col.type === 'file' ? 'bg-orange-50 text-orange-600 border-orange-100' :
                          'bg-gray-50 text-gray-500 border-gray-200'}
                      `}>
                        {col.type}
                      </span>
                  )}
                </span>
                {col.isAutoGenerated && <span className="text-[10px] font-black text-indigo-500 bg-indigo-50 px-2 py-0.5 rounded-md">AUTO_KEY</span>}
              </label>

              <div className="relative flex flex-col gap-2">
                <div className="flex items-stretch relative">
                  {col.type === 'currency' && (
                      <select 
                        className="bg-gray-50 border border-r-0 border-gray-200 rounded-l-lg px-2 text-xs font-bold text-gray-500 outline-none focus:ring-0 appearance-none cursor-pointer hover:bg-gray-100 transition-colors"
                        onChange={(e) => {
                            const symbol = e.target.value;
                            const currentVal = formData[col.name]?.toString() || '';
                            const cleanVal = currentVal.replace(/^[₩$¥€]\s?/, '');
                            setFormData((prev: any) => ({ ...prev, [col.name]: `${symbol} ${cleanVal}`.trim() }));
                        }}
                        defaultValue="₩"
                      >
                          <option value="₩">₩</option>
                          <option value="$">$</option>
                          <option value="€">€</option>
                          <option value="¥">¥</option>
                      </select>
                  )}

                  {(col.type === 'email' || col.type === 'phone') && (
                      <div className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400 z-10">
                          {col.type === 'email' ? <Mail size={14} /> : <Phone size={14} />}
                      </div>
                  )}

                  {col.type === 'select' ? (
                      <div className="relative w-full">
                          <select
                            id={col.name}
                            name={col.name}
                            value={formData[col.name] || ''}
                            onChange={handleChange}
                            className="w-full px-4 py-2 border border-gray-200 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-none transition-all font-medium appearance-none bg-white cursor-pointer hover:bg-gray-50"
                          >
                              <option value="">선택하세요</option>
                              {col.options?.map(opt => <option key={opt} value={opt}>{opt}</option>)}
                          </select>
                          <ChevronDown size={14} className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400 pointer-events-none" />
                      </div>
                  ) : col.type === 'boolean' ? (
                      <div className="flex items-center gap-2 bg-gray-50 p-1 rounded-xl border border-gray-100 w-full">
                          <button
                            type="button"
                            onClick={() => setFormData((prev: any) => ({ ...prev, [col.name]: 'Yes' }))}
                            className={`flex-1 flex items-center justify-center gap-2 py-1.5 rounded-lg text-xs font-black transition-all ${val === 'Yes' ? 'bg-white text-blue-600 shadow-sm' : 'text-gray-400 hover:text-gray-600'}`}
                          >
                              <Check size={14} /> 예 (Yes)
                          </button>
                          <button
                            type="button"
                            onClick={() => setFormData((prev: any) => ({ ...prev, [col.name]: 'No' }))}
                            className={`flex-1 flex items-center justify-center gap-2 py-1.5 rounded-lg text-xs font-black transition-all ${val === 'No' ? 'bg-white text-red-600 shadow-sm' : 'text-gray-400 hover:text-gray-600'}`}
                          >
                              <X size={14} /> 아니오 (No)
                          </button>
                      </div>
                  ) : col.type === 'textarea' ? (
                      <textarea
                        id={col.name}
                        name={col.name}
                        value={formData[col.name] || ''}
                        onChange={(e: any) => handleChange(e)}
                        className="w-full px-4 py-2 border border-gray-200 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-none transition-all font-medium min-h-[100px] resize-none"
                        placeholder={`${col.name} 내용을 입력하세요...`}
                      />
                  ) : col.type === 'file' ? (
                      <div className="w-full flex flex-col gap-2">
                          <label className="flex items-center justify-center gap-2 w-full py-8 border-2 border-dashed border-gray-200 rounded-xl cursor-pointer hover:bg-gray-50 hover:border-blue-400 transition-all text-gray-400 hover:text-blue-500 group">
                              <input 
                                type="file" 
                                className="hidden" 
                                onChange={(e) => e.target.files?.[0] && handleFileChange(col.name, e.target.files[0])} 
                              />
                              <Upload size={20} className="group-hover:scale-110 transition-transform" />
                              <span className="text-xs font-bold">{val ? '파일 변경하기' : '파일 업로드 (이미지/문서)'}</span>
                          </label>
                          {val && (
                              <div className="flex items-center gap-3 p-3 bg-blue-50 rounded-xl border border-blue-100 animate-in fade-in zoom-in duration-300">
                                  {val.match(/\.(jpg|jpeg|png|gif|webp)$/i) ? (
                                      <img src={val} alt="Preview" className="w-12 h-12 rounded-lg object-cover shadow-sm bg-white" />
                                  ) : (
                                      <div className="w-12 h-12 rounded-lg bg-white flex items-center justify-center shadow-sm"><FileText size={20} className="text-blue-500" /></div>
                                  )}
                                  <div className="flex-1 min-w-0">
                                      <p className="text-[10px] font-black text-blue-600 uppercase">Attached File</p>
                                      <p className="text-xs font-medium text-gray-700 truncate">{val.split('/').pop()}</p>
                                  </div>
                                  <button type="button" onClick={() => setFormData((prev: any) => ({ ...prev, [col.name]: '' }))} className="text-gray-400 hover:text-red-500"><X size={16} /></button>
                              </div>
                          )}
                      </div>
                  ) : (
                      <input
                        id={col.name}
                        name={col.name}
                        type={col.type === 'date' ? 'date' : 'text'}
                        value={
                            col.isAutoGenerated 
                            ? (formData[col.name] || (col.autoPrefix ? `${col.autoPrefix}000000` : '자동 생성')) 
                            : (col.type === 'currency' 
                               ? (formData[col.name]?.toString().replace(/^[₩$¥€]\s?/, '') || '') 
                               : (formData[col.name] || ''))
                        }
                        onChange={(e) => {
                            if (col.type === 'currency') {
                                const val = e.target.value;
                                const existingSymbol = formData[col.name]?.toString().match(/^[₩$¥€]/)?.[0] || '₩';
                                setFormData((prev: any) => ({ ...prev, [col.name]: `${existingSymbol} ${val}`.trim() }));
                            } else {
                                handleChange(e);
                            }
                        }}
                        readOnly={col.isAutoGenerated}
                        className={`
                           w-full px-4 py-2 border rounded-lg transition-all
                           ${col.type === 'currency' ? 'rounded-l-none' : ''}
                           ${(col.type === 'email' || col.type === 'phone') ? 'pl-10' : ''}
                           ${col.isAutoGenerated ? 'bg-gray-50 text-gray-400 border-gray-100 cursor-not-allowed' : 
                             isInvalidType ? 'border-red-500 bg-red-50 focus:ring-red-500' : 'focus:ring-2 focus:ring-blue-500 focus:border-blue-500 border-gray-200'}
                        `}
                        placeholder={col.isAutoGenerated ? '자동으로 부여되는 고유키입니다' : `${col.name} 입력`}
                        required={col.isRequired && !col.isAutoGenerated}
                      />
                  )}
                </div>
                {isInvalidType && (
                    <p className="text-[10px] font-bold text-red-500 flex items-center gap-1 animate-in fade-in slide-in-from-top-1">
                        <span className="bg-red-500 text-white rounded-full w-3 h-3 flex items-center justify-center text-[8px]">!</span>
                        숫자 데이터만 입력 가능합니다.
                    </p>
                )}
              </div>
            </div>
          );
        })}
      </div>
      <div className="flex justify-end gap-3 pt-4 border-t">
        {onCancel && (
          <button
            type="button"
            onClick={onCancel}
            className="px-6 py-2 text-sm font-medium text-gray-600 bg-gray-100 rounded-lg hover:bg-gray-200 transition-colors"
          >
            취소
          </button>
        )}
        <button
          type="submit"
          disabled={isSubmitting}
          className="px-6 py-2 text-sm font-medium text-white bg-blue-600 rounded-lg hover:bg-blue-700 shadow-md transition-colors disabled:opacity-50 flex items-center gap-2"
        >
          {isSubmitting ? (
              <>
                <Loader2 size={16} className="animate-spin" />
                처리 중...
              </>
          ) : '저장하기'}
        </button>
      </div>
    </form>
  );
}
