'use client';

import React, { useState } from 'react';
import { ColumnDefinition } from '@/lib/excel-parser';
import { GripVertical, Check, X, AlertCircle, Edit3, Save, Trash2, Plus } from 'lucide-react';
import { updateReportSchemaAction, getSchemaRecommendationAction } from '@/app/actions';
import { ColumnRecommendation } from '@/lib/ai-vision';

interface SchemaEditorProps {
  reportId: string;
  initialColumns: ColumnDefinition[];
  onClose: () => void;
}

export default function SchemaEditor({ reportId, initialColumns, onClose }: SchemaEditorProps) {
  const [columns, setColumns] = useState<ColumnDefinition[]>(initialColumns);
  const [dragIndex, setDragIndex] = useState<number | null>(null);
  const [isSaving, setIsSaving] = useState(false);
  const [isRecommending, setIsRecommending] = useState(false);
  const [highlightedIndices, setHighlightedIndices] = useState<Set<number>>(new Set());
  const [rawOptionInputs, setRawOptionInputs] = useState<Record<number, string>>(() => {
    const initial: Record<number, string> = {};
    initialColumns.forEach((col, idx) => {
      if (col.options) initial[idx] = col.options.join(', ');
    });
    return initial;
  });

  const handleUpdateName = (index: number, name: string) => {
    const updated = [...columns];
    updated[index] = { ...updated[index], name };
    setColumns(updated);
  };

  const handleToggleRequired = (index: number) => {
    if (columns[index].isAutoGenerated) return;
    const updated = [...columns];
    updated[index] = { ...updated[index], isRequired: !updated[index].isRequired };
    setColumns(updated);
  };

  const handleToggleUnique = (index: number) => {
    if (columns[index].isAutoGenerated) return;
    const updated = [...columns];
    updated[index] = { ...updated[index], isUnique: !updated[index].isUnique };
    setColumns(updated);
  };

  const handleDeleteColumn = (index: number) => {
    if (columns[index].isAutoGenerated) return;
    if (confirm('이 필드를 삭제하시겠습니까? (기존 데이터는 유지되지만 화면에 표시되지 않습니다)')) {
        const updated = columns.filter((_, i) => i !== index);
        setColumns(updated);
    }
  };

  const handleAddColumn = () => {
    const newField: ColumnDefinition = {
        name: `새 필드 ${columns.length + 1}`,
        type: 'string',
        isRequired: false
    };
    setColumns([...columns, newField]);
  };

  // Drag and Drop
  const onDragStart = (index: number) => setDragIndex(index);
  const onDragOver = (e: React.DragEvent, index: number) => {
    e.preventDefault();
    if (dragIndex === null || dragIndex === index) return;
    
    const newColumns = [...columns];
    const item = newColumns[dragIndex];
    newColumns.splice(dragIndex, 1);
    newColumns.splice(index, 0, item);
    setDragIndex(index);
    setColumns(newColumns);
  };

  const handleRecommendSchema = async () => {
    setIsRecommending(true);
    setHighlightedIndices(new Set());
    try {
      const recommended = await getSchemaRecommendationAction(reportId);
      const newColumns = [...columns];
      const newHighlights = new Set<number>();
      const newRawOptions = { ...rawOptionInputs };

      recommended.forEach((rec: any) => {
        const idx = newColumns.findIndex(c => c.name === rec.name);
        if (idx !== -1 && !newColumns[idx].isAutoGenerated) {
          // 변경 사항이 있는 경우에만 하이라이트
          if (
            newColumns[idx].type !== rec.type || 
            newColumns[idx].isRequired !== rec.isRequired ||
            JSON.stringify(newColumns[idx].options) !== JSON.stringify(rec.options)
          ) {
            newColumns[idx] = { 
              ...newColumns[idx], 
              type: rec.type, 
              isRequired: rec.isRequired,
              isUnique: rec.isUnique ?? newColumns[idx].isUnique,
              options: rec.options,
              autoPrefix: rec.autoPrefix || newColumns[idx].autoPrefix,
              description: rec.reason || newColumns[idx].description
            };
            newHighlights.add(idx);
            if (rec.options) {
              newRawOptions[idx] = rec.options.join(', ');
            }
          }
        }
      });

      setColumns(newColumns);
      setRawOptionInputs(newRawOptions);
      setHighlightedIndices(newHighlights);

      // 3초 후 하이라이트 제거
      setTimeout(() => setHighlightedIndices(new Set()), 3000);
    } catch (error) {
      alert('AI 추천 중 오류가 발생했습니다.');
    } finally {
      setIsRecommending(false);
    }
  };

  const handleSave = async () => {
    setIsSaving(true);
    try {
      await updateReportSchemaAction(reportId, columns);
      onClose();
    } catch (error) {
      alert('설정 저장 중 오류가 발생했습니다.');
    } finally {
      setIsSaving(false);
    }
  };

  return (
    <div className="fixed inset-0 bg-black/60 backdrop-blur-sm z-[1000] flex items-center justify-center p-4 overflow-y-auto">
      <div className="bg-white w-full max-w-2xl rounded-[32px] shadow-2xl overflow-hidden animate-in fade-in zoom-in duration-300 max-h-[90vh] flex flex-col my-auto">
        <div className="bg-gray-50 px-8 py-6 border-b flex items-center justify-between shrink-0">
            <div>
                <h3 className="text-xl font-black text-gray-900 tracking-tight">테이블 구조 수정</h3>
                <p className="text-gray-400 text-xs font-bold mt-0.5 uppercase tracking-wider">Configure schema for this database</p>
            </div>
            <div className="flex items-center gap-3">
                <button 
                  onClick={handleRecommendSchema}
                  disabled={isRecommending || isSaving}
                  className="px-4 py-2 bg-gradient-to-r from-purple-600 to-blue-600 text-white text-xs font-black rounded-xl hover:shadow-lg hover:shadow-blue-200 active:scale-95 disabled:opacity-50 transition-all flex items-center gap-2"
                >
                  {isRecommending ? <span className="w-3 h-3 border-2 border-white/30 border-t-white rounded-full animate-spin" /> : '✨'}
                  AI 속성 추천
                </button>
                <button onClick={onClose} className="p-2 hover:bg-white hover:shadow-md rounded-xl transition-all">
                    <X size={20} className="text-gray-400" />
                </button>
            </div>
        </div>

        <div className="p-8 overflow-y-auto flex-1 space-y-3 custom-scrollbar">
            {columns.map((col, idx) => (
                <div 
                  key={idx}
                  draggable
                  onDragStart={() => onDragStart(idx)}
                  onDragOver={(e) => onDragOver(e, idx)}
                  onDragEnd={() => setDragIndex(null)}
                  className={`
                    flex items-center gap-4 p-4 rounded-2xl border-2 transition-all group relative
                    ${dragIndex === idx ? 'opacity-30 border-dashed border-blue-400' : 'bg-white border-gray-100 hover:border-blue-100 hover:shadow-sm'}
                    ${highlightedIndices.has(idx) ? 'ring-4 ring-blue-400/20 border-blue-400 shadow-xl shadow-blue-100' : ''}
                  `}
                >
                    <div className="cursor-grab text-gray-300 hover:text-gray-500"><GripVertical size={20} /></div>
                    
                    <div className="flex-1 flex flex-col gap-1 min-w-0">
                        <div className="flex items-center gap-2">
                             <input 
                               type="text" 
                               value={col.name} 
                               onChange={(e) => handleUpdateName(idx, e.target.value)}
                               className="font-black text-sm text-gray-900 bg-transparent border-b-2 border-transparent focus:border-blue-500 outline-none w-full"
                             />
                             <Edit3 size={12} className="text-gray-200 opacity-0 group-hover:opacity-100" />
                        </div>
                        
                        {col.description && (
                            <p className="text-[10px] text-blue-500 font-bold animate-in fade-in duration-500">✨ {col.description}</p>
                        )}

                        {/* 엑스트라 설정 (Select 타입인 경우) */}
                        {col.type === 'select' && (
                            <div className="mt-2 p-3 bg-gray-50 rounded-xl border border-gray-100 animate-in slide-in-from-top-1 duration-200">
                                <label className="text-[10px] font-black text-blue-600 uppercase mb-1 block">목록 옵션 (쉼표로 구분)</label>
                                <input 
                                    type="text"
                                    placeholder="예: 사과, 바나나, 포도"
                                    className="w-full bg-white border border-gray-200 rounded-lg px-3 py-1.5 text-xs outline-none focus:border-blue-400 font-medium"
                                    value={rawOptionInputs[idx] ?? ''}
                                    onChange={(e) => {
                                        const val = e.target.value;
                                        setRawOptionInputs(prev => ({ ...prev, [idx]: val }));
                                        const updated = [...columns];
                                        updated[idx] = { 
                                            ...updated[idx], 
                                            options: val.split(',').map(s => s.trim()).filter(s => !!s) 
                                        };
                                        setColumns(updated);
                                    }}
                                />
                            </div>
                        )}

                        {col.type === 'auto' && (
                            <div className="mt-2 p-3 bg-gray-50 rounded-xl border border-gray-100 animate-in slide-in-from-top-1 duration-200">
                                <label className="text-[10px] font-black text-blue-600 uppercase mb-1 block">자동 번호 접두어 (Prefix)</label>
                                <input 
                                    type="text"
                                    placeholder="예: INV-"
                                    className="w-full bg-white border border-gray-200 rounded-lg px-3 py-1.5 text-xs outline-none focus:border-blue-400 font-medium uppercase"
                                    value={col.autoPrefix || ''}
                                    onChange={(e) => {
                                        const updated = [...columns];
                                        updated[idx] = { ...updated[idx], autoPrefix: e.target.value.toUpperCase() };
                                        setColumns(updated);
                                    }}
                                />
                            </div>
                        )}
                        
                        <p className="text-[10px] font-bold text-gray-400 truncate tracking-tight mt-1">Source ID: {col.isAutoGenerated ? 'SYSTEM' : col.name}</p>
                    </div>

                    <div className="flex items-center gap-2">
                        <select 
                            value={col.type} 
                            onChange={(e) => {
                                const updated = [...columns];
                                updated[idx] = { ...updated[idx], type: e.target.value };
                                if (e.target.value === 'select' && !updated[idx].options) updated[idx].options = [];
                                if (e.target.value === 'auto' && !updated[idx].autoPrefix) updated[idx].autoPrefix = 'DID-';
                                setColumns(updated);
                            }}
                            className="text-[10px] font-black bg-gray-50 border-none rounded-md px-2 py-1 outline-none text-gray-500 cursor-pointer hover:bg-gray-100"
                        >
                            <option value="string">Text</option>
                            <option value="number">Number</option>
                            <option value="date">Date</option>
                            <option value="currency">Currency</option>
                            <option value="select">목록 선택 (Select)</option>
                            <option value="boolean">체크박스 (Checkbox)</option>
                            <option value="textarea">장문 텍스트 (TextArea)</option>
                            <option value="file">파일/이미지 첨부</option>
                            <option value="email">이메일</option>
                            <option value="phone">전화번호</option>
                            <option value="auto">자동 번호 (Auto)</option>
                        </select>

                        <button 
                          onClick={() => handleToggleUnique(idx)}
                          className={`
                            px-3 py-1.5 rounded-full text-[10px] font-black transition-all border
                            ${col.isUnique ? 'bg-blue-50 text-blue-600 border-blue-100' : 'bg-gray-100 text-gray-400 border-transparent'}
                            ${col.isAutoGenerated ? 'opacity-50 cursor-not-allowed' : 'active:scale-95'}
                          `}
                        >
                            {col.isUnique ? '고유(중복체크)' : '일반'}
                        </button>

                        <button 
                          onClick={() => handleToggleRequired(idx)}
                          className={`
                            px-3 py-1.5 rounded-full text-[10px] font-black transition-all border
                            ${col.isRequired ? 'bg-red-50 text-red-600 border-red-100' : 'bg-gray-100 text-gray-400 border-transparent'}
                            ${col.isAutoGenerated ? 'opacity-50 cursor-not-allowed' : 'active:scale-95'}
                          `}
                        >
                            {col.isRequired ? '필수' : '선택'}
                        </button>
                        
                        {!col.isAutoGenerated && (
                            <button 
                                onClick={() => handleDeleteColumn(idx)}
                                className="p-2 text-gray-300 hover:text-red-500 hover:bg-red-50 rounded-lg transition-colors"
                            >
                                <Trash2 size={16} />
                            </button>
                        )}
                    </div>
                </div>
            ))}

            <button 
                onClick={handleAddColumn}
                className="w-full flex items-center justify-center gap-2 py-4 border-2 border-dashed border-gray-100 rounded-2xl text-gray-400 hover:border-blue-300 hover:text-blue-600 hover:bg-blue-50 transition-all font-bold text-sm"
            >
                <Plus size={18} />
                새 필드 추가
            </button>
        </div>

        <div className="bg-gray-50 px-8 py-6 border-t flex items-center justify-between shrink-0">
            <p className="text-xs text-gray-400 font-medium">드래그하여 필드 순서를 변경할 수 있습니다.</p>
            <div className="flex gap-3">
                <button 
                  onClick={onClose}
                  className="px-6 py-2.5 bg-white text-gray-600 font-bold rounded-xl border border-gray-200 hover:bg-gray-100 active:scale-95 transition-all text-sm"
                >
                    취소
                </button>
                <button 
                  onClick={handleSave}
                  disabled={isSaving}
                  className="px-8 py-2.5 bg-blue-600 text-white font-black rounded-xl hover:bg-blue-700 shadow-xl shadow-blue-100 active:scale-95 disabled:opacity-50 transition-all text-sm flex items-center gap-2"
                >
                    {isSaving ? <span className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" /> : <Save size={18} />}
                    설정 저장
                </button>
            </div>
        </div>
      </div>

      <style jsx>{`
        .custom-scrollbar::-webkit-scrollbar { width: 6px; }
        .custom-scrollbar::-webkit-scrollbar-track { background: transparent; }
        .custom-scrollbar::-webkit-scrollbar-thumb { background: #e5e7eb; border-radius: 10px; }
        .custom-scrollbar::-webkit-scrollbar-thumb:hover { background: #d1d5db; }
      `}</style>
    </div>
  );
}
