// check_report_columns.js
const fetch = require('node-fetch');

async function run() {
    const API_URL = 'http://localhost:8080';
    const API_KEY = process.env.NEXT_PUBLIC_EGDESK_API_KEY || 'a87d1623-34c1-43fe-87c8-9fa8263d71a4';

    const reqAll = await fetch(`${API_URL}/user-data/tools/call`, {
        method: 'POST',
        headers: {'Content-Type': 'application/json', 'X-Api-Key': API_KEY},
        body: JSON.stringify({tool: 'user_data_query', arguments: {tableName: 'report', limit: 1000}})
    });
    const resAll = await reqAll.json();
    const reportsAll = JSON.parse(resAll.result.content[0].text).rows || [];
    
    for (const report of reportsAll) {
        if (!report.tableName) continue;
        console.log("Report:", report.name);
        const cols = JSON.parse(report.columns || "[]");
        const idCol = cols.find(c => c.isAutoGenerated);
        console.log("AutoGenerated column:", idCol ? idCol.name : "NONE!");
    }
}
run();
