const fetch = require('node-fetch');

async function run() {
    try {
        const API_URL = 'http://localhost:8080';
        const API_KEY = process.env.NEXT_PUBLIC_EGDESK_API_KEY || 'a87d1623-34c1-43fe-87c8-9fa8263d71a4';

        const q = async (name, args) => {
            const res = await fetch(`${API_URL}/user-data/tools/call`, {
                method: 'POST',
                headers: {'Content-Type': 'application/json', 'X-Api-Key': API_KEY},
                body: JSON.stringify({ tool: 'user_data_query', arguments: { tableName: name, ...args } })
            });
            const j = await res.json();
            const parsed = JSON.parse(j.result.content[0].text);
            return Array.isArray(parsed) ? parsed : (parsed.rows || []);
        }

        const reports = await q('report', { limit: 10, orderBy: 'createdAt', orderDirection: 'DESC' });
        const latest = reports.filter(r => r.tableName)[0]; 

        console.log("Checking Sync for:", latest.name, latest.tableName);

        const virtualRowsResponse = await q('report_row', { filters: { reportId: String(latest.id) }, limit: 10000 });
        const virtualList = virtualRowsResponse.filter(r => !r.isDeleted || r.isDeleted === '0' || r.isDeleted === 0 || r.isDeleted === false);
        const virtualCount = virtualList.length;

        const physicalRows = await q(latest.tableName, { limit: 10000 });
        const physicalCount = physicalRows.length;

        let idColName = null;
        const columns = JSON.parse(latest.columns);
        const idCol = columns.find(c => c.isAutoGenerated);
        if (idCol) idColName = idCol.name;

        let missingInPhysical = [];
        let missingInVirtual = [];

        if (idColName) {
            const virtualIds = new Set();
            virtualList.forEach(row => {
                const data = typeof row.data === 'string' ? JSON.parse(row.data) : row.data;
                if (data?.[idColName]) virtualIds.add(String(data[idColName]));
            });

            const physicalIds = new Set();
            physicalRows.forEach(row => {
                if (row[idColName]) physicalIds.add(String(row[idColName]));
            });

            virtualIds.forEach(id => { if (!physicalIds.has(id)) missingInPhysical.push(id); });
            physicalIds.forEach(id => { if (!virtualIds.has(id)) missingInVirtual.push(id); });
        }

        console.log("Result:", {
            virtualCount,
            physicalCount,
            missingInPhysical: missingInPhysical.slice(0, 10),
            missingInVirtual: missingInVirtual.slice(0, 10),
            idColName
        });

    } catch (e) {
        console.error(e);
    }
}
run();
