import { PrismaClient } from '@prisma/client';
import crypto from 'crypto';

const prisma = new PrismaClient();

function generateContentHash(rowData: any, columns: any[]) {
    const uniqueCols = columns.filter((c: any) => c.isUnique);
    const targetCols = uniqueCols.length > 0 ? uniqueCols : columns.filter((c: any) => !c.isAutoGenerated);
    
    const sortedKeys = targetCols.map((c: any) => c.name).sort();
    const hashSource = sortedKeys.map(key => `${key}:${rowData[key] ?? ''}`).join('|');
    
    return crypto.createHash('sha256').update(hashSource).digest('hex');
}

async function main() {
  console.log('--- 기존 정합 데이터 해시 생성을 시작합니다 ---');
  
  const reports = await prisma.report.findMany({
      include: { rows: true }
  });

  for (const report of reports) {
    const columns = JSON.parse(report.columns);
    console.log(`보고서 처리 중: ${report.name} (행: ${report.rows.length})`);

    for (const row of report.rows) {
      if (row.contentHash) continue; // 이미 해시가 있으면 건너뜀

      try {
        const rowData = JSON.parse(row.data);
        // 해시 생성 시 '데이터 ID' 등 자동 생성 필드 제외 로직이 generateContentHash 에 포함되어 있습니다.
        const hash = generateContentHash(rowData, columns);

        await prisma.reportRow.update({
          where: { id: row.id },
          data: { contentHash: hash }
        });
      } catch (e) {
        console.error(`행 ID ${row.id} 처리 중 오류 발생:`, e);
      }
    }
  }

  console.log('--- 마이그레이션이 완료되었습니다 ---');
}

main()
  .catch(e => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
