const EGDESK_CONFIG = {
  apiUrl: 'http://localhost:8080',
  apiKey: '7a406902-a90d-4aef-a983-c64320c77084',
};

async function syncVirtualFromPhysical() {
  const headers = { 'Content-Type': 'application/json', 'X-Api-Key': EGDESK_CONFIG.apiKey };
  const callRaw = async (tool, args) => {
    const res = await fetch(`${EGDESK_CONFIG.apiUrl}/user-data/tools/call`, {
      method: 'POST', headers, body: JSON.stringify({ tool, arguments: args })
    });
    const json = await res.json();
    if (!json.success) throw new Error(`Tool fail: ${json.error}`);
    return JSON.parse(json.result.content[0].text);
  };

  try {
    console.log('🔄 Starting Data Sync (Physical -> Virtual)...');

    // 1. 모든 보고서 메타데이터 조회
    const reportsRes = await callRaw('user_data_query', { tableName: 'report' });
    const reports = Array.isArray(reportsRes) ? reportsRes : (reportsRes.rows || []);

    for (const report of reports) {
      if (!report.tableName) {
          console.log(`[${report.name}] Skip: No physical table.`);
          continue;
      }

      console.log(`\n[${report.name}] Analyzing sync status...`);
      const columns = JSON.parse(report.columns);
      const idCol = columns.find(c => c.isAutoGenerated);
      const idColName = idCol ? idCol.name : null;

      // 2. 가상 테이블 행 조회 (isDeleted=0인 것들 위주로 비교)
      const virtualRes = await callRaw('user_data_query', { 
          tableName: 'report_row', 
          filters: { reportId: String(report.id) },
          limit: 10000 
      });
      const allVirtualRows = Array.isArray(virtualRes) ? virtualRes : (virtualRes.rows || []);
      const activeVirtualRows = allVirtualRows.filter(r => !r.isDeleted || r.isDeleted === '0' || r.isDeleted === 0);

      // 3. 물리적 테이블 데이터 조회
      const physicalRes = await callRaw('user_data_query', { tableName: report.tableName, limit: 10000 });
      const physicalRows = Array.isArray(physicalRes) ? physicalRes : (physicalRes.rows || []);

      console.log(`- Virtual Active: ${activeVirtualRows.length}, Physical: ${physicalRows.length}`);

      // 4. 아이디 목록 생성 (데이터 ID 기준)
      if (!idColName) {
          console.log(`[${report.name}] Error: No auto-generated ID column found. Sync aborted.`);
          continue;
      }

      const pIds = new Set(physicalRows.map(r => String(r[idColName])).filter(id => id !== 'undefined'));
      
      // 5. 가상 테이블 중 물리 테이블에 없는 행 식별 (Extra rows in Virtual)
      const rowsToSoftDelete = [];
      for (const vRow of activeVirtualRows) {
          try {
              const data = JSON.parse(vRow.data);
              const vid = String(data[idColName]);
              if (!pIds.has(vid)) {
                  rowsToSoftDelete.push(vRow.id);
              }
          } catch (e) {}
      }

      // 6. 가상 테이블 업데이트 (Soft Delete)
      if (rowsToSoftDelete.length > 0) {
          console.log(`- Marking ${rowsToSoftDelete.length} virtual rows as deleted...`);
          for (const id of rowsToSoftDelete) {
              await callRaw('user_data_update_rows', {
                  tableName: 'report_row',
                  filters: { id: String(id) },
                  updates: { isDeleted: 1, deletedAt: new Date().toISOString() }
              });
          }
          console.log(`  Done.`);
      } else {
          console.log(`- No extra virtual rows found.`);
      }

      // 7. 물리적 테이블 중 가상 테이블에 없는 행 식별 (Missing in Virtual)
      const vIds = new Set();
      activeVirtualRows.forEach(vRow => {
          try {
              const data = JSON.parse(vRow.data);
              vIds.add(String(data[idColName]));
          } catch (e) {}
      });

      const rowsToCreateInVirtual = physicalRows.filter(pRow => !vIds.has(String(pRow[idColName])));

      if (rowsToCreateInVirtual.length > 0) {
          console.log(`- Creating ${rowsToCreateInVirtual.length} missing virtual rows...`);
          const rowsToInsert = rowsToCreateInVirtual.map(pRow => ({
              id: crypto.randomUUID(),
              reportId: report.id,
              data: JSON.stringify(pRow),
              createdAt: new Date().toISOString(),
              updatedAt: new Date().toISOString(),
              isDeleted: 0,
              creatorId: 'system'
          }));
          
          await callRaw('user_data_insert_rows', {
              tableName: 'report_row',
              rows: rowsToInsert
          });
          console.log(`  Done.`);
      } else {
          console.log(`- No missing rows found in virtual.`);
      }
    }

    console.log('\n✅ Sync process completed successfully!');

  } catch (e) {
    console.error('\n❌ Sync failed:', e.message);
  }
}

syncVirtualFromPhysical();
