import { listTables, queryTable } from '../egdesk-helpers';

async function run() {
    const reportId = 'rep-something'; // We need the actual reportId, or we can just list reports.
    const reports = await queryTable('report', { limit: 10, orderBy: 'createdAt', orderDirection: 'DESC' });
    const latest = reports[0];
    
    console.log("Report:", latest.name, latest.tableName);
    
    const virtuals = await queryTable('report_row', { filters: { reportId: String(latest.id) }});
    const physical = await queryTable(latest.tableName, { limit: 10000 });
    
    const vList = virtuals.filter(r => !r.isDeleted || r.isDeleted == '0');
    console.log("Virtual count:", vList.length);
    console.log("Physical count:", physical.length);
    
    const columns = JSON.parse(latest.columns);
    const idCol = columns.find(c => c.isAutoGenerated) || columns[0];
    const idColName = idCol.name;
    
    console.log("ID col:", idColName);
    
    const vIds = vList.map(v => JSON.parse(v.data)[idColName]);
    const pIds = physical.map(p => p[idColName]);
    
    console.log("Sample V_IDs:", vIds.slice(0,3));
    console.log("Sample P_IDs:", pIds.slice(0,3));
}
run();
