const fetch = require('node-fetch');

async function run() {
    try {
        const API_URL = 'http://localhost:8080';
        const API_KEY = process.env.NEXT_PUBLIC_EGDESK_API_KEY || 'a87d1623-34c1-43fe-87c8-9fa8263d71a4';

        const q = async (name, args) => {
            const res = await fetch(`${API_URL}/user-data/tools/call`, {
                method: 'POST',
                headers: {'Content-Type': 'application/json', 'X-Api-Key': API_KEY},
                body: JSON.stringify({ tool: 'user_data_query', arguments: { tableName: name, ...args } })
            });
            return JSON.parse((await res.json()).result.content[0].text);
        }

        const reports = await q('report', { limit: 10, orderBy: 'createdAt', orderDirection: 'DESC' });
        const latest = reports.filter(r => r.tableName)[0]; // get newest physically mounted report
        
        console.log("Report:", latest.name, latest.tableName);
        
        const virtuals = await q('report_row', { filters: { reportId: String(latest.id) }, limit: 10000 });
        const physical = await q(latest.tableName, { limit: 10000 });
        
        const vList = virtuals.filter(r => !r.isDeleted || r.isDeleted == '0' || r.isDeleted == 0 || r.isDeleted === false);
        console.log("Virtual count:", vList.length);
        console.log("Physical count:", physical.length);
        
        const columns = JSON.parse(latest.columns);
        const idCol = columns.find(c => c.isAutoGenerated) || columns[0];
        const idColName = idCol.name;
        
        console.log("ID col:", idColName);
        
        const vIds = vList.map(v => {
            try {
               let data = typeof v.data === 'string' ? JSON.parse(v.data) : v.data;
               return data[idColName];
            } catch(e) { return null; }
        });
        const pIds = physical.map(p => p[idColName]);
        
        const missingInPhysical = vIds.filter(id => !pIds.includes(String(id) || id));
        const missingInVirtual = pIds.filter(id => !vIds.includes(String(id) || id));

        console.log("missingInPhysical:", missingInPhysical.length);
        console.log("missingInVirtual:", missingInVirtual.length);

    } catch (e) {
        console.error(e);
    }
}
run();
