import { NextResponse } from 'next/server';
import type { NextRequest } from 'next/server';

/**
 * EGDesk Database Proxy (Next.js 16+)
 *
 * Intercepts __user_data_proxy requests and forwards them to the EGDesk MCP server.
 * This allows CORS-free database access in both local and tunneled environments.
 *
 * Generated by @egdesk/next-api-plugin
 */
export async function proxy(request: NextRequest) {
  const { pathname } = request.nextUrl;

  // Intercept __user_data_proxy requests
  if (pathname.includes('__user_data_proxy')) {
    try {
      const body = await request.text();

      // Read API key and URL from environment
      const apiKey = process.env.NEXT_PUBLIC_EGDESK_API_KEY;
      const apiUrl = process.env.NEXT_PUBLIC_EGDESK_API_URL || 'http://localhost:8080';

      const headers: HeadersInit = {
        'Content-Type': 'application/json',
      };

      if (apiKey) {
        headers['X-Api-Key'] = apiKey;
      }

      // Forward to EGDesk MCP server
      const response = await fetch(`${apiUrl}/user-data/tools/call`, {
        method: 'POST',
        headers,
        body,
      });

      const result = await response.json();

      return NextResponse.json(result, { status: response.status });
    } catch (error: any) {
      return NextResponse.json(
        { error: 'Proxy error', message: error.message },
        { status: 500 }
      );
    }
  }

  // RBAC Authentication & Authorization Logic
  const userIdCookie = request.cookies.get('session_user_id');
  const roleCookie = request.cookies.get('session_user_role');
  const isAuthenticated = !!userIdCookie?.value;
  const role = roleCookie?.value;

  // Public Assets & Next.js internal paths: Bypass middleware
  if (
      pathname.startsWith('/_next') ||
      pathname.startsWith('/api') ||
      pathname.includes('.') ||
      pathname.includes('__user_data_proxy')
  ) {
      return NextResponse.next();
  }

  // 1. 비로그인 시 /login으로 무조건 리다이렉트
  if (!isAuthenticated && pathname !== '/login') {
      return NextResponse.redirect(new URL('/login', request.url));
  }

  // 2. 이미 로그인한 사용자가 로그인 페이지 접근 시
  if (isAuthenticated && pathname === '/login') {
      if (role === 'EMPLOYEE') {
          return NextResponse.redirect(new URL('/workspace', request.url));
      }
      return NextResponse.redirect(new URL('/', request.url));
  }

  // 3. 역할(Role) 기반 라우팅 제한
  if (isAuthenticated) {
      if (role === 'EMPLOYEE') {
          // EMPLOYEE는 오직 /workspace 하위 경로만 접근 가능
          if (!pathname.startsWith('/workspace')) {
              return NextResponse.redirect(new URL('/workspace', request.url));
          }
      }
  }

  // Continue to next proxy or route
  return NextResponse.next();
}

export const config = {
  matcher: [
    /*
     * Match all paths except static assets
     * The proxy function itself filters for __user_data_proxy
     */
    '/:path*',
  ],
};
