'use server';

import { revalidatePath } from 'next/cache';
import { 
    queryTable, 
    insertRows, 
    updateRows, 
    deleteRows
} from '@/egdesk-helpers';
import { 
    generateNumericId, 
    generateId, 
    checkReportAuthorization,
    SYSTEM_TABLES
} from './shared';
import { getSessionAction } from './auth';
import { notifyNewDataRow, notifyBulkUpload } from '@/lib/notifications';
import { triggerWorkflow } from '@/lib/workflow/engine';
import { castToPhysicalValue } from '@/lib/db-utils';
import crypto from 'crypto';

/**
 * 이력 테이블 전용 레지던트 체크 함수
 */
async function ensureHistoryTable() {
    const tableName = 'report_row_history';
    const tableDef = SYSTEM_TABLES.find(t => t.tableName === tableName);
    if (!tableDef) return;

    try {
        await queryTable(tableName, { limit: 1 });
    } catch (err: any) {
        const msg = String(err.message || err);
        if (msg.includes('no such table')) {
             const { createTable } = await import('@/egdesk-helpers');
             await createTable(tableDef.displayName, tableDef.schema, { tableName });
        }
    }
}

/**
 * 데이터 행의 중복 여부를 판단하기 위한 해시값을 생성합니다.
 */
export async function generateContentHash(rowData: any, columns: any[]) {
    const isUnique = (col: any) => col.isUnique === true || String(col.isUnique) === 'true' || Number(col.isUnique) === 1 || String(col.isUnique) === '1';
    
    const uniqueCols = columns.filter(c => isUnique(c));
    const targetCols = uniqueCols.length > 0 ? uniqueCols : columns.filter(c => !c.isAutoGenerated);
    
    const sortedKeys = targetCols.map(c => c.name).sort();
    const hashSource = sortedKeys.map(key => `${key}:${rowData[key] === undefined || rowData[key] === null ? '' : rowData[key]}`).join('|');
    
    return crypto.createHash('sha256').update(hashSource).digest('hex');
}

export async function addRowAction(reportId: string, rowData: any) {
  const user = await getSessionAction();
  if (!user) throw new Error('인증이 필요합니다.');
  
  const isAuthorized = await checkReportAuthorization(reportId, user.id, user.role);
  if (!isAuthorized) throw new Error('해당 보고서에 대한 접근 권한이 없습니다.');

  const reportsResult: any = await queryTable('report', { filters: { id: String(reportId) } });
  const reports = reportsResult.rows || reportsResult;
  const report = reports[0];
  if (!report) throw new Error('보고서를 찾을 수 없습니다.');

  const columns = JSON.parse(report.columns);
  
  const hash = await generateContentHash(rowData, columns);
  const isUnique = (col: any) => col.isUnique === true || String(col.isUnique) === 'true' || Number(col.isUnique) === 1 || String(col.isUnique) === '1';
  const uniqueCols = columns.filter((c: any) => isUnique(c));
  
  if (uniqueCols.length > 0) {
    const existingRowsResult: any = await queryTable('report_row', {
        filters: { reportId: String(reportId), contentHash: String(hash), isDeleted: '0' }
    });
    const existingRows = existingRowsResult.rows || existingRowsResult;
    
    if (existingRows.length > 0) {
        throw new Error('이미 동일한 내용의 데이터가 존재합니다. (중복 방지)');
    }
  }

  let currentSerial = 0;
  const idCol = columns.find((c: any) => c.isAutoGenerated);

  if (idCol && report.tableName) {
      try {
          const allPhysicalRows: any = await queryTable(report.tableName, { limit: 100000 });
          const rows = allPhysicalRows?.rows || allPhysicalRows || [];
          if (Array.isArray(rows)) {
              rows.forEach((r: any) => {
                  const did = r[idCol.name];
                  if (did && typeof did === 'string') {
                      const num = parseInt(did.replace(/[^0-9]/g, ''), 10);
                      if (!isNaN(num) && num > currentSerial) currentSerial = num;
                  }
              });
          }
      } catch (e) {
          console.warn("Failed to fetch physical rows for max ID:", e);
      }
  }

  if (currentSerial === 0) {
      if (report.lastSerial !== undefined && report.lastSerial !== null && Number(report.lastSerial) > 0) {
          currentSerial = Number(report.lastSerial);
      } else if (idCol) {
          try {
              const allRowsResult: any = await queryTable('report_row', { filters: { reportId: String(reportId) }, limit: 100000 });
              const allRows = allRowsResult?.rows || allRowsResult || [];
              if (Array.isArray(allRows)) {
                  allRows.forEach((r: any) => {
                      try {
                          const data = JSON.parse(r.data);
                          const did = data[idCol.name];
                          if (did && typeof did === 'string') {
                               const num = parseInt(did.replace(/[^0-9]/g, ''), 10);
                               if (!isNaN(num) && num > currentSerial) currentSerial = num;
                          }
                      } catch (e) {}
                  });
              }
          } catch (e) {}
      }
  }

  const nextSerial = (currentSerial + 1).toString().padStart(6, '0');
  const finalData = { ...rowData };
  columns.forEach((col: any) => {
    if (col.isAutoGenerated) {
        const prefix = col.autoPrefix || 'DID-';
        finalData[col.name] = `${prefix}${nextSerial}`;
    }
  });

  for (const col of columns) {
    if (col.isAutoGenerated) continue;
    const val = finalData[col.name];

    if (col.isRequired && (val === undefined || val === null || val === '')) {
        throw new Error(`'${col.name}' 필드는 필수입니다.`);
    }

    if (col.type === 'select' && col.options && val !== '' && val !== null && val !== undefined) {
      const rawOptions = col.options;
      const optionsList = Array.isArray(rawOptions) ? rawOptions : String(rawOptions).split(',').map(s => s.trim()).filter(Boolean);
      if (!optionsList.includes(String(val).trim())) {
          throw new Error(`'${col.name}' 필드의 값 '${val}'은(는) 허용된 목록(${optionsList.join(', ')})에 없습니다.`);
      }
    }

    if ((col.type === 'number' || col.type === 'currency') && val !== '' && val !== null && val !== undefined) {
        const sVal = String(val);
        const cleanVal = sVal.replace(/[^0-9.-]/g, '').trim();
        if (isNaN(Number(cleanVal))) {
            throw new Error('필드 ' + col.name + '에는 숫자만 입력 가능합니다.');
        }
        finalData[col.name] = Number(cleanVal);
    }
  }

  let syncWarning: string | undefined;
  if (report.tableName) {
      try {
        const physicalData: any = {};
        columns.forEach((col: any) => {
          physicalData[col.name] = castToPhysicalValue(finalData[col.name], col.type);
        });
        await insertRows(report.tableName, [physicalData]);
      } catch (err: any) {
        console.error(`Physical table sync failed during add (report: ${reportId}):`, err);
        syncWarning = `데이터는 저장되었지만 물리적 테이블(${report.tableName}) 반영에 실패했습니다.`;
      }
  }

  const creatorId = user.id;

  const vRes = await insertRows('report_row', [{
    id: generateNumericId(),
    reportId,
    data: JSON.stringify(finalData),
    contentHash: hash,
    creatorId: creatorId,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    isDeleted: 0
  }]);
    
  if (!vRes?.success) {
      throw new Error(`가상 테이블(report_row) 저장에 실패하여 처리가 중단되었습니다. (원인: ${vRes?.error || '알 수 없음'})`);
  }
    
  try {
      await updateRows('report', { lastSerial: currentSerial + 1 }, { filters: { id: String(reportId) } });
  } catch (err) {}
    
  notifyNewDataRow(report.name, user.fullName || user.username, finalData, columns, report.slackWebhookUrl).catch(console.error);

  await triggerWorkflow(reportId, finalData, creatorId).catch(err => {
      console.error("[Workflow Trigger Error]", err);
  });

  revalidatePath(`/report/${reportId}`);
  revalidatePath(`/report/${reportId}/input`);
  return { success: true, syncWarning };
}

export async function addRowsAction(reportId: string, rows: any[]) {
    const user = await getSessionAction();
    if (!user) throw new Error('인증이 필요합니다.');

    const isAuthorized = await checkReportAuthorization(reportId, user.id, user.role);
    if (!isAuthorized) throw new Error('해당 보고서에 대한 접근 권한이 없습니다.');

    const creatorId = user.id;

    const reports = await queryTable('report', { filters: { id: String(reportId) } });
    const report = reports[0];
    if (!report) throw new Error('보고서를 찾을 수 없습니다.');
  
    const columns = JSON.parse(report.columns);
    
    let currentSerial = 0;
    if (report.lastSerial !== undefined && report.lastSerial !== null && Number(report.lastSerial) > 0) {
        currentSerial = Number(report.lastSerial);
    } else {
        const idCol = columns.find((c: any) => c.isAutoGenerated);
        if (idCol) {
            const allRows = await queryTable('report_row', { filters: { reportId: String(reportId) }, limit: 100000 });
            let maxNum = 0;
            const rowsArray = allRows.rows || allRows;
            if (Array.isArray(rowsArray)) {
                rowsArray.forEach((r: any) => {
                    try {
                        const data = JSON.parse(r.data);
                        const did = data[idCol.name];
                        if (did && typeof did === 'string') {
                            const num = parseInt(did.replace(/[^0-9]/g, ''), 10);
                            if (!isNaN(num) && num > maxNum) maxNum = num;
                        }
                    } catch (e) {}
                });
            }
            currentSerial = maxNum;
        }
    }
    let skippedCount = 0;
    
    const rawExistingRows = await queryTable('report_row', {
        filters: { reportId: String(reportId) }
    });
    const existingRows = rawExistingRows.filter((r: any) => String(r.isDeleted) === '0');
    const existingHashes = new Set(existingRows.map((r: any) => r.contentHash).filter((h: any) => h));

    const cleanedRowsToInsert = [];
    
    for (const rowData of rows) {
        const finalData: any = {};
        columns.forEach((col: any) => {
            if (!col.isAutoGenerated) {
                finalData[col.name] = rowData[col.name];
            }
        });

        const hash = await generateContentHash(finalData, columns);
        const isUnique = (col: any) => col.isUnique === true || String(col.isUnique) === 'true' || Number(col.isUnique) === 1 || String(col.isUnique) === '1';
        const uniqueCols = columns.filter((c: any) => isUnique(c));
        
        if (uniqueCols.length > 0 && existingHashes.has(hash)) {
            skippedCount++;
            continue; 
        }
        
        const dataKey = hash;
        if (uniqueCols.length > 0 && existingHashes.has(dataKey)) {
            skippedCount++;
            continue;
        }

        let isRowDataValid = true;
        for (const col of columns) {
            if (col.isAutoGenerated) continue;
            const val = finalData[col.name];

            if (col.isRequired && (val === undefined || val === null || val === '')) {
                if (val !== 0) {
                    isRowDataValid = false;
                    break;
                }
            }

            if (col.type === 'select' && col.options && val !== '' && val !== null && val !== undefined) {
                const rawOptions = col.options;
                const optionsList = Array.isArray(rawOptions) ? rawOptions : String(rawOptions).split(',').map(s => s.trim()).filter(Boolean);
                if (!optionsList.includes(String(val).trim())) {
                    isRowDataValid = false;
                    break;
                }
            }

            if ((col.type === 'number' || col.type === 'currency') && val !== '' && val !== null && val !== undefined) {
                const sVal = String(val);
                const cleanVal = sVal.replace(/[^0-9.-]/g, '').trim();
                const numericVal = Number(cleanVal);
                if (!isNaN(numericVal)) {
                    finalData[col.name] = numericVal;
                }
            }
        }

        if (!isRowDataValid) {
            skippedCount++;
            continue;
        }

        currentSerial++;
        const nextSerial = currentSerial.toString().padStart(6, '0');
        const rowWithMetadata: any = { ...finalData };
        
        columns.forEach((col: any) => {
            if (col.isAutoGenerated) {
                rowWithMetadata[col.name] = 'DID-' + nextSerial;
            }
        });

        cleanedRowsToInsert.push({
            id: generateNumericId(),
            data: JSON.stringify(rowWithMetadata),
            contentHash: hash,
            reportId: String(reportId),
            creatorId: creatorId,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
            isDeleted: 0
        });
        
        existingHashes.add(hash);
    }

    if (cleanedRowsToInsert.length > 0) {
        if (report.tableName) {
            try {
                const physicalRows = cleanedRowsToInsert.map(r => {
                    const rowWithMetadata = JSON.parse(r.data);
                    const physicalData: any = {};
                    columns.forEach((col: any) => {
                        physicalData[col.name] = castToPhysicalValue(rowWithMetadata[col.name], col.type);
                    });
                    return physicalData;
                });
                await insertRows(report.tableName, physicalRows);
            } catch (err: any) {
                throw new Error(`물리적 테이블 데이터 일괄 삽입에 실패하였습니다. (사유: ${err.message || '알 수 없음'})`);
            }
        }

        const vRes = await insertRows('report_row', cleanedRowsToInsert);
        if (!vRes?.success) {
            throw new Error(`가상 테이블 데이터 일괄 삽입에 실패하였습니다. (사유: ${vRes?.error || '알 수 없음'})`);
        }

        try {
            await updateRows('report', { lastSerial: currentSerial }, { filters: { id: String(reportId) } });
        } catch (err) {}
    }
  
    if (cleanedRowsToInsert.length > 0) {
        const firstRowData = JSON.parse(cleanedRowsToInsert[0].data);
        notifyBulkUpload(report.name, user.fullName || user.username, cleanedRowsToInsert.length, firstRowData, columns, report.slackWebhookUrl).catch(console.error);
    }

    revalidatePath('/report/' + reportId);
    return { 
        success: true, 
        addedCount: cleanedRowsToInsert.length, 
        skippedCount 
    };
}

export async function updateSingleRowAction(reportId: string, rowId: string, newData: any) {
    try {
        const user = await getSessionAction();
        if (!user) throw new Error('인증이 필요합니다.');
        
        const isAuthorized = await checkReportAuthorization(reportId, user.id, user.role);
        if (!isAuthorized) throw new Error('해당 보고서에 대한 접근 권한이 없습니다.');

        const reports = await queryTable('report', { filters: { id: String(reportId) } });
        const report = reports[0];
        if (!report) throw new Error('보고서를 찾을 수 없습니다.');

        const columns = JSON.parse(report.columns);
        const rows = await queryTable('report_row', { filters: { id: String(rowId) } });
        const row = rows[0];
        if (!row) throw new Error('수정할 데이터를 찾을 수 없습니다.');

        const updaterId = user.id;
        if (user.role === 'VIEWER' && row.creatorId !== user.id) {
            throw new Error('본인이 작성하지 않은 데이터는 수정할 수 없습니다.');
        }

        let syncWarning: string | undefined;
        const updatedDataStr = JSON.stringify(newData);
        await updateRows('report_row', {
            data: updatedDataStr,
            updatedAt: new Date().toISOString(),
            updaterId: updaterId
        }, { filters: { id: String(rowId) } });

        try {
            await ensureHistoryTable();
            await insertRows('report_row_history', [{
                id: generateId(),
                rowId: String(rowId),
                oldData: row.data,
                newData: updatedDataStr,
                changeType: 'UPDATE',
                changedById: String(updaterId || 'system'),
                changedAt: new Date().toISOString()
            }]);
        } catch (historyErr) {
            console.error('Failed to insert update history log:', historyErr);
        }

        if (report.tableName) {
            try {
                const oldRowData = JSON.parse(row.data);
                const filters: any = {};
                const idCol = columns.find((c: any) => c.name === '데이터ID');
                let idColName = idCol ? idCol.name : null;

                if (idColName && oldRowData[idColName]) {
                    filters[idColName] = String(oldRowData[idColName]);
                } else {
                    columns.forEach((c: any) => {
                        if (oldRowData[c.name] !== undefined) {
                            filters[c.name] = String(oldRowData[c.name]);
                        }
                    });
                }

                if (Object.keys(filters).length > 0) {
                    const physicalData: any = {};
                    columns.forEach((col: any) => {
                        if (newData[col.name] !== undefined) {
                            physicalData[col.name] = castToPhysicalValue(newData[col.name], col.type);
                        }
                    });
                    await updateRows(report.tableName, physicalData, { filters });
                }
            } catch (err) {
                console.error(`Physical table sync failed during update (row: ${rowId}):`, err);
                syncWarning = `데이터는 수정되었지만 물리적 테이블(${report.tableName}) 동기화에 실패했습니다.`;
            }
        }

        revalidatePath(`/report/${reportId}`);
        return { success: true, syncWarning };
    } catch (err: any) {
        console.error('updateSingleRowAction error:', err);
        throw new Error(err.message || '데이터 수정 중 서버 오류가 발생했습니다.');
    }
}

export async function bulkUpdateRowsAction(reportId: string, rowIds: string[], fieldName: string, actionType: 'OVERWRITE' | 'FIND_REPLACE', params: { value?: any; find?: string; replace?: string }) {
    const user = await getSessionAction();
    if (!user) throw new Error('인증이 필요합니다.');
    
    const isAuthorized = await checkReportAuthorization(reportId, user.id, user.role);
    if (!isAuthorized) throw new Error('해당 보고서에 대한 접근 권한이 없습니다.');

    const reports = await queryTable('report', { filters: { id: String(reportId) } });
    const report = reports[0];
    if (!report) throw new Error('보고서를 찾을 수 없습니다.');

    const columns = JSON.parse(report.columns);
    const colDef = columns.find((c: any) => c.name === fieldName);
    if (!colDef) throw new Error('컬럼 정의를 찾을 수 없습니다.');

    let idColName: string | null = null;
    if (report.tableName) {
        const idCol = columns.find((c: any) => c.name === '데이터ID');
        if (idCol) idColName = idCol.name;
    }

    const rows = await Promise.all(rowIds.map(async (id) => {
            const results = await queryTable('report_row', { filters: { id: String(id), reportId: String(reportId) } });
            return results[0];
        })
    );
    const validRows = rows.filter(r => r);
    if (validRows.length === 0) throw new Error('수정할 데이터가 없습니다.');

    const updaterId = user.id;
    if (user.role === 'VIEWER') {
        const hasUnauthorized = validRows.some(r => r.creatorId !== user.id);
        if (hasUnauthorized) {
            throw new Error('본인이 작성하지 않은 데이터는 일괄 수정할 수 없습니다.');
        }
    }

    for (const row of validRows) {
        const oldDataStr = row.data;
        const parsedOldData = JSON.parse(oldDataStr);
        const rowData = { ...parsedOldData };
        let newValue = params.value;

        if (actionType === 'FIND_REPLACE' && params.find !== undefined && params.replace !== undefined) {
            const currentVal = String(rowData[fieldName] || '');
            newValue = currentVal.replace(new RegExp(params.find, 'g'), params.replace);
            
            if (colDef.type === 'number' || colDef.type === 'currency') {
                const cleanVal = newValue.replace(/[^0-9.-]/g, '').trim();
                newValue = isNaN(Number(cleanVal)) ? newValue : Number(cleanVal);
            }
        }

        if ((colDef.type === 'number' || colDef.type === 'currency') && newValue !== undefined) {
            const sVal = String(newValue);
            const cleanVal = sVal.replace(/[^0-9.-]/g, '').trim();
            if (newValue !== '' && isNaN(Number(cleanVal))) {
                throw new Error(`${fieldName} 필드에는 숫자만 입력 가능합니다.`);
            }
            if (newValue !== '') newValue = Number(cleanVal);
        }

        rowData[fieldName] = newValue;
        const newHash = await generateContentHash(rowData, columns);
        const virtualUpdates: any = {
            data: JSON.stringify(rowData),
            contentHash: newHash,
            updaterId: updaterId,
            updatedAt: new Date().toISOString()
        };

        await updateRows('report_row', virtualUpdates, { filters: { id: String(row.id) } });

        try {
            await ensureHistoryTable();
            await insertRows('report_row_history', [{
                id: generateId(),
                rowId: String(row.id),
                oldData: oldDataStr,
                newData: virtualUpdates.data,
                changeType: 'UPDATE',
                changedById: String(updaterId || 'system'),
                changedAt: new Date().toISOString()
            }]);
        } catch (historyErr) {
            console.error('Failed to insert history log:', historyErr);
        }

        if (report.tableName) {
            try {
                const filters: any = {};
                if (idColName && parsedOldData[idColName]) {
                    filters[idColName] = String(parsedOldData[idColName]);
                } else {
                    columns.forEach((c: any) => {
                        if (parsedOldData[c.name] !== undefined) {
                            filters[c.name] = String(parsedOldData[c.name]);
                        }
                    });
                }
                
                const physicalUpdates: any = {};
                columns.forEach((col: any) => {
                    if (col.name !== idColName && rowData[col.name] !== undefined) {
                        physicalUpdates[col.name] = castToPhysicalValue(rowData[col.name], col.type);
                    }
                });
                await updateRows(report.tableName, physicalUpdates, { filters });
            } catch (err) {
                console.error(`Failed to sync bulk update to physical table ${report.tableName}:`, err);
            }
        }
    }

    revalidatePath(`/report/${reportId}`);
    return { success: true, count: validRows.length };
}

export async function deleteRowsAction(reportId: string, rowIds: string[]) {
    try {
        const user = await getSessionAction();
        if (!user) throw new Error('인증이 필요합니다.');
        const updaterId = user.id;
        const isAuthorized = await checkReportAuthorization(reportId, user.id, user.role);
        if (!isAuthorized) throw new Error('해당 보고서에 대한 접근 권한이 없습니다.');

        const rows = await Promise.all(rowIds.map(async (id) => {
                const results = await queryTable('report_row', { filters: { id: String(id) } });
                return results[0];
            })
        );
        const validRows = rows.filter(r => r);
        if (validRows.length === 0) throw new Error('삭제할 데이터를 찾을 수 없습니다.');

        if (user.role === 'VIEWER') {
            const hasUnauthorized = validRows.some(r => r.creatorId !== user.id);
            if (hasUnauthorized) {
                throw new Error('본인이 작성하지 않은 데이터는 삭제할 수 없습니다.');
            }
        }

        const reports = await queryTable('report', { filters: { id: String(reportId) } });
        const report = reports[0];
        let idColName: string | null = null;
        if (report?.tableName) {
            try {
                const columns = JSON.parse(report.columns);
                const idCol = columns.find((c: any) => c.name === '데이터ID');
                if (idCol) idColName = idCol.name;
            } catch (e) {}
        }

        let syncWarning: string | undefined;
        for (const row of validRows) {
            await updateRows('report_row', {
                isDeleted: 1,
                contentHash: null,
                deletedAt: new Date().toISOString(),
                updaterId: updaterId
            }, { filters: { id: String(row.id) } });

            try {
                await ensureHistoryTable();
                await insertRows('report_row_history', [{
                    id: generateNumericId(),
                    rowId: String(row.id),
                    oldData: row.data,
                    newData: JSON.stringify({ ...JSON.parse(row.data), _deleted: true }),
                    changeType: 'DELETE',
                    changedById: String(updaterId || 'system'),
                    changedAt: new Date().toISOString()
                }]);
            } catch (historyErr) {}

            if (report?.tableName) {
                try {
                    const rowData = JSON.parse(row.data);
                    const filters: any = {};
                    if (idColName && rowData[idColName]) {
                        filters[idColName] = String(rowData[idColName]);
                    } else {
                        const columns = JSON.parse(report.columns);
                        columns.forEach((c: any) => {
                            if (rowData[c.name] !== undefined) {
                                filters[c.name] = String(rowData[c.name]);
                            }
                        });
                    }
                    if (Object.keys(filters).length > 0) {
                        await deleteRows(report.tableName, { filters });
                    }
                } catch (err) {
                    syncWarning = `데이터는 삭제되었지만 물리적 테이블(${report?.tableName}) 동기화에 실패했습니다.`;
                }
            }
        }

        revalidatePath(`/report/${reportId}`);
        revalidatePath('/archive');
        return { success: true, syncWarning };
    } catch (err: any) {
        throw new Error(err.message || '데이터 삭제 중 서버 오류가 발생했습니다.');
    }
}

export async function restoreRowsAction(reportId: string, rowIds: string[]) {
    try {
        const user = await getSessionAction();
        if (!user) return { success: false, error: '인증이 필요합니다.' };
        const updaterId = user.id;
        const isAuthorized = await checkReportAuthorization(reportId, user.id, user.role);
        if (!isAuthorized) return { success: false, error: '해당 보고서에 대한 접근 권한이 없습니다.' };

        const sReportId = String(reportId);
        const validRows: any[] = [];
        for (const id of rowIds) {
            try {
                const results: any = await queryTable('report_row', { filters: { id: String(id) } });
                const rows = (results?.rows || results || []);
                const row = rows[0];
                if (row && (Number(row.isDeleted) === 1 || String(row.isDeleted) === '1' || row.isDeleted === true)) {
                    validRows.push(row);
                }
            } catch (e) {}
        }

        if (validRows.length === 0) return { success: true, restoredCount: 0, syncWarning: '복구할 대상을 찾을 수 없거나 이미 복구되었습니다.' };

        const reportsResult: any = await queryTable('report', { filters: { id: sReportId } });
        const reports = reportsResult?.rows || reportsResult || [];
        const report = reports[0];
        let successCount = 0;
        let failCount = 0;

        for (const row of validRows) {
            try {
                const rowData = JSON.parse(row.data);
                const columns = report.columns ? JSON.parse(report.columns) : [];
                const hash = await generateContentHash(rowData, columns);
                
                const existingResult: any = await queryTable('report_row', {
                    filters: { reportId: sReportId, contentHash: hash, isDeleted: '0' }
                });
                const existing = existingResult.rows || existingResult;
                if (existing.length > 0) {
                    throw new Error(`이미 동일한 내용의 데이터 가 활성 상태로 존재합니다.`);
                }

                if (report?.tableName) {
                    try {
                        await insertRows(report.tableName, [rowData]);
                    } catch (pErr: any) {
                        const msg = String(pErr.message || pErr);
                        if (!(msg.includes('unique') || msg.includes('Duplicate') || msg.includes('exists'))) {
                            throw pErr;
                        }
                    }
                }

                await updateRows('report_row', {
                    isDeleted: 0,
                    contentHash: hash,
                    deletedAt: null,
                    updaterId: updaterId,
                    updatedAt: new Date().toISOString()
                }, { filters: { id: String(row.id) } });

                try {
                    await ensureHistoryTable();
                    await insertRows('report_row_history', [{
                        id: generateNumericId(),
                        rowId: row.id,
                        oldData: row.data,
                        newData: row.data,
                        changeType: 'RESTORE',
                        changedById: updaterId || 'system',
                        changedAt: new Date().toISOString()
                    }]);
                } catch (hErr) {}

                successCount++;
            } catch (rowErr: any) {
                failCount++;
            }
        }

        revalidatePath(`/report/${sReportId}`);
        return { 
            success: successCount > 0, 
            restoredCount: successCount,
            message: failCount > 0 ? `${successCount}건 성공, ${failCount}건 실패` : '성공적으로 복구되었습니다.'
        };
    } catch (err: any) {
        return { success: false, error: '서버 내부 오류가 발생했습니다.' };
    }
}

export async function getRowHistoryAction(rowId: string) {
    try {
        const rows = await queryTable('report_row', { filters: { id: String(rowId) } });
        const row = rows[0];
        if (!row) throw new Error('데이터를 찾을 수 없습니다.');
        const creatorUsers = await queryTable('user', { filters: { id: String(row.creatorId) } });
        const updaterUsers = await queryTable('user', { filters: { id: String(row.updaterId) } });

        let histories: any[] = [];
        try {
            histories = await queryTable('report_row_history', { 
                filters: { rowId: String(rowId) },
                orderBy: 'changedAt',
                orderDirection: 'DESC'
            });
        } catch (e) {
            histories = [];
        }

        const distinctUserIds = Array.from(new Set(histories.map((h: any) => h.changedById).filter(id => !!id)));
        let userMap: Record<string, any> = {};
        if (distinctUserIds.length > 0) {
            const users = await Promise.all(
                distinctUserIds.map(id => queryTable('user', { filters: { id: String(id) } }).then(res => res[0]).catch(() => null))
            );
            users.forEach(u => { if(u) userMap[u.id] = u; });
        }

        const historyWithUsers = histories.map((h: any) => ({
            ...h,
            changedBy: userMap[h.changedById] || (h.changedById === 'system' ? { id: 'system', fullName: '시스템', username: 'system' } : null)
        }));

        return {
            id: row.id,
            data: row.data,
            createdAt: row.createdAt,
            updatedAt: row.updatedAt,
            creator: creatorUsers[0] || null,
            updater: updaterUsers[0] || null,
            histories: historyWithUsers
        };
    } catch (err: any) {
        throw new Error(err.message || '이력을 불러오는 중 서버 오류가 발생했습니다.');
    }
}

export async function checkSyncStatusAction(reportId: string) {
    try {
        const reports = await queryTable('report', { filters: { id: String(reportId) } });
        const report = reports[0];
        if (!report) return { status: 'error' as const, message: '보고서를 찾을 수 없습니다.' };
        if (!report.tableName) return { status: 'no-physical' as const, message: '물리적 테이블 없음' };

        const virtualRowsResponse = await queryTable('report_row', { filters: { reportId: String(reportId) }, limit: 10000 });
        const allVirtualList = Array.isArray(virtualRowsResponse) ? virtualRowsResponse : (virtualRowsResponse?.rows || []);
        const virtualList = allVirtualList.filter((r: any) => !r.isDeleted || r.isDeleted === '0' || r.isDeleted === 0 || r.isDeleted === false);
        const virtualCount = virtualList.length;

        let physicalRows: any[] = [];
        let physicalCount = 0;
        try {
            const pRows = await queryTable(report.tableName, { limit: 10000 });
            physicalRows = Array.isArray(pRows) ? pRows : (pRows?.rows || []);
            physicalCount = physicalRows.length;
        } catch (err) {
            return { status: 'error' as const, message: '물리적 테이블 조회 실패', virtualCount };
        }

        let idColName: string | null = null;
        try {
            const columns = JSON.parse(report.columns);
            const idCol = columns.find((c: any) => c.isAutoGenerated);
            if (idCol) idColName = idCol.name;
        } catch (e) {}

        let missingInPhysical: string[] = [];
        let missingInVirtual: string[] = [];
        if (idColName) {
            const virtualIds = new Set<string>();
            virtualList.forEach((row: any) => {
                try {
                    const data = typeof row.data === 'string' ? JSON.parse(row.data) : row.data;
                    if (data?.[idColName!]) virtualIds.add(String(data[idColName!]));
                } catch (e) {}
            });
            const physicalIds = new Set<string>();
            physicalRows.forEach((row: any) => {
                if (row[idColName!]) physicalIds.add(String(row[idColName!]));
            });
            virtualIds.forEach(id => { if (!physicalIds.has(id)) missingInPhysical.push(id); });
            physicalIds.forEach(id => { if (!virtualIds.has(id)) missingInVirtual.push(id); });
        }

        const isSynced = (virtualCount === physicalCount) && (missingInPhysical.length === 0 && missingInVirtual.length === 0);
        return {
            status: isSynced ? 'synced' as const : 'mismatch' as const,
            virtualCount,
            physicalCount,
            diff: physicalCount - virtualCount,
            missingInPhysical: missingInPhysical.slice(0, 10),
            missingInVirtual: missingInVirtual.slice(0, 10),
            tableName: report.tableName
        };
    } catch (err: any) {
        return { status: 'error' as const, message: err.message || '동기화 상태 확인 실패' };
    }
}

export async function repairVirtualTableAction(reportId: string) {
    try {
        const session = await getSessionAction();
        if (!session || (session.role !== 'ADMIN' && session.role !== 'EDITOR')) {
            return { success: false, error: '접근 권한이 없습니다.' };
        }
        const sReportId = String(reportId);
        const reportsResult: any = await queryTable('report', { filters: { id: sReportId } });
        const reports = reportsResult?.rows || reportsResult || [];
        const report = reports[0];
        if (!report || !report.tableName) return { success: false, message: '보고서 또는 물리 테이블 정보를 찾을 수 없습니다.' };

        const columns = typeof report.columns === 'string' ? JSON.parse(report.columns) : (report.columns || []);
        const idCol = columns.find((c: any) => c.name === '데이터ID');
        const idColName = idCol?.name;
        if (!idColName) return { success: false, message: '기준이 될 "데이터ID" 컬럼을 찾을 수 없습니다.' };

        const [pRowsResponse, vRowsResponse]: any[] = await Promise.all([
            queryTable(report.tableName, { limit: 10000 }).catch(() => ({ rows: [] })),
            queryTable('report_row', { filters: { reportId: sReportId }, limit: 10000 }).catch(() => ({ rows: [] }))
        ]);
        const physicalRows = Array.isArray(pRowsResponse) ? pRowsResponse : (pRowsResponse?.rows || []);
        const virtualRows = Array.isArray(vRowsResponse) ? vRowsResponse : (vRowsResponse?.rows || []);

        const physicalMap = new Map();
        physicalRows.forEach((row: any) => {
            const pk = row[idColName];
            if (pk !== undefined && pk !== null) physicalMap.set(String(pk), row);
        });
        const virtualMap = new Map();
        virtualRows.forEach((row: any) => {
            try {
                const data = typeof row.data === 'string' ? JSON.parse(row.data) : row.data;
                const pk = data?.[idColName];
                if (pk !== undefined && pk !== null) virtualMap.set(String(pk), { rowId: row.id, data });
            } catch (e) {}
        });

        const toInsert: any[] = [];
        const toUpdateItems: any[] = [];
        const toDeleteIds: string[] = [];
        const matchedVirtualRowIds = new Set<string>();

        for (const [pId, pData] of physicalMap.entries()) {
            const vEntry = virtualMap.get(pId);
            if (!vEntry) {
                toInsert.push(pData);
            } else {
                matchedVirtualRowIds.add(vEntry.rowId);
                if (JSON.stringify(vEntry.data) !== JSON.stringify(pData)) {
                    toUpdateItems.push({ id: vEntry.rowId, data: JSON.stringify(pData) });
                }
            }
        }
        virtualRows.forEach((row: any) => {
            if (!matchedVirtualRowIds.has(row.id)) toDeleteIds.push(row.id);
        });

        let successCount = 0;
        let failCount = 0;
        if (toInsert.length > 0) {
            const batchSize = 50;
            for (let i = 0; i < toInsert.length; i += batchSize) {
                const chunk = toInsert.slice(i, i + batchSize).map(pData => ({
                    id: generateNumericId(),
                    reportId: sReportId,
                    data: JSON.stringify(pData),
                    isDeleted: 0,
                    createdAt: new Date().toISOString(),
                    updatedAt: new Date().toISOString()
                }));
                try {
                    await insertRows('report_row', chunk);
                    successCount += chunk.length;
                } catch (e) { failCount += chunk.length; }
            }
        }
        for (const item of toUpdateItems) {
            try {
                await updateRows('report_row', { data: item.data, isDeleted: 0, updatedAt: new Date().toISOString() }, { filters: { id: String(item.id) } });
                successCount++;
            } catch (e) { failCount++; }
        }
        for (const id of toDeleteIds) {
            try {
                await deleteRows('report_row', { filters: { id: String(id) } });
                successCount++;
            } catch (e) { failCount++; }
        }

        try {
            await ensureHistoryTable();
            await insertRows('report_row_history', [{
                id: generateNumericId(),
                rowId: 'SYSTEM_REPAIR',
                oldData: JSON.stringify({ reportId: sReportId, beforeCount: virtualRows.length }),
                newData: JSON.stringify({ added: toInsert.length, deleted: toDeleteIds.length, updated: toUpdateItems.length, successCount, failCount }),
                changeType: 'UPDATE',
                changedById: session.id,
                changedAt: new Date().toISOString()
            }]);
        } catch (hErr) {}

        revalidatePath(`/report/${sReportId}`);
        revalidatePath('/');
        return { success: true, message: `데이터 정합이 완료되었습니다. (처리: ${successCount}건, 실패: ${failCount}건)` };
    } catch (err: any) {
        return { success: false, message: err?.message || '서버 내부 오류가 발생했습니다.' };
    }
}
